Repository kubevirt/containerized-data-importer, pull requests merged in 2018-08, with the labels that each got.

#301 Backports of Cloning PRs #280 and #297 to 1.1 branch
  cmd/cdi-cloner/script.sh
  pkg/controller/util.go
Labels: bug, release-v1.1

#320 Add hash to cluster images
  hack/build/config.sh
Labels: no-merge-til-e2e-testing-done

#326 backport manifests rbac
  manifests/controller/cdi-controller-deployment.yaml
Labels: release-v1.1

#341 local (file://) endpoint deprecation notice
  README.md
  cmd/cdi-importer/importer.go
  pkg/importer/dataStream.go
  pkg/lib/size/size_test.go
  test/functional/importer/datastream/datastream_test.go
Labels: deprecate

#357 Use correct release manifest for CDI controller
  README.md
Labels: doc

#358 fix 'make cluster-up' hang
  cluster/gocli.sh
  hack/build/config.sh
Labels: P1

#356 Sync test http server to cluster in make cluster-sync
  Makefile
  cluster/clean.sh
  cluster/sync.sh
  hack/build/build-cdi-func-test-file-host.sh
  hack/build/config.sh
Labels: P1

#361 Disable .tar.xz until issue 335 is resolved
  pkg/importer/datastream_ginkgo_test.go
Labels: P0

#353 Unify redundant test scripts under test target and aliases
  .travis.yml
  Makefile
  hack/README.md
  hack/build/config.sh
  hack/build/functests.sh
  hack/build/run-functional-tests.sh
  hack/build/run-tests.sh
Labels: P1

#355 Add skip namespace creation flag.
  tests/basic_sanity_test.go
  tests/framework/framework.go
  tests/import_test.go
Labels: P1

#369 Update hack readme
  doc/releases.md
  hack/README.md
Labels: doc

#383 improve hack/readme for TEST_ARGS
  hack/README.md
Labels: doc

#376 E2E Testing - transport protocols
  hack/build/docker/cdi-func-test-file-host-http/Dockerfile
  hack/build/docker/cdi-func-test-file-host-http/htpasswd
  hack/build/docker/cdi-func-test-file-host-http/nginx.conf
  manifests/templates/file-host.yaml.in
  tests/tests_suite_test.go
  tests/transport_test.go
  tests/utils/common.go
  tests/utils/deployments.go
  tests/utils/pod.go
  tests/utils/pvc.go
  tests/utils/secrets.go
  tests/utils/services.go
Labels: WIP

#393 add hack/README documentation for non-standard execution path of functional tests
  hack/README.md
Labels: doc
