Repository kubevirt/containerized-data-importer, pull requests merged in 2018-12, with the labels that each got.

#551 Updated release-description.sh to include relevant info.
  hack/build/release-description.sh
Labels: release-note-none, size/XS

#555 How to create Blank Raw Image User Guide
  doc/blank-raw-image.md
Labels: release-note, size/M

#553 skopeo: use util UnArchiveTar
  cmd/cdi-cloner/clonertarget.go
  cmd/cdi-cloner/clonertarget_test.go
  pkg/image/skopeo.go
  pkg/importer/dataStream.go
  pkg/importer/registry_test.go
  pkg/importer/util.go
  pkg/util/util.go
  tests/transport_test.go
Labels: release-note-none, size/L

#557 Validation fields fix
  manifests/templates/cdi-controller.yaml.in
Labels: release-note-none, size/XS

#533 Update k8s and OS versions.
  automation/check-patch.k8s-1.11.0-release.mounts
  automation/check-patch.k8s-1.11.0-release.packages
  automation/check-patch.k8s-1.11.0-release.sh
  automation/check-patch.openshift-3.11.0-release.mounts
  automation/check-patch.openshift-3.11.0-release.packages
  automation/check-patch.openshift-3.11.0-release.sh
  automation/test.sh
  cluster/up.sh
  hack/README.md
  hack/build/config.sh
  stdci.yaml
  tests/transport_test.go
Labels: do-not-merge/hold, release-note-none, size/M

#552 Fix go report card issues.
  cmd/cdi-importer/importer.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/util/util_test.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/reporters/reporters.go
  tests/utils/secrets.go
Labels: release-note-none, size/S

#563 was incorrectly getting available free space on volume
  cmd/cdi-importer/importer.go
  pkg/system/prlimit.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/pvc.go
Labels: release-note, size/S

#554 leader election for cdi controller
  cmd/cdi-controller/controller.go
  cmd/cdi-controller/leaderelection.go
  glide.lock
  manifests/templates/cdi-controller.yaml.in
  tests/leaderelection_test.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/parser.go
  vendor/github.com/pborman/uuid/CONTRIBUTORS
  vendor/github.com/pborman/uuid/LICENSE
  vendor/github.com/pborman/uuid/dce.go
  vendor/github.com/pborman/uuid/doc.go
  vendor/github.com/pborman/uuid/hash.go
  vendor/github.com/pborman/uuid/json.go
  vendor/github.com/pborman/uuid/json_test.go
  vendor/github.com/pborman/uuid/node.go
  vendor/github.com/pborman/uuid/seq_test.go
  vendor/github.com/pborman/uuid/time.go
  vendor/github.com/pborman/uuid/util.go
  vendor/github.com/pborman/uuid/uuid.go
  vendor/github.com/pborman/uuid/uuid_test.go
  vendor/github.com/pborman/uuid/version1.go
  vendor/github.com/pborman/uuid/version4.go
Labels: release-note-none, size/XXL

#566 manifest/example/local-pv-allocation-claim.yaml fails on validation #565
  manifests/example/local-pv-allocation-claim.yaml
Labels: release-note-none, size/S

#562 api server not validating client cert
  pkg/apiserver/apiserver.go
Labels: release-note-none, size/XS

#569 Add doc how to build a registry image with VM disk
  doc/image-from-registry.md
Labels: release-note-none, size/M

#575 fix: Handle sparse files when cloning
  cmd/cdi-cloner/cloner_startup.sh
Labels: release-note, size/XS

#577 manifests example: import registry image
  doc/image-from-registry.md
  manifests/example/registry-image-pvc.yaml
Labels: release-note-none, size/M

#567 API validation test
  tests/api_validation_test.go
  tests/manifests/datavolume.yaml
Labels: release-note-none, size/L

#573 Clone sometimes doesn't add k8s.io/CloneOf annotation to target PVC #560
  pkg/controller/clone-controller.go
Labels: release-note-none, size/XS

#570 Add Registry source validation to Datavolume
  manifests/templates/cdi-controller.yaml.in
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  pkg/apiserver/webhooks/validating-webhook/validating-webhook_test.go
Labels: release-note-none, size/M

#576 Correct singularName for UploadTokenRequests
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
Labels: release-note, size/XS

#578 don't specify storage class in example dv manifest
  manifests/example/datavolume.yaml
Labels: release-note-none, size/XS

#528 Ingress/Route manifests for Upload
  doc/exposing-upload-proxy.md
  manifests/templates/cdi-uploadproxy-ingress.yaml.in
  manifests/templates/cdi-uploadproxy-route.yaml.in
Labels: release-note, size/L

#568 Adding more functional tests for blank-raw-image, PV allocation on specific node and upload disk image features
  tests/datavolume_test.go
  tests/framework/exec_util.go
  tests/framework/pv.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/local_volume_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/cli.go
  tests/utils/datavolume.go
  tests/utils/pod.go
  tests/utils/pv.go
  tests/utils/pvc.go
  tests/utils/upload.go
Labels: release-note-none, size/XL

#582 disable more data stream tests
  pkg/importer/dataStream_test.go
Labels: release-note-none, size/XS

#572 Add Blank Image source to Datavolume validation
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
Labels: release-note-none, size/XS
