Repository kubevirt/containerized-data-importer, pull requests merged in 2018-10, with the labels that each got.

#460 deprecation of local endpoint support
  README.md
  cmd/cdi-importer/importer.go
  hack/build/run-functional-tests.sh
  pkg/image/qemu_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/datastream_ginkgo_test.go
  pkg/importer/datastream_suite_test.go
  pkg/importer/importer_test.go
  pkg/lib/size/size.go
  pkg/lib/size/size_test.go
  pkg/util/util.go
  pkg/util/util_suite_test.go
  pkg/util/util_test.go
  tests/images/namespace.txt
Labels: release-note, size/XXL

#475 Reenable and fix prlimit test
  pkg/system/prlimit_suite_test.go
  pkg/system/prlimit_test.go
Labels: release-note-none, size/S

#477 Properly fix concurrency issue with QEMU cmd
  pkg/system/prlimit.go
  tests/utils/pod.go
Labels: release-note-none, size/S

#479 add timeout to http client
  pkg/importer/dataStream.go
Labels: release-note, size/XS

#480 clean up if qemu-img fails
  hack/build/docker/cdi-func-test-file-host-http/Dockerfile
  pkg/image/qemu.go
Labels: release-note-none, size/XS

#487 Set fixed OCP console port in dev environment
  cluster/up.sh
Labels: release-note-none, size/XS

#483 Remove old commented out lintcheck code
  hack/build/run-lint-checks.sh
Labels: release-note-none, size/XS

#481 Set pod restart policy to "OnFailure" and cleanup succesful pods
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils.go
Labels: release-note, size/L

#485 Orchestrate upload using a DataVolume
  manifests/example/upload-datavolume.yaml
  manifests/example/upload-dv-token.yaml
  pkg/apis/datavolumecontroller/v1alpha1/types.go
  pkg/apis/datavolumecontroller/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: release-note-none, size/L

#486 add events to DataVolume controller
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note-none, size/L

#427 CDI e2e negative tests
  tests/cloner_test.go
  tests/import_test.go
  tests/transport_test.go
  tests/utils/pod.go
  tests/utils/pvc.go
  tests/utils/secrets.go
Labels: size/L

#493 force delete upload pod if not completed and pvc deleted
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
Labels: release-note-none, size/M

#495 Import pvc 'cdi.kubevirt.io/storage.pod.phase' annotation valu…
  pkg/controller/import-controller.go
Labels: release-note-none, size/XS

#499 Add test-lint target to README
  hack/README.md
Labels: release-note-none, size/XS

#502 Add structure to hold all CDI importer environment variables #501
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/M

#508 Fix typos in common.go
  pkg/common/common.go
Labels: release-note-none, size/XS

#510 Update datavolume_test.go
  tests/datavolume_test.go
Labels: do-not-merge/release-note-label-needed, size/XS
