Repository kubevirt/containerized-data-importer, pull requests merged in 2018-07, with the labels that each got.

#219 [WIP] Host-assisted cloning integrated to CDI
  cmd/controller/controller.go
  manifests/cloner/Dockerfile
  manifests/cloner/script.sh
  manifests/example/target-pvc.yaml
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/util.go
Labels: Do Not Merge

#291 Update RBAC for PVC owner references
  manifests/templates/cdi-controller.yaml.in
Labels: release-v1.1

#293 Use the correct API group for import pod owner reference
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: bug, release-v1.1
