Repository kubevirt/containerized-data-importer, pull requests merged in 2019-12, with the labels that each got.

#1038 Add node to node clone functional test
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1037 Push builder image to dockerhub
  .travis.yml
  Makefile
  hack/build/bazel-build-builder.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1046 Updated clone across nodes to make sure we have PVs on at least 2 nod…
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1045 Fix strings to check against in validation for k8s 1.16
  tests/api_validation_test.go
  tests/utils/deployments.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1047 make operator more resilient when creating ownership ConfigMap fails
  pkg/operator/controller/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1050 Added support for OKD-4.3 lane
  cluster-sync/okd-4.3/ceph_sc.yaml
  cluster-sync/okd-4.3/provider.sh
  cluster-sync/okd-4.3/rook_ceph.yaml
  cluster-up/cluster/okd-4.3/provider.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1049 Add nil check for ingress http rule
  go.mod
  pkg/controller/config-controller.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1034 Use controller library for config controller
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  go.mod
  go.sum
  pkg/controller/BUILD.bazel
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/runtime-util.go
  pkg/controller/util.go
  pkg/operator/resources/cluster/controller.go
  tests/BUILD.bazel
  tests/cdiconfig_test.go
  tests/leaderelection_test.go
  tests/manifests/ingressNetworkApigroup.yaml
  tests/manifests/ingressNoHttp.yaml
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#997 Use an existing bazel-builder image instead of building it every time
  hack/build/bazel-build-builder.sh
  hack/build/bazel-docker.sh
  hack/build/config.sh
  hack/build/in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1051 Fix build and push of builder image
  hack/build/bazel-build-builder.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1052 Add missing parenthesis
  hack/build/bazel-build-builder.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1056 Setup hostpath provisioner as an option in ci.
  cluster-sync/k8s-1.16.2/provider.sh
  go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1057 Move CDI config related functions to config controller from utils.
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1060 Enable hostpath provisioner for OKD 4.3 kubevirtci provider.
  cluster-sync/ephemeral_provider.sh
  cluster-sync/k8s-1.16.2/provider.sh
  cluster-sync/okd-4.3/hpp-master-mc.yaml
  cluster-sync/okd-4.3/hpp-worker-mc.yaml
  cluster-sync/okd-4.3/provider.sh
  cluster-up/cluster/okd-4.3/provider.sh
  hack/README.md
  tests/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
