Repository kubevirt/containerized-data-importer, pull requests merged in 2019-02, with the labels that each got.

#634 delete .test.swp file
  .gitignore
  .test.swp
Labels: release-note-none, size/XS

#638 fix for issue #636: can't create/delete/create the same datavolume
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note-none, size/M

#645 backport of #644 to release-v1.5
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
Labels: release-note-none, size/M

#644 Import pod status should not be 'Failed' when starting up
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
Labels: release-note-none, size/M

#655 add a random go file to satisfy dep package manager
  doc.go
Labels: release-note, size/S

#657 Typo
  doc/datavolumes.md
Labels: do-not-merge/release-note-label-needed, size/XS

#658 Fix validate space constraints to properly validate the space needed.
  pkg/importer/dataStream.go
Labels: release-note-none, size/M

#653 Imported iso image file should not be resized
  pkg/importer/dataStream.go
  tests/transport_test.go
Labels: release-note, size/M

#661 secure registry import
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  hack/build/docker/cdi-func-test-registry-init/Dockerfile
  manifests/example/registry-image-pvc.yaml
  manifests/templates/registry-host.yaml.in
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/skopeo.go
  pkg/image/skopeo_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
  tests/datavolume_test.go
  tests/transport_test.go
  tests/utils/common.go
  tests/utils/configmaps.go
  tools/cdi-func-test-registry-init/main.go
Labels: release-note-none, size/L

#662 secure registry 1.5
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  hack/build/docker/cdi-func-test-registry-init/Dockerfile
  manifests/example/registry-image-pvc.yaml
  manifests/templates/registry-host.yaml.in
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/skopeo.go
  pkg/image/skopeo_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
  tests/datavolume_test.go
  tests/transport_test.go
  tests/utils/common.go
  tests/utils/configmaps.go
  tools/cdi-func-test-registry-init/main.go
Labels: release-note-none, size/L

#660 Remove unused code
  pkg/util/util.go
Labels: release-note-none, size/M

#669 only limit "qemu-img info"
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/image/skopeo.go
Labels: release-note-none, size/M

#650 Delete importer pod on pvc delete request
  pkg/controller/controller.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  tests/import_test.go
Labels: release-note-none, size/M

#647 reject DataVolume creation with already exisiting destination PVC
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/validating-webhook/util.go
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  tests/api_validation_test.go
Labels: release-note, size/M

#673 use port forwarding for upload tests instead of ssh to node01
  tests/upload_test.go
  tests/utils.go
  tests/utils/upload.go
Labels: release-note-none, size/L

#663 add configmap for insecure registries
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/qemu_test.go
  pkg/image/skopeo.go
  pkg/image/skopeo_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/namespaced/controller.go
  tests/transport_test.go
  tests/utils/configmaps.go
Labels: release-note, size/L

#671 Add info on kubectl port-fwd to upload doc
  doc/upload.md
Labels: release-note-none, size/XS

#675 Make the CDI Config more resilient to runtime errors
  pkg/controller/config-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/S

#676 update go to 1.11.5
  .travis.yml
  hack/build/docker/builder/Dockerfile
  pkg/image/qemu.go
  pkg/importer/dataStream.go
  pkg/operator/api.go
  pkg/uploadserver/uploadserver.go
  tools/openapi-spec-generator/openapi.go
Labels: release-note-none, size/S
