Repository kubevirt/containerized-data-importer, pull requests merged in 2019-10, with the labels that each got.

#981 Wait for SC to be available before making it default
  cluster-sync/okd-4.1/provider.sh
  tests/leaderelection_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#983 additional RBAC test
  tests/rbac_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#982 Remove OLM integration as we aren't using it.
  .travis.yml
  Makefile
  README.md
  cluster-sync/external/install.sh
  cluster-sync/install-config.sh
  cluster-sync/install.sh
  cluster-sync/k8s-1.13.3/install.sh
  cluster-sync/k8s-1.15.1/install.sh
  cluster-sync/okd-4.1/install.sh
  cluster-sync/os-3.11.0-crio/install.sh
  cluster-sync/sync.sh
  doc/cdi-operator-olm.md
  hack/README.md
  hack/build/build-cdi-olm-catalog.sh
  hack/build/build-copy-artifacts.sh
  hack/build/build-manifests.sh
  hack/build/config.sh
  hack/build/docker/cdi-olm-catalog/Dockerfile
  hack/build/docker/cdi-operator/Dockerfile
  hack/build/olm.sh
  manifests/templates/cdi-controller.yaml.in
  manifests/templates/cdi-uploadproxy-ingress.yaml.in
  manifests/templates/cdi-uploadproxy-route.yaml.in
  manifests/templates/release/olm/bundle/cdi-crds.yaml.in
  manifests/templates/release/olm/bundle/cdi-package.yaml.in
  manifests/templates/release/olm/bundle/cdioperator.VERSION.csv.yaml.in
  manifests/templates/release/olm/cdi-csv-preconditions.yaml.in
  manifests/templates/release/olm/k8s/cdi-catalogsource-registry.yaml.in
  manifests/templates/release/olm/k8s/cdi-catalogsource.yaml.in
  manifests/templates/release/olm/k8s/cdi-operatorsource.yaml.in
  manifests/templates/release/olm/k8s/cdi-subscription.yaml.in
  manifests/templates/release/olm/operatorgroup.yaml.in
  manifests/templates/release/olm/os/cdi-catalogsource-registry.yaml.in
  manifests/templates/release/olm/os/cdi-catalogsource.yaml.in
  manifests/templates/release/olm/os/cdi-operatorsource.yaml.in
  manifests/templates/release/olm/os/cdi-subscription.yaml.in
  tools/cdi-olm-catalog/main.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/XXL

#988 Increase DV state timeout for multiple clone tests
  tests/cloner_test.go
  tests/utils/datavolume.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/S

#987 Unique client cert per clone source pod
  cmd/cdi-uploadserver/uploadserver.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/cloner_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/XXL

#927 added CRD open API schema validation and unit tests
  go.mod
  go.sum
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/operator/operator_test.go
  vendor/github.com/RHsyseng/operator-utils/LICENSE
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_sync.go
  vendor/github.com/emicklei/go-restful-openapi/build_path.go
  vendor/github.com/emicklei/go-restful-openapi/definition_builder.go
  vendor/github.com/gregjones/httpcache/httpcache.go
  vendor/github.com/minio/minio-go/retry.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/golang.org/x/net/html/entity.go
  vendor/gopkg.in/tomb.v1/tomb.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/k8s.io/api/apps/v1beta2/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/autoscaling/v2beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/extensions/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/storage/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/storage/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/api/meta/meta.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL

#992 Update kubevirt ci image to have valid certificates.
  cluster-up/check.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.14.2/manifests/network_config_policy.yaml
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/okd-4.1/provider.sh
  hack/update-codegen.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/L

#990 Provide general overview of source and contentType in README
  README.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#993 Fix push failing on target that is no longer relevant.
  Makefile
  hack/build/build-docker.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#995 [skip ci] Enable bazel cache
  automation/check-patch.k8s-1.15.1-release.mounts
  automation/check-patch.k8s-1.15.1-release.packages
  automation/check-patch.k8s-1.15.1-release.sh
  automation/check-patch.k8s-1.15.1-release.yumrepos
  automation/check-patch.mounts
  automation/check-patch.okd-4.1-release.mounts
  automation/check-patch.okd-4.1-release.packages
  automation/check-patch.okd-4.1-release.sh
  automation/check-patch.okd-4.1-release.yumrepos
  automation/check-patch.openshift-3.11.0-crio-release.mounts
  automation/check-patch.openshift-3.11.0-crio-release.packages
  automation/check-patch.openshift-3.11.0-crio-release.sh
  automation/check-patch.openshift-3.11.0-crio-release.yumrepos
  automation/check-patch.packages.el7
  automation/check-patch.sh
  automation/check-patch.yumrepos
  automation/test.sh
  go.mod
  go.sum
  pkg/controller/BUILD.bazel
  pkg/operator/resources/operator/BUILD.bazel
  pkg/system/prlimit_test.go
  tests/cloner_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/XL

#998 Fix rfe id & test id issues
  tests/cloner_test.go
  tests/datavolume_test.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/S

#996 uploadproxy should use pod ready annotation
  pkg/operator/resources/cluster/uploadproxy.go
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  tests/upload_test.go
  tests/utils/pvc.go
  tests/utils/upload.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/L

#1000 Don't fail immediately when Local is not found when syncing.
  cluster-sync/okd-4.1/provider.sh
Labels: dco-signoff: yes, release-note-none, size/XS
