Repository kubevirt/containerized-data-importer, pull requests merged in 2019-07, with the labels that each got.

#871 Update ref_id in QCOW tests
  tests/datavolume_test.go
Labels: release-note-none, size/XS

#872 fix cluster-sync for okd
  cluster-sync/okd-4.1.0/create-local-storage-cr.yaml
  cluster-sync/okd-4.1.0/provider.sh
  cluster-up/ssh.sh
Labels: release-note-none, size/S

#875 make clone pods use selinux type spc_t instead of privileged
  hack/build/run-functional-tests.sh
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/upload.go
Labels: release-note-none, size/L

#869 Validating webhook and token authorization for PVC cloning
  cmd/cdi-controller/controller.go
  doc/RBAC.md
  pkg/apis/core/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/util.go
  pkg/apiserver/webhooks/api/clone-validate.go
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/scheme.go
  pkg/apiserver/webhooks/validating-webhook/util.go
  pkg/apiserver/webhooks/webhook_suite_test.go
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/operator/operator.go
  pkg/token/token.go
  pkg/token/token_test.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  tests/cloner_test.go
  tests/framework/framework.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
  tests/webhook_test.go
Labels: release-note, size/XXL

#878 Switch to default namespace after creating local storage.
  cluster-sync/okd-4.1.2/provider.sh
Labels: release-note-none, size/XS

#882 fix flaky webhook test
  tests/webhook_test.go
Labels: release-note-none, size/XS

#886 * make file fix: all target requires manifests
  Makefile
Labels: release-note-none, size/XS

#884 token validation broken
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/upload_test.go
Labels: release-note-none, size/L

#881 Add the option to change the operator name
  pkg/operator/resources/operator/components.go
Labels: do-not-merge/release-note-label-needed, size/XS

#887 Backport 884
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/upload_test.go
Labels: release-note-none, size/L

#891 Call make manifests during publish as well.
  .travis.yml
  Makefile
  hack/build/build-manifests.sh
Labels: release-note-none, size/S

#896 Fix install instruction for 1.10+
  README.md
Labels: release-note-none, size/XS

#894 mutating webhook registration broken
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
Labels: release-note-none, size/L

#899 Pass annotations from DV to PVC.
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: release-note-none, size/S

#898 Fix path to exported artifacts.
  automation/test.sh
Labels: release-note-none, size/XS

#900 Pass annotations to PVC from data volume.
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: release-note-none, size/S

#901 Pass annotations to PVC from data volume.
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: release-note-none, size/S

#904 Fix CPU limit no longer working.
  pkg/system/prlimit.go
  pkg/system/prlimit_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/M
