Repository kubevirt/containerized-data-importer, pull requests merged in 2019-09, with the labels that each got.

#948 Set conditions properly while deploying.
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
Labels: release-note-none, size/L

#951 Make sure input is not same as output directory when building olm-cat…
  hack/build/docker/cdi-olm-catalog/Dockerfile
Labels: release-note-none, size/XS

#952 Make sure input is not same as output directory when building olm-cat…
  hack/build/docker/cdi-olm-catalog/Dockerfile
Labels: release-note-none, size/XS

#950 Set conditions properly while deploying. (#948)
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
Labels: release-note-none, size/L

#949 Fix leader election test with import by not scaling.
  tests/leaderelection_test.go
Labels: release-note-none, size/L

#953 Fix transport tests to work with ceph file system.
  tests/framework/pvc.go
  tests/import_test.go
  tests/transport_test.go
Labels: release-note-none, size/M

#954 Add upgrade from release version 1.10.4 to current master.
  automation/test.sh
  cluster-sync/install.sh
  cluster-sync/okd-4.1/install.sh
  cluster-sync/sync.sh
  pkg/operator/controller/controller.go
Labels: release-note-none, size/M

#957 Restore backwards compatible docker syntax
  hack/build/docker/cdi-olm-catalog/Dockerfile
Labels: release-note-none, size/XS

#956 set ceph to be default sc
  cluster-sync/k8s-1.13.3/provider.sh
  tests/framework/pvc.go
  tests/local_volume_test.go
Labels: do-not-merge/hold, release-note-none, size/S

#959 Use right lane k8s-1.15.1, and verify that --enable-ceph is set.
  cluster-sync/k8s-1.13.3/provider.sh
  cluster-sync/k8s-1.15.1/provider.sh
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/smartclone_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/upload.go
Labels: release-note-none, size/M

#960 Don't hard code CDI CR object name to be cdi in tests.
  tests/operator_test.go
Labels: release-note-none, size/XS

#961 create aggregate cluster roles
  manifests/templates/release/cdi-operator.yaml.in
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/rbac.go
  pkg/operator/resources/operator/operator.go
  tests/rbac_test.go
  tests/webhook_test.go
  tools/manifest-generator/manifest-generator.go
Labels: release-note, size/XL

#962 Creating a blank disk on a block device
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/import_test.go
  tests/utils/datavolume.go
Labels: release-note, size/M

#964 Creating blank disk on a block device (#962)
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/import_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/M

#965 Backport 961
  manifests/templates/release/cdi-operator.yaml.in
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/rbac.go
  pkg/operator/resources/operator/operator.go
  tests/rbac_test.go
  tests/webhook_test.go
  tools/manifest-generator/manifest-generator.go
Labels: release-note-none, size/XL

#966 Sparsify clone tarring
  cluster-sync/k8s-1.15.1/provider.sh
  cmd/cdi-cloner/cloner_startup.sh
Labels: release-note, size/M

#968 Added unit test to verify quantity returns right value.
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  tests/utils/pod.go
Labels: release-note-none, size/S

#969 delete RBAC tests for unexpected aggregated PolicyRules
  tests/rbac_test.go
Labels: release-note-none, size/M

#971 backport #969
  tests/rbac_test.go
Labels: release-note-none, size/M

#970 falloc on resize and blank disk.
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/pod.go
Labels: dco-signoff: yes, release-note, size/L

#972 Sparsify clone tarring. (#966)
  cluster-sync/k8s-1.15.1/provider.sh
  cmd/cdi-cloner/cloner_startup.sh
Labels: dco-signoff: yes, release-note-none, size/M

#974 Add node selector for VerifyPvcEmpty pod
  tests/framework/pvc.go
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/pod.go
Labels: dco-signoff: yes, release-note-none, size/M

#977 Select a schedulable node in local PV test
  tests/local_volume_test.go
  tests/utils/pod.go
Labels: dco-signoff: yes, release-note-none, size/S

#979 apiserver not translating HTTP method
  pkg/apiserver/authorizer.go
  pkg/apiserver/authorizer_test.go
  pkg/operator/resources/cluster/rbac.go
  tests/rbac_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#980 backport #979
  pkg/apiserver/authorizer.go
  pkg/apiserver/authorizer_test.go
  pkg/operator/resources/cluster/rbac.go
  tests/rbac_test.go
Labels: dco-signoff: yes, release-note-none, size/S
