Repository kubevirt/containerized-data-importer, pull requests merged in 2019-04, with the labels that each got.

#736 PVC accessModes should be a required field
  pkg/operator/resources/cluster/datavolume.go
  tests/api_validation_test.go
  tests/manifests/dvMissingPVCAccessModes.yaml
Labels: release-note, size/S

#738 Fixing issue 737 - update import-block-pv.md
  doc/import-block-pv.md
Labels: release-note-none, size/XS

#712 import/upload tests should not look for pods if they may not exist
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/pvc.go
  tests/utils/upload.go
Labels: release-note-none, size/L

#739 Disable flaky unit test related to CDI Config
  pkg/controller/config-controller_test.go
Labels: release-note-none, size/M

#740 Fix for issue #1690415 - CDI appends 'source pod' to a label and may fail on error that label must not be longer than 63 characters
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/M

#744 Display error message when importer pod is passed none source and arc…
  cmd/cdi-importer/importer.go
Labels: release-note, size/XS

#595 Update Datavolume status to include progress
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/utils/datavolume.go
Labels: release-note, size/L

#730 Update fedora base image to fedora 29 for containers.
  automation/check-patch.k8s-1.13.3-release.yumrepos
  automation/check-patch.openshift-3.11.0-release.yumrepos
  automation/check-patch.yumrepos
  hack/build/build-cdi-func-test-registry-host.sh
  hack/build/docker/builder/Dockerfile
  hack/build/docker/cdi-apiserver/Dockerfile
  hack/build/docker/cdi-cloner/Dockerfile
  hack/build/docker/cdi-controller/Dockerfile
  hack/build/docker/cdi-func-test-file-host-http/Dockerfile
  hack/build/docker/cdi-func-test-file-host-http/fedora.repo
  hack/build/docker/cdi-func-test-file-host-init/Dockerfile
  hack/build/docker/cdi-func-test-file-host-init/fedora.repo
  hack/build/docker/cdi-func-test-registry-init/Dockerfile
  hack/build/docker/cdi-func-test-registry-init/fedora.repo
  hack/build/docker/cdi-func-test-registry-populate/Dockerfile
  hack/build/docker/cdi-func-test-registry-populate/fedora.repo
  hack/build/docker/cdi-importer/Dockerfile
  hack/build/docker/cdi-importer/fedora.repo
  hack/build/docker/cdi-operator/Dockerfile
  hack/build/docker/cdi-uploadproxy/Dockerfile
  hack/build/docker/cdi-uploadserver/Dockerfile
  hack/build/docker/cdi-uploadserver/fedora.repo
  tests/utils/pod.go
Labels: do-not-merge/hold, release-note, size/L

#742 Support matrix
  doc/scratch-space.md
  doc/supported_operations.md
Labels: release-note-none, size/S

#747 Unable to get progress metrics is not an error.
  pkg/controller/datavolume-controller.go
Labels: release-note-none, size/XS

#749 add a better error message if pvc size is missing
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  tests/api_validation_test.go
  tests/manifests/dvMissingPVCSize.yaml
Labels: release-note, size/S

#629 Adding support to clone disk image from one Raw Block PV to another
  cmd/cdi-cloner/cloner_startup.sh
  cmd/cdi-cloner/clonertarget.go
  doc/clone-block-datavolume.md
  hack/build/docker/cdi-cloner/Dockerfile
  hack/build/docker/cdi-func-test-block-device/entrypoint.sh
  manifests/example/clone-block-datavolume.yaml
  manifests/templates/block-device.yaml.in
  pkg/common/common.go
  pkg/controller/clone-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/http-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/util/util.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/pod.go
  tests/utils/pv.go
Labels: release-note, size/XL

#750 Adding a description about Block volumeMode field in a DataVolume manifest
  doc/datavolumes.md
Labels: release-note-none, size/S

#733 Adding support to upload disk image to a Raw Block PV
  manifests/example/upload-block-datavolume-token.yaml
  manifests/example/upload-block-datavolume.yaml
  pkg/controller/util.go
  tests/upload_test.go
  tests/utils/pvc.go
  tests/utils/upload.go
Labels: release-note, size/L

#754 Change the prometheus label used by cdi.
  pkg/common/common.go
Labels: release-note-none, size/XS

#756 Clarify upload scratch space usage.
  doc/supported_operations.md
Labels: release-note-none, size/XS

#757 apiserver should return RootPaths
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
Labels: release-note-none, size/M

#752 allow for override of registry and tag in CDI object
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
Labels: release-note-none, size/L

#758 BACKPORT to 1.8 - apiserver should return RootPaths
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
Labels: release-note-none, size/M

#760 Make curl silent on install instructions
  README.md
Labels: release-note-none, size/XS

#751 Fix example links in datavolume documentation.
  doc/datavolumes.md
  manifests/example/vm-dv.yaml
Labels: release-note-none, size/M

#755 Verify source and target PVC are correct before proceeding with clone.
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/L

#763 Ingress should not be required to have a label
  cmd/cdi-controller/controller.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
Labels: release-note-none, size/M

#766 Fix link to example in REAdME
  README.md
Labels: release-note-none, size/XS

#764 fix link in exposing upload proxy document
  doc/exposing-upload-proxy.md
Labels: release-note-none, size/XS

#762 Fix issues with size header in cloning sometimes reading beginning of…
  cmd/cdi-cloner/cloner_startup.sh
  cmd/cdi-cloner/clonertarget.go
  cmd/cdi-cloner/clonertarget_test.go
  hack/build/docker/cdi-cloner/Dockerfile
  pkg/util/util.go
  tests/cloner_test.go
  tests/framework/pv.go
  tests/framework/pvc.go
  tests/images/totalsize.txt
  tests/import_test.go
  tests/upload_test.go
Labels: release-note-none, size/L

#767 Fix support matrix for registry
  doc/supported_operations.md
Labels: release-note-none, size/XS

#771 Extra logging for cloner target
  cmd/cdi-cloner/clonertarget.go
Labels: release-note-none, size/XS

#770 Before writing import, clean target filesystem.
  pkg/importer/data-processor.go
  pkg/importer/util.go
Labels: release-note-none, size/S
