Repository kubevirt/containerized-data-importer, pull requests merged in 2019-03, with the labels that each got.

#652 ready checks for all upload components
  cmd/cdi-controller/controller.go
  cmd/cdi-uploadserver/uploadserver.go
  hack/build/build-copy-artifacts.sh
  hack/build/docker/cdi-apiserver/Dockerfile
  hack/build/docker/cdi-uploadproxy/Dockerfile
  hack/build/docker/cdi-uploadserver/Dockerfile
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/common.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/factory.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/upload_test.go
Labels: release-note, size/L

#683 update k8s to latest kubevirtci version (openshift is fine)
  hack/build/config.sh
Labels: release-note-none, size/XS

#682 Update examples to use data volumes everywhere.
  doc/annotations.md
  doc/blank-raw-image.md
  doc/image-from-registry.md
  doc/local-pv-allocation.md
  doc/upload.md
  manifests/example/blank-image-datavolume.yaml
  manifests/example/blank-image-pvc.yaml
  manifests/example/clone-datavolume.yaml
  manifests/example/example-clone-dv.yaml
  manifests/example/example-import-dv.yaml
  manifests/example/example-vm-dv.yaml
  manifests/example/golden-pvc.yaml
  manifests/example/import-archive-datavolume.yaml
  manifests/example/import-archive-pvc.yaml
  manifests/example/import-kubevirt-datavolume-secret.yaml
  manifests/example/import-kubevirt-datavolume.yaml
  manifests/example/local-pv-allocation-claim.yaml
  manifests/example/local-pv-allocation.yaml
  manifests/example/prometheus.yaml
  manifests/example/registry-image-datavolume.yaml
  manifests/example/registry-image-pvc.yaml
  manifests/example/target-pvc.yaml
  manifests/example/upload-datavolume-token.yaml
  manifests/example/upload-pvc.yaml
  manifests/example/upload-token.yaml
Labels: release-note-none, size/XL

#688 make CDIConfig client cluster scoped and fix occasional crash
  api/openapi-spec/swagger.json
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1alpha1/types.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/cdi.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/cdiconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_cdi.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_cdiconfig.go
  pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go
  pkg/client/informers/externalversions/core/v1alpha1/cdi.go
  pkg/client/informers/externalversions/core/v1alpha1/cdiconfig.go
  pkg/client/informers/externalversions/core/v1alpha1/interface.go
  pkg/client/listers/core/v1alpha1/cdi.go
  pkg/client/listers/core/v1alpha1/cdiconfig.go
  pkg/client/listers/core/v1alpha1/expansion_generated.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/L

#689 use pullPolicy=Always for openshift
  cluster/sync.sh
  hack/build/config.sh
  manifests/templates/cdi-operator.yaml.in
  pkg/operator/resources/namespaced/controller.go
Labels: release-note-none, size/S

#646 Update README
  README.md
Labels: release-note-none, size/L

#677 Test prometheus endpoint existence.
  hack/build/docker/cdi-func-test-file-host-http/Dockerfile
  hack/build/docker/cdi-func-test-file-host-http/nginx.conf
  manifests/templates/file-host.yaml.in
  pkg/image/qemu.go
  tests/framework/framework.go
  tests/import_test.go
  tests/utils/common.go
Labels: release-note-none, size/L

#690 make uploadproxy slightly more resilient to network errors
  pkg/uploadproxy/uploadproxy.go
Labels: release-note-none, size/XS

#685 Test attribute for API validation
  tests/api_validation_test.go
Labels: release-note-none, size/M

#693 Update dependencies to latest
  glide.lock
  vendor/github.com/go-ini/ini/bench_test.go
  vendor/github.com/go-ini/ini/file.go
  vendor/github.com/go-ini/ini/file_test.go
  vendor/github.com/go-ini/ini/ini.go
  vendor/github.com/go-ini/ini/ini_internal_test.go
  vendor/github.com/go-ini/ini/ini_test.go
  vendor/github.com/go-ini/ini/key.go
  vendor/github.com/go-ini/ini/key_test.go
  vendor/github.com/go-ini/ini/parser.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/json_test.go
  vendor/github.com/pkg/errors/stack.go
  vendor/github.com/ulikunitz/xz/TODO.md
  vendor/github.com/ulikunitz/xz/cmd/gxz/licenses.go
  vendor/github.com/ulikunitz/xz/cmd/gxz/version.go
  vendor/github.com/ulikunitz/xz/cmd/xb/copyright.go
  vendor/github.com/ulikunitz/xz/cmd/xb/version.go
  vendor/github.com/ulikunitz/xz/doc/relnotes/release-v0.5.6.md
  vendor/github.com/ulikunitz/xz/go.mod
  vendor/go.uber.org/zap/example_test.go
  vendor/google.golang.org/appengine/appengine.go
  vendor/google.golang.org/appengine/datastore/query.go
  vendor/google.golang.org/appengine/datastore/query_test.go
  vendor/google.golang.org/appengine/internal/api.go
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/jwt/claims.go
  vendor/gopkg.in/square/go-jose.v2/jwt/claims_test.go
  vendor/gopkg.in/square/go-jose.v2/jwt/errors.go
  vendor/gopkg.in/square/go-jose.v2/jwt/jwt.go
  vendor/gopkg.in/square/go-jose.v2/jwt/jwt_test.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation.go
  vendor/gopkg.in/square/go-jose.v2/jwt/validation_test.go
  vendor/sigs.k8s.io/testing_frameworks/integration/apiserver.go
  vendor/sigs.k8s.io/testing_frameworks/integration/etcd.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/integration_tests/integration_test.go
  vendor/sigs.k8s.io/testing_frameworks/integration/internal/process.go
Labels: release-note-none, size/XL

#686 https cert configuration
  cluster/clean.sh
  hack/build/docker/cdi-func-test-file-host-http/nginx.conf
  manifests/templates/file-host.yaml.in
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  tests/datavolume_test.go
  tests/transport_test.go
  tests/utils/certs.go
  tests/utils/common.go
  tests/utils/configmaps.go
  tests/utils/datavolume.go
  tools/cdi-func-test-file-host-init/main.go
  tools/cdi-func-test-registry-init/main.go
Labels: release-note-none, size/L

#680 Reject cloning using DataVolume if source PVC doesn't exist.
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  tests/api_validation_test.go
Labels: release-note, size/M

#659 Scratch space retry framework logic.
  cmd/cdi-importer/importer.go
  hack/build/run-tests.sh
  pkg/common/common.go
  pkg/controller/clone-controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/skopeo.go
  pkg/image/skopeo_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
  pkg/importer/util.go
  pkg/operator/resources/cluster/controller.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/basic_sanity_test.go
  tests/upload_test.go
  tests/utils/pvc.go
Labels: release-note, size/XXL

#697 Correct datavol src:registry example manifest
  manifests/example/registry-image-datavolume.yaml
Labels: release-note-none, size/XS

#695 refresh docs for uploadproxy reencrypt routes
  doc/exposing-upload-proxy.md
  doc/upload.md
Labels: release-note-none, size/M

#684 tech debt: make cleanup
  Makefile
  hack/README.md
  hack/build/build-cdi-func-test-registry-host.sh
  hack/build/cleanup_docker.sh
Labels: release-note-none, size/L

#699 Resize on upload.
  cmd/cdi-uploadserver/uploadserver.go
  pkg/common/common.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/framework/pvc.go
  tests/upload_test.go
  tests/utils/upload.go
Labels: release-note, size/M

#706 Add type metadata to cdi-insecure registries ConfigMap
  pkg/operator/resources/namespaced/controller.go
Labels: release-note-none, size/XS

#714 bug fix: func test - registry buildah failure on outdated /etc/contai…
  hack/build/docker/cdi-func-test-registry-populate/populate-registry.sh
Labels: release-note-none, size/XS

#707 Fix wrong value being passed to validation.
  cmd/cdi-importer/importer.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
Labels: release-note-none, size/L

#711 update docs for https cert configuration
  doc/datavolumes.md
  manifests/example/cert-configmap.yaml
Labels: release-note-none, size/S

#708 Add documentation on how to create a local volume DV on a particular …
  doc/local-storage-selector.md
Labels: release-note-none, size/L

#710 add documentation on registry security
  doc/image-from-registry.md
Labels: release-note-none, size/M

#717 registry func test host fixes
  hack/build/docker/cdi-func-test-registry-populate/populate-registry.sh
  manifests/templates/registry-host.yaml.in
Labels: release-note-none, size/S

#718 Add a --version flag to cdi-apiserver
  cmd/cdi-apiserver/apiserver.go
  hack/build/build-go.sh
  hack/build/common.sh
  hack/build/version.sh
  pkg/version/base.go
  pkg/version/types.go
  pkg/version/verflag/verflag.go
  pkg/version/version.go
Labels: release-note, size/L

#700 Use CDIConfig for scratch storage class.
  cmd/cdi-controller/controller.go
  doc/cdi-config.md
  doc/scratch-space.md
  pkg/apis/core/v1alpha1/deepcopy_generated.go
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import_controller_ginkgo_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note, size/L

#713 dump logs when functional tests fail
  hack/build/docker/cdi-func-test-file-host-http/nginx.conf
  manifests/templates/cdi-operator.yaml.in
  manifests/templates/file-host.yaml.in
  manifests/templates/registry-host.yaml.in
  tests/framework/framework.go
Labels: release-note-none, size/M

#725 operator creates upload proxy route
  cmd/cdi-operator/operator.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/route.go
  pkg/operator/controller/scc.go
  pkg/operator/controller/util.go
Labels: release-note, size/L

#727 Allow missing storage class for scratch space, if none exists, create scratch PVC without SC
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note, size/M

#728 add missing apiVersion to upload doc
  doc/upload.md
Labels: release-note-none, size/XS

#729 Fix issue with the cdi config controller hanging in k8s
  pkg/controller/config-controller.go
  tests/cdiconfig_test.go
Labels: release-note-none, size/M

#630 Adding support to import disk image into a Block PV
  Makefile
  cluster/sync.sh
  cmd/cdi-importer/importer.go
  doc/import-block-pv.md
  hack/build/build-cdi-func-test-block-device.sh
  hack/build/config.sh
  hack/build/docker/cdi-func-test-block-device/Dockerfile
  hack/build/docker/cdi-func-test-block-device/entrypoint.sh
  manifests/example/import-archive-block-datavolume.yaml
  manifests/example/import-block-pv.yaml
  manifests/example/import-kubevirt-block-datavolume.yaml
  manifests/example/registry-image-block-datavolume.yaml
  manifests/templates/block-device.yaml.in
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/util.go
  pkg/util/util.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/framework/storageclass.go
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/datavolume.go
  tests/utils/pod.go
  tests/utils/pv.go
  tests/utils/pvc.go
  tests/utils/storageclass.go
Labels: release-note, size/XL

#724 update k8s image to 1.13.3 and enable ceph
  automation/check-patch.k8s-1.13.3-release.mounts
  automation/check-patch.k8s-1.13.3-release.packages
  automation/check-patch.k8s-1.13.3-release.sh
  automation/test.sh
  cluster/gocli.sh
  cluster/up.sh
  hack/README.md
  hack/build/config.sh
  stdci.yaml
Labels: release-note-none, size/S

#732 Fix target pod cleanup across namespaces
  pkg/controller/clone-controller.go
Labels: release-note, size/XS
