Repository kubevirt/containerized-data-importer, pull requests merged in 2019-01, with the labels that each got.

#586 fix typo in cdi-uploadproxy-ingress manifest
  manifests/templates/cdi-uploadproxy-ingress.yaml.in
Labels: release-note-none, size/XS

#592 Remove streaming data conversion 'unit tests'
  pkg/importer/dataStream_test.go
Labels: release-note-none, size/L

#591 make sure all generated client code actually gets deleted
  hack/update-codegen.sh
Labels: release-note-none, size/XS

#585 Internal Docker registry host that is visible only inside the cluster.
  Makefile
  cluster/sync.sh
  cluster/up.sh
  hack/README.md
  hack/build/build-cdi-func-test-registry-host.sh
  hack/build/config.sh
  hack/build/docker/cdi-func-test-registry-init/Dockerfile
  hack/build/docker/cdi-func-test-registry-populate/Dockerfile
  hack/build/docker/cdi-func-test-registry-populate/populate-registry.sh
  hack/build/docker/cdi-func-test-registry/Dockerfile
  hack/build/docker/cdi-func-test-registry/registry-config.yml
  hack/build/docker/cdi-func-test-registry/start-registry.sh
  manifests/templates/registry-host.yaml.in
  tools/cdi-func-test-registry-init/main.go
Labels: release-note-none, size/XL

#593 fix open quotes
  doc/exposing-upload-proxy.md
Labels: release-note-none, size/XS

#590 Increase skopeo unit test coverage.
  pkg/image/skopeo.go
  pkg/image/skopeo_test.go
  tests/images/invalid_manifest/manifest.json
  tests/images/valid_manifest/manifest.json
Labels: release-note-none, size/L

#588 Fix some functional test issues running locally.
  hack/build/run-tests.sh
  tests/api_validation_test.go
  tests/import_test.go
  tests/upload_test.go
Labels: release-note-none, size/M

#589 Adding DataVolume support for unpacking imported archive
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  manifests/example/import-archive-datavolume.yaml
  manifests/example/import-archive-pvc.yaml
  pkg/apis/datavolumecontroller/v1alpha1/openapi_generated.go
  pkg/apis/datavolumecontroller/v1alpha1/types.go
  pkg/apis/datavolumecontroller/v1alpha1/types_swagger_generated.go
  pkg/controller/datavolume-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
  pkg/importer/registry_test.go
  tests/import_test.go
  tests/local_volume_test.go
Labels: release-note, size/L

#597 Fix annotation in documentation
  doc/annotations.md
Labels: release-note-none, size/XS

#599 Update open shift image.
  hack/build/config.sh
Labels: release-note-none, size/XS

#601 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-note-none, size/L

#594 Integration test between DataVolume and import from registry
  cluster/sync.sh
  cluster/up.sh
  tests/datavolume_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/M

#583 Add test attributes
  tests/api_validation_test.go
  tests/basic_sanity_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/leaderelection_test.go
  tests/local_volume_test.go
  tests/upload_test.go
Labels: release-note-none, size/M

#602 Fixed junit report not getting generated.
  automation/test.sh
Labels: do-not-merge/hold, release-note-none, size/XS

#606 Updating hack/README.md with more 'make' targets and alphabetical reo…
  hack/README.md
Labels: release-note-none, size/M

#605 refactor data stream copy
  pkg/importer/dataStream.go
  pkg/importer/dataStream_test.go
Labels: release-note-none, size/L

#609 Make data volume status optional.
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
Labels: release-note-none, size/XS

#610 Make data volume status optional.
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
Labels: release-note-none, size/XS

#611 Make data volume status optional.
  pkg/apis/datavolumecontroller/v1alpha1/types.go
Labels: release-note-none, size/XS

#614 Alternative fix for broken Openshift functional test
  manifests/templates/file-host.yaml.in
  manifests/templates/registry-host.yaml.in
Labels: release-note-none, size/XS

#616 Remove minikube deployment from travis.
  .travis.yml
  pkg/apiserver/apiserver_test.go
  pkg/util/util_test.go
Labels: release-note-none, size/S

#618 fix apiserver unittests
  pkg/apiserver/apiserver_test.go
  pkg/operator/api.go
Labels: release-note-none, size/S

#619 The Operator CRD needs the operator.cdi.kubevirt.io label
  manifests/templates/cdi-operator.yaml.in
Labels: release-note-none, size/XS

#623 Enable api reference guide generation.
  .travis.yml
Labels: release-note, size/S

#625 Add validation of content type and unit tests.
  pkg/apiserver/webhooks/validating-webhook/validating-webhook.go
  pkg/apiserver/webhooks/validating-webhook/validating-webhook_test.go
  tests/api_validation_test.go
  tests/manifests/dv0SizePVC.yaml
  tests/manifests/dvBlankArchive.yaml
  tests/manifests/dvInvalidContentType.yaml
  tests/manifests/dvInvalidSourcePVC.yaml
  tests/manifests/dvInvalidURL.yaml
  tests/manifests/dvMissingPVCSpec.yaml
  tests/manifests/dvMissingResourceSpec.yaml
  tests/manifests/dvMissingSource.yaml
  tests/manifests/dvMultiSource.yaml
Labels: release-note, size/L

#622 Updated the released files to include operator and current binaries.
  .travis.yml
  hack/build/build-manifests.sh
Labels: release-note-none, size/M

#628 Update data volume documentation to include upload and blank image.
  doc/datavolumes.md
Labels: release-note-none, size/M
