Repository kubevirt/containerized-data-importer, pull requests merged in 2020-02, with the labels that each got.

#1094 Add help target in Makefile for developers
  Makefile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#1098 remove permission to get secrets at cluster scope
  pkg/controller/util.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/namespaced/controller.go
  tests/basic_sanity_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1096 upload.md minor fixes
  doc/upload.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1101 Remove references to extensions/v1beta1 in examples
  doc/basic_pv_pvc_dv.md
  doc/exposing-upload-proxy.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1099 Remove code that potentially let DV get into failed state with Restar…
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/transport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1102 Disable caching when converting qcow2 images
  pkg/image/qemu.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1103 operator create apiservice and webhook configurations
  Makefile
  cmd/cdi-apiserver/apiserver.go
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  go.mod
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/authorizer.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/util.go
  pkg/operator/resources/cert/factory.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/common.go
  tools/manifest-generator/manifest-generator.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1095 Add async endpoint for upload that closes connection immediately
  doc/upload.md
  pkg/common/common.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/upload-datasource.go
  pkg/importer/upload-datasource_test.go
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1112 Include csv-generator in upstream operator container.
  cmd/cdi-operator/BUILD.bazel
  go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1105 Add id to node to node test.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1107 operator needs to use uncached client in certain places
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1115 README: Provide a deep link to slack
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1109 Copy kubevirt.io annotations to scratch space pvc
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1118 Uninstall strategy and blocking webhook
  Makefile
  api/openapi-spec/swagger.json
  cluster-sync/clean.sh
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  go.mod
  pkg/apis/core/v1alpha1/deepcopy_generated.go
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/cdi-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/scheme.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/cruft.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/operator/operator.go
  tests/BUILD.bazel
  tests/operator_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1125 Increase test timeouts to account for slower CI
  go.mod
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/utils.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1127 add CDIConfig to swagger
  api/openapi-spec/swagger.json
  tools/openapi-spec-generator/definitions.go
  tools/openapi-spec-generator/openapi-spec-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1124 Add note in docs that scratch space requires RWO mode on the PVs in o…
  doc/scratch-space.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1128 Fix up the validation of sources logic to be easier to understand and…
  pkg/apiserver/webhooks/datavolume-validate.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
