Repository kubevirt/containerized-data-importer, pull requests merged in 2020-03, with the labels that each got.

#1085 Update upload controller to use runtime controller library
  cmd/cdi-controller/controller.go
  pkg/controller/BUILD.bazel
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1076 Added functional tests for ResourceRequirements feature.
  doc/quota.md
  tests/cloner_test.go
  tests/framework/framework.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1090 Update datavolume controller to use runtime controller library
  cmd/cdi-controller/controller.go
  pkg/controller/BUILD.bazel
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1132 Added missing cdiv1 scheme in import controller unit test.
  pkg/controller/import-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1131 skip CDI CR delete tests when expected name does not exist
  manifests/templates/release/cdi-cr.yaml.in
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1119 Move base images to fedora 31.
  WORKSPACE
  cmd/cdi-importer/BUILD.bazel
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/fedora.repo
  tests/datavolume_test.go
  tests/transport_test.go
  tools/cdi-func-test-registry-init/BUILD.bazel
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1133 Update comments on scratch space
  doc/scratch-space.md
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, release-note-none, size/S

#1136 Looks like gradle is no longer available in fedora 31, and the build …
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/entrypoint-bazel.sh
  hack/build/docker/builder/entrypoint.sh
  hack/gen-swagger-doc/gen-swagger-docs.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1137 Make sure the storage class annotations are not nil.
  tests/cdiconfig_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1140 Restore sparse images as the default (revert #970)
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1138 Avoid failing reconciliation on new CR
  pkg/operator/controller/controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1139 Use long timeout for uploadproxy client
  pkg/uploadproxy/uploadproxy.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1145 Enable IPv6 on cdi http file host.
  tools/cdi-func-test-file-host-init/nginx.conf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1042 Imageio - new import data source
  api/openapi-spec/swagger.json
  cluster-sync/sync.sh
  cmd/cdi-importer/importer.go
  go.mod
  go.sum
  manifests/templates/imageio.yaml.in
  pkg/apis/core/v1alpha1/deepcopy_generated.go
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/util.go
  pkg/importer/BUILD.bazel
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  tests/api_validation_test.go
  tests/datavolume_test.go
  tests/manifests/dvImageio.yaml
  tests/utils/datavolume.go
  vendor/github.com/ovirt/go-ovirt/BUILD.bazel
  vendor/github.com/ovirt/go-ovirt/README.md
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/github.com/ovirt/go-ovirt/error.go
  vendor/github.com/ovirt/go-ovirt/helper.go
  vendor/github.com/ovirt/go-ovirt/http.go
  vendor/github.com/ovirt/go-ovirt/reader.go
  vendor/github.com/ovirt/go-ovirt/readers.go
  vendor/github.com/ovirt/go-ovirt/service.go
  vendor/github.com/ovirt/go-ovirt/services.go
  vendor/github.com/ovirt/go-ovirt/type.go
  vendor/github.com/ovirt/go-ovirt/types.go
  vendor/github.com/ovirt/go-ovirt/utils.go
  vendor/github.com/ovirt/go-ovirt/version.go
  vendor/github.com/ovirt/go-ovirt/writer.go
  vendor/github.com/ovirt/go-ovirt/writers.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1146 operator permissions still not right
  pkg/operator/resources/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1134 Runtime lib smartclone controller
  cluster-sync/ephemeral_provider.sh
  cluster-sync/k8s-1.16.2/rook_ceph.yaml
  cluster-sync/k8s-1.17.0/provider.sh
  cluster-sync/k8s-1.17.0/rook_ceph.yaml
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller_test.go
  pkg/controller/config-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller_test.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
  pkg/controller/upload-controller_test.go
  tests/smartclone_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1153 Add source of imageio docker images
  manifests/templates/imageio.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1151 Add oVirt imageIO documentation
  cmd/cdi-importer/importer.go
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1154 Only have hostpath provisioner repeat test with scratch space.
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1158 Misc README updates
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1148 Set secondary GID of user on import and upload pods to be 107 (qemu) …
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/importer/BUILD.bazel
  tests/cloner_test.go
  tests/framework/exec_util.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1157 Don't annotate pvc/dvs with provisionOnNode as it causes a race with …
  tests/utils/common.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1160 Read timeout from environment variable instead of hard coding it.
  Makefile
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1159 Fix InsecureSkipVerify in imageio data source for http client. Use ht…
  BUILD.bazel
  manifests/templates/imageio.yaml.in
  pkg/importer/imageio-datasource.go
  tests/datavolume_test.go
  tests/utils/common.go
  tests/utils/configmaps.go
  tools/imageio-init/BUILD.bazel
  tools/imageio-init/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1156 CDI install synchronization
  go.mod
  go.sum
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  tests/BUILD.bazel
  tests/operator_test.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1143 Add ember csi lane
  BUILD.bazel
  WORKSPACE
  cluster-sync/ember/ember-csi-lvm.yaml
  cluster-sync/ember/loop_back.yaml
  cluster-sync/ember/snapshot-class.yaml
  cluster-sync/ephemeral_provider.sh
  cluster-sync/k8s-1.16.2/provider.sh
  cluster-sync/k8s-1.17.0/provider.sh
  hack/build/run-tests.sh
  tools/loop-back-lvm/BUILD.bazel
  tools/loop-back-lvm/create_lvm.sh
  tools/loop-back-lvm/entrypoint.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1161 Add missing test ids
  tests/api_validation_test.go
  tests/certrotation_test.go
  tests/datavolume_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1155 Add a field to DataVolume to track the number of retries/pod restarts
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/operator/resources/cluster/datavolume.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
