Repository kubevirt/containerized-data-importer, pull requests merged in 2020-08, with the labels that each got.

#1321 enable webhooks for alpha resources
  hack/build/build-functest.sh
  hack/build/build-manifests.sh
  hack/build/run-unit-tests.sh
  hack/update-codegen.sh
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/scheme.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  tests/BUILD.bazel
  tests/alpha_test.go
  tests/basic_sanity_test.go
  tests/framework/framework.go
  tests/manifests/dvAlphaMissingAccessModes.yaml
  tests/operator_test.go
  tests/transport_test.go
  vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1323 Avoid using unportable readlink -f, use pwd -P instead
  hack/build/bazel-build-builder.sh
  hack/build/bazel-docker.sh
  hack/build/build-cdi-func-test-file-host.sh
  hack/build/build-cdi-func-test-registry-host.sh
  hack/build/build-copy-artifacts.sh
  hack/build/build-functest.sh
  hack/build/build-go.sh
  hack/build/build-manifests.sh
  hack/build/common.sh
  hack/build/format.sh
  hack/build/in-docker.sh
  hack/build/resource-generator.sh
  hack/build/run-functional-tests.sh
  hack/update-codegen.sh
  hack/version/set-version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1318 Update external provider to allow for hpp and ceph storage.
  WORKSPACE
  cluster-sync/ephemeral_provider.sh
  cluster-sync/external/provider.sh
  cluster-sync/rook-ceph/scc.yaml
  hack/build/bazel-docker.sh
  hack/build/run-functional-tests.sh
  tests/basic_sanity_test.go
  tests/cdiconfig_test.go
  tests/cloner_test.go
  tests/import_test.go
  tests/tests_suite_test.go
  tests/upload_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1324 Update builder to v0.0.6 and include controller-gen install
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1332 update PATH for bazel builder image
  hack/build/config.sh
  hack/build/docker/builder/entrypoint-bazel.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1334 Fix how we determine base builder image.
  hack/build/bazel-build-builder.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1335 Update builder image to official latest
  hack/build/config.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1336 verify schema is synchronized using travis.
  hack/update-codegen.sh
  hack/verify-codegen.sh
  pkg/operator/resources/cluster/datavolume.go
  tools/schema-exporter/schema-exporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1326 Make it possible to import images needing conversion from servers that don't support range requests
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  tests/badserver_test.go
  tools/cdi-func-test-bad-webserver/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1339 Change +build ignore tag in tools.go to +build codegen
  tools.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1340 S3 source on DataVolume results in IMPORTER_SOURCE=http env variable …
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#1343 fix crd explain
  cluster-sync/sync.sh
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/cruft.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1325 Add functional tests to explain CDI CRDs.
  tests/BUILD.bazel
  tests/explain_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1182 Add events to operator
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr.go
  pkg/operator/controller/cruft.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
