Repository kubevirt/containerized-data-importer, pull requests merged in 2020-07, with the labels that each got.

#1259 Have transport tests re-use the verifier pod
  tests/framework/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1275 Remove outdated stdci.yaml file.
  stdci.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1262 Correct check in badserver_tests
  tests/badserver_test.go
  tools/cdi-func-test-bad-webserver/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1272 New test case "delete file during import"
  tests/datavolume_test.go
  tools/cdi-func-test-file-host-init/nginx.conf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1279 [test] Attempt to import from registry without the CA config map existing
  go.mod
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/utils/configmaps.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1281 [test] Import from registry using credentials - tier 1 test
  manifests/templates/registry-host.yaml.in
  tests/transport_test.go
  tools/cdi-func-test-registry-init/BUILD.bazel
  tools/cdi-func-test-registry-init/htpasswd
  tools/cdi-func-test-registry-init/populate-registry.sh
  tools/cdi-func-test-registry-init/registry-auth-config.yml
  tools/cdi-func-test-registry-init/start-registry.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1257 PVC deleted during import - tier1 test
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/utils/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1280 Remove k8s-1.16 cluster-sync logic
  Makefile
  cluster-sync/k8s-1.15/provider.sh
  cluster-sync/k8s-1.16/provider.sh
  cluster-up/hack/common.sh
  hack/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1288 Support form based uploads
  pkg/common/common.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1292 Update kubevirtci.
  cluster-sync/okd-4.1/provider.sh
  cluster-sync/okd-4.3/ceph_sc.yaml
  cluster-sync/okd-4.3/hpp-master-mc.yaml
  cluster-sync/okd-4.3/hpp-worker-mc.yaml
  cluster-sync/okd-4.3/provider.sh
  cluster-sync/okd-4.3/rook_ceph.yaml
  cluster-up/cluster/images.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/ocp-4.4/README.md
  cluster-up/cluster/ocp-4.4/provider.sh
  cluster-up/cluster/okd-4.1/README.md
  cluster-up/cluster/okd-4.1/provider.sh
  cluster-up/cluster/okd-4.2/README.md
  cluster-up/cluster/okd-4.2/provider.sh
  cluster-up/cluster/okd-4.3/README.md
  cluster-up/cluster/okd-4.3/provider.sh
  cluster-up/container.sh
  cluster-up/hack/common.sh
  cluster-up/ssh.sh
  hack/update-codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1300 Fix CDI apiserver authentication on AKS
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config.go
  pkg/apiserver/auth-config_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1296 Combine datavolume name tests into a single table.
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1283 Feature gates
  api/openapi-spec/swagger.json
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/config-controller.go
  pkg/feature-gates/BUILD.bazel
  pkg/feature-gates/feature-gates.go
  pkg/feature-gates/feature-gates_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1302 Non-functional change cleanup: remove unused calls to UploadPodName
  tests/cloner_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1304 build: Add btrfs-progs-devel and device-mapper-devel to builder image
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1242 WaitForFirstConsumer handling for DataVolumes
  doc/waitforfirstconsumer-storage-handling.md
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/feature-gates/BUILD.bazel
  pkg/feature-gates/feature-gates.go
  pkg/feature-gates/feature-gates_test.go
  tests/BUILD.bazel
  tests/badserver_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/leaderelection_test.go
  tests/operator_test.go
  tests/rbac_test.go
  tests/smartclone_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/common.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1297 Fix test kill container
  tests/cloner_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1310 Update cdi-builder to use go version 1.14.6 (current latest)
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
  hack/build/run-functional-tests.sh
  tests/alpha_test.go
  tests/api_validation_test.go
  tests/badserver_test.go
  tests/basic_sanity_test.go
  tests/cdiconfig_test.go
  tests/certrotation_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/import_test.go
  tests/leaderelection_test.go
  tests/local_volume_test.go
  tests/operator_test.go
  tests/rbac_test.go
  tests/smartclone_test.go
  tests/tests_suite_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1312 Remove potential failed state from DV
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1313 Update builder image to v0.0.5
  .travis.yml
  go.mod
  go.sum
  hack/build/config.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1237 Strip status from objects in operator reconcile loop
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/controller.go
  pkg/operator/controller/util.go
  pkg/operator/controller/util_test.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/utils/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
