Repository kubevirt/containerized-data-importer, pull requests merged in 2020-09, with the labels that each got.

#1348 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1351 Add nbdkit-devel to builder image
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1353 Update quota restore logic
  tests/cloner_test.go
  tests/import_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1363 Fix quota restore function by storing correct original value
  tests/cloner_test.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1362 Publish test binary on release
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1360 Sync with HCO definition of node placement values.
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/operator/resources/utils/common.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1367 Update qe-tools dependency to avoid a cryptic Go module issue.
  go.mod
  go.sum
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1356 Copy missing description for pod resource requirement.
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1357 Add ref_id and test_id for CDI placement API tests
  tests/import_test.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1372 Fix code schema to match what is generated by types.go
  pkg/operator/resources/cluster/datavolume.go
  pkg/operator/resources/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1359 Use semantic DeepEqual check on DV update
  hack/build/build-manifests.sh
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  tests/api_validation_test.go
  tests/manifests/templates/dv1024MiPVC.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1342 Prepare test image for OpenShift test lane.
  .travis.yml
  Makefile
  hack/build/osci-image-builder.sh
  hack/ci/Dockerfile.ci
  hack/ci/build-functest.sh
  hack/ci/build.sh
  hack/ci/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1383 Ensure we can specify different CDI CR name.
  Makefile
  automation/test.sh
  cluster-sync/clean.sh
  cluster-sync/sync.sh
  hack/build/config.sh
  hack/build/resource-generator.sh
  manifests/templates/release/cdi-cr.yaml.in
  pkg/controller/util.go
  pkg/controller/util_test.go
  tools/manifest-generator/manifest-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1384 [release-v1.23] Ensure we can specify different CDI CR name. (#1383)
  Makefile
  automation/test.sh
  cluster-sync/clean.sh
  cluster-sync/sync.sh
  hack/build/config.sh
  hack/build/resource-generator.sh
  manifests/templates/release/cdi-cr.yaml.in
  pkg/controller/util.go
  pkg/controller/util_test.go
  tools/manifest-generator/manifest-generator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1385 Skip the test if CDI CR is called something else
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1391 Only test upgrading from latest release to current if random_cr not set
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1392 Clone auth for serviceaccounts should include groups
  pkg/clone/auth.go
  pkg/controller/BUILD.bazel
  pkg/operator/resources/cluster/rbac.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1389 Updated controller-lifecycle-operator-sdk dependency
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1beta1/BUILD.bazel
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/cdi-validate_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/controller/cruft.go
  pkg/operator/controller/scc.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/factory.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/operator/BUILD.bazel
  pkg/operator/resources/operator/factory.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/BUILD.bazel
  pkg/operator/resources/utils/common.go
  tests/BUILD.bazel
  tests/operator_test.go
  tests/utils.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/callbacks/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/callbacks/callback-dispatcher.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/cr-status.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/predicate.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/builder.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/versions.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/openapi/BUILD.bazel
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/openapi/status.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/rbac.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/resources.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/util.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1390 Fixing dependency on Operator Framework.
  go.mod
  go.sum
  pkg/operator/resources/operator/BUILD.bazel
  pkg/operator/resources/operator/operator.go
  tests/BUILD.bazel
  tests/cdiconfig_test.go
  vendor/github.com/coreos/go-semver/LICENSE
  vendor/github.com/coreos/go-semver/NOTICE
  vendor/github.com/coreos/go-semver/semver/BUILD.bazel
  vendor/github.com/coreos/go-semver/semver/semver.go
  vendor/github.com/coreos/go-semver/semver/sort.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/BUILD.bazel
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/operatorgroup_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/BUILD.bazel
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/catalogsource_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/clusterserviceversion_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/doc.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/installplan_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/register.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/subscription_types.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.conversion.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/zz_generated.deepcopy.go
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/version/BUILD.bazel
  vendor/github.com/operator-framework/operator-lifecycle-manager/pkg/lib/version/version.go
  vendor/golang.org/x/lint/go.mod
  vendor/golang.org/x/lint/go.sum
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1396 Change clone authorization api to allow any k8s client version
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/handler.go
  pkg/clone/BUILD.bazel
  pkg/clone/auth.go
  tests/BUILD.bazel
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1387 Add functional test for cloning if source NS has enought quota and
  pkg/controller/BUILD.bazel
  tests/cloner_test.go
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1395 Fix incorrect region parsing from aws s3 endpoint
  pkg/importer/s3-datasource.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#1398 Add test_ids for the test cases
  tests/alpha_test.go
  tests/cdiconfig_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/explain_test.go
  tests/import_test.go
  tests/operator_test.go
  tests/smartclone_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1386 Remove dependency update when building the OR CI build image
  hack/ci/Dockerfile.ci
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1400 Add library function to determine if a PVC has been populated fully.
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/utils.go
  pkg/apis/core/v1beta1/BUILD.bazel
  pkg/apis/core/v1beta1/utils.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/util.go
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1402 Removed hard coded registry:5000 for vddk datasource test.
  manifests/templates/vcenter.yaml.in
  pkg/importer/vddk-datasource.go
  tests/datavolume_test.go
  tests/utils/configmaps.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1404 Test behavior after client-side upload failure.
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
