Repository kubevirt/containerized-data-importer, pull requests merged in 2020-01, with the labels that each got.

#1065 Fix `GetAvailableSpaceBlock` always return -1 in LXC
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1071 Update design doc
  doc/design.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1070 Smartclone tests: refer to Polarion IDs
  tests/smartclone_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1055 Fix to create temporary pod with default resource quota
  cmd/cdi-controller/controller.go
  go.mod
  pkg/apis/core/v1alpha1/deepcopy_generated.go
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#1063 modify default k8s version in cluster-up
  cluster-up/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1082 update builder to k8s 1.16.4 and use tags for builder image
  hack/build/bazel-build-builder.sh
  hack/build/bazel-docker.sh
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
  hack/build/in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1077 Print additional information with kubectl get dv
  go.mod
  pkg/operator/resources/cluster/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1080 Don't run raw images through qemu-img as it sometimes has issues tran…
  pkg/importer/http-datasource.go
  tests/leaderelection_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1086 Allow multiple previous versions to upgrade from
  automation/test.sh
  cluster-sync/install.sh
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1089 Reverse the check for multi upgrade.
  automation/test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1093 Add NFS as KUBEVIRT_STORAGE to cluster-sync
  cluster-sync/ephemeral_provider.sh
  cluster-sync/k8s-1.16.2/provider.sh
  cluster-sync/nfs/nfs-sc.yaml
  cluster-sync/nfs/nfs-server.yaml
  cluster-sync/nfs/nfs-service.yaml
  cluster-sync/sync.sh
  go.mod
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/framework/nfs-utils.go
  tests/utils/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L
