Repository kubevirt/containerized-data-importer, pull requests merged in 2020-11, with the labels that each got.

#1448 VDDK: replace qemu-img with libnbd
  WORKSPACE
  cmd/cdi-importer/BUILD.bazel
  cmd/cdi-uploadserver/BUILD.bazel
  go.mod
  go.sum
  hack/build/bazel-build-images.sh
  hack/build/bazel-build.sh
  hack/build/bazel-generate.sh
  hack/build/bazel-push-images.sh
  hack/build/config.sh
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/image/qemu.go
  pkg/importer/BUILD.bazel
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  vendor/github.com/mrnold/go-libnbd/BUILD.bazel
  vendor/github.com/mrnold/go-libnbd/aio_buffer.go
  vendor/github.com/mrnold/go-libnbd/bindings.go
  vendor/github.com/mrnold/go-libnbd/callbacks.go
  vendor/github.com/mrnold/go-libnbd/closures.go
  vendor/github.com/mrnold/go-libnbd/handle.go
  vendor/github.com/mrnold/go-libnbd/wrappers.go
  vendor/github.com/mrnold/go-libnbd/wrappers.h
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XXL

#1463 Test framework dump service
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1424 Scratch import bug
  cluster-sync/nfs/nfs-server.yaml
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/util.go
  tests/datavolume_test.go
  tests/framework/nfs-utils.go
  tests/utils/datavolume.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1446 Remove the "Process" data processor phase, simplify state machine.
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/registry-datasource.go
  pkg/importer/registry-datasource_test.go
  pkg/importer/s3-datasource.go
  pkg/importer/s3-datasource_test.go
  pkg/importer/upload-datasource.go
  pkg/importer/upload-datasource_test.go
  pkg/importer/vddk-datasource.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1459 Fix flaky operator test
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1475 Add CDIConfig to CDI
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/resources/operator/operator.go
  tests/cdiconfig_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/import_test.go
  tests/rbac_test.go
  tests/upload_test.go
  tests/utils/BUILD.bazel
  tests/utils/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1481 k8s-reporter: Add Endpoints logging
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1465 VDDK: Add more debug logging around nbdkit.
  pkg/importer/vddk-datasource.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#1485 apiserver should serve up openapi spec
  api/openapi-spec/swagger.json
  pkg/apis/upload/v1beta1/openapi_generated.go
  pkg/apis/upload/v1beta1/types.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/util/openapi/BUILD.bazel
  pkg/util/openapi/openapi.go
  tests/BUILD.bazel
  tests/apiserver_test.go
  tests/utils/BUILD.bazel
  tools/openapi-spec-generator/BUILD.bazel
  tools/openapi-spec-generator/openapi-spec-generator.go
  tools/openapi-spec-generator/openapi.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1478 Pull less from dockerhub when running testsuite
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/smartclone_test.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1450 Controller support for Multistage Imports
  api/openapi-spec/swagger.json
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/util.go
  pkg/operator/resources/cluster/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1499 Make sure the DV is the main resource and single source of truth for …
  pkg/apis/core/v1alpha1/utils.go
  pkg/apis/core/v1beta1/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1484 fix KUBEVIRT_STORAGE=nfs make cluster-sync
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1480 Pass specific PVC annotations to the transfer pods
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  tests/datavolume_test.go
  tests/utils/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
