Repository kubevirt/containerized-data-importer, pull requests merged in 2020-06, with the labels that each got.

#1211 Enable the use of podman
  go.mod
  hack/build/bazel-docker.sh
  hack/build/build-manifests.sh
  hack/build/config.sh
  hack/build/docker/builder/entrypoint.sh
  hack/build/in-docker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1218 ember csi with beta snapshot api
  cluster-sync/ember/ember-csi-lvm.yaml
  cluster-sync/ember/snapshot-class.yaml
  cluster-sync/ephemeral_provider.sh
  cluster-sync/k8s-1.16/provider.sh
  cluster-sync/rook-ceph/operator.yaml
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1215 Fix cloner across tests failing on ceph lane
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1222 use kubernetes openapi generator
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/upload/v1alpha1/BUILD.bazel
  pkg/apis/upload/v1alpha1/openapi_generated.go
  pkg/apis/upload/v1alpha1/types.go
  pkg/apis/upload/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  tools/openapi-spec-generator/BUILD.bazel
  tools/openapi-spec-generator/definitions.go
  tools/openapi-spec-generator/openapi.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/BUILD.bazel
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/k8s.io/kube-openapi/pkg/builder/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/builder/doc.go
  vendor/k8s.io/kube-openapi/pkg/builder/openapi.go
  vendor/k8s.io/kube-openapi/pkg/builder/util.go
  vendor/k8s.io/kube-openapi/pkg/util/BUILD.bazel
  vendor/k8s.io/kube-openapi/pkg/util/trie.go
  vendor/k8s.io/kube-openapi/pkg/util/util.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1223 Added missing diff to builder image
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1220 Update `make help` documentation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1221 Update builder image to allow podman to work.
  go.mod
  hack/build/config.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1225 Update regex that matches version to accept +hash in version string
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1228 Call finalize in close for imageio source
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1233 Allow tokens for PVCs that do not exist.
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1230 Add missing content types to clone source flag
  cmd/cdi-cloner/clone-source.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1238 Allow tokens for PVCs that do not exist. (#1233)
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1231 Change permissions to always be 660 for the disk image.
  pkg/image/qemu.go
  pkg/importer/data-processor.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1243 [release-v1.13] Don't annotate pvc/dvs with provisionOnNode
  tests/utils/common.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
Labels: dco-signoff: yes, lgtm, release-note-none, size/M

#1245 Report better qemu failure messages.
  pkg/apiserver/BUILD.bazel
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/system/prlimit.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1250 Fix tests compile.
  tests/utils/common.go
Labels: dco-signoff: yes, release-note-none

#1247 Add new dv phase WaitForFirstConsumer
  pkg/apis/core/v1alpha1/types.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1256 Add test-ids for new tests
  tests/cdiconfig_test.go
  tests/datavolume_test.go
  tests/operator_test.go
  tests/rbac_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1252 Update kubevirtci and add k8s-1.18 lane
  cluster-sync/k8s-1.18/provider.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.18/README.md
  cluster-up/cluster/k8s-1.18/dev-guide.md
  cluster-up/cluster/k8s-1.18/provider.sh
  cluster-up/cluster/kind-k8s-1.14.2/README.md
  cluster-up/cluster/kind-k8s-1.14.2/provider.sh
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind/README.md
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kube-calico.yaml
  hack/update-codegen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1255 Block clone across namespace, delete populator/verifier pod
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1253 Return stderr from verifier pods
  tests/framework/exec_util.go
  tests/framework/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1261 [flaky test] verifier pods hanging around keeps cloning from working
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1226 Report the failure count and environmental setup of failure counts
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1269 [flaky test] datavolume should not say upload is ready until pod is running
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1258 Use blockdev instead of lsblk for getting block device size
  cmd/cdi-cloner/cloner_startup.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XS

#1260 use go package to properly handle CORS requests
  go.mod
  go.sum
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
  tests/upload_test.go
  vendor/github.com/rs/cors/.travis.yml
  vendor/github.com/rs/cors/BUILD.bazel
  vendor/github.com/rs/cors/LICENSE
  vendor/github.com/rs/cors/README.md
  vendor/github.com/rs/cors/cors.go
  vendor/github.com/rs/cors/go.mod
  vendor/github.com/rs/cors/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1271 Fix PodResourceRequirements
  doc/quota.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1254 Don't mark DV succeeded during scratch space pod delete/create
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1263 Wait for PVCs to be unused before initiating clone operations
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/smartclone_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1273 [release-v1.18] cherry-pick 1269 1263
  go.sum
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/smartclone_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL
