Repository kubevirt/containerized-data-importer, pull requests merged in 2020-10, with the labels that each got.

#1319 Reserve overhead when validating that a Filesystem has enough space
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/uploadserver.go
  doc/cdi-config.md
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/common/common.go
  pkg/controller/config-controller.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/operator/resources/cluster/cdiconfig.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/BUILD.bazel
  tests/cdiconfig_test.go
  tests/framework/nfs-utils.go
  tests/upload_test.go
  tests/utils/pv.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#1412 Fixing CDIStatus generate-verify issues
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/operator/resources/operator/operator.go
  tests/explain_test.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/builder.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/openapi/status.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1415 add system:authenticated to groups checked for clone auth
  pkg/clone/auth.go
  tests/webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1419 use snappy compression for cloning instead of gzip
  cmd/cdi-cloner/BUILD.bazel
  cmd/cdi-cloner/clone-source.go
  go.mod
  go.sum
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  tests/cloner_test.go
  vendor/github.com/golang/snappy/.gitignore
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/BUILD.bazel
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/LICENSE
  vendor/github.com/golang/snappy/README
  vendor/github.com/golang/snappy/decode.go
  vendor/github.com/golang/snappy/decode_amd64.s
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode.go
  vendor/github.com/golang/snappy/encode_amd64.s
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/github.com/golang/snappy/go.mod
  vendor/github.com/golang/snappy/snappy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1421 Fix size mismatch between source and target in smart clone tests.
  doc/smart-clone.md
  tests/smartclone_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1422 [release-v1.23] use snappy compression for cloning instead of gzip
  cmd/cdi-cloner/BUILD.bazel
  cmd/cdi-cloner/clone-source.go
  go.mod
  go.sum
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  tests/cloner_test.go
  vendor/github.com/golang/snappy/.gitignore
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/BUILD.bazel
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/LICENSE
  vendor/github.com/golang/snappy/README
  vendor/github.com/golang/snappy/decode.go
  vendor/github.com/golang/snappy/decode_amd64.s
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode.go
  vendor/github.com/golang/snappy/encode_amd64.s
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/github.com/golang/snappy/go.mod
  vendor/github.com/golang/snappy/snappy.go
  vendor/github.com/pquerna/ffjson/fflib/v1/jsonstring.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1413 Fix imports for images with no info about MediaType.
  pkg/image/BUILD.bazel
  pkg/importer/BUILD.bazel
  pkg/importer/registry-datasource.go
  pkg/importer/transport.go
  pkg/importer/transport_test.go
  tools/cdi-func-test-file-host-init/nginx.conf
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1427 Touch ups for filesystem overhead test cases
  tests/cdiconfig_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1426 Attempt to schedule clone source/target pods on same node
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1432 Files in tar archives can have paths relative to ./
  pkg/importer/transport.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1436 [release-v1.18] backport "replace gzip with snappy" for network clone and #1426
  automation/test.sh
  cmd/cdi-cloner/BUILD.bazel
  cmd/cdi-cloner/clone-source.go
  go.mod
  go.sum
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  tests/cloner_test.go
  vendor/github.com/golang/snappy/.gitignore
  vendor/github.com/golang/snappy/AUTHORS
  vendor/github.com/golang/snappy/BUILD.bazel
  vendor/github.com/golang/snappy/CONTRIBUTORS
  vendor/github.com/golang/snappy/LICENSE
  vendor/github.com/golang/snappy/README
  vendor/github.com/golang/snappy/decode.go
  vendor/github.com/golang/snappy/decode_amd64.s
  vendor/github.com/golang/snappy/decode_arm64.s
  vendor/github.com/golang/snappy/decode_asm.go
  vendor/github.com/golang/snappy/decode_other.go
  vendor/github.com/golang/snappy/encode.go
  vendor/github.com/golang/snappy/encode_amd64.s
  vendor/github.com/golang/snappy/encode_arm64.s
  vendor/github.com/golang/snappy/encode_asm.go
  vendor/github.com/golang/snappy/encode_other.go
  vendor/github.com/golang/snappy/go.mod
  vendor/github.com/golang/snappy/snappy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1417 Check for expected changes after CDI upgrade
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1437 Retry upload in case upload pod wasn't 100% ready when attempting upload
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1416 Add files used in OpenShift CI.
  Makefile
  cluster-sync/sync-os-ci.sh
  hack/ci/Dockerfile.ci
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1428 Fix types.go vs code schema verification to actually fail if they are different
  hack/verify-codegen.sh
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/resources/cluster/cdiconfig.go
  tests/cdiconfig_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1435 Fix cloning checking fsGroup test in case of use with OCS.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1361 Make CDI infra deployments as critical addons.
  cluster-sync/nfs/nfs-server.yaml
  manifests/templates/release/cdi-cr.yaml.in
  pkg/operator/resources/utils/common.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1429 add finalizer to target PVC before creating clone source pod
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1440 Retry upload in case upload pod wasn't 100% ready when attempting upload
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1441 Add test_ids for the tests
  tests/badserver_test.go
  tests/basic_sanity_test.go
  tests/datavolume_test.go
  tests/transport_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1447 [release-v1.23] Retry upload in case upload pod wasn't 100% ready when attempting upload (#1437)
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1442 Add library function to determine if a PVC is waiting for first consu…
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/utils.go
  pkg/apis/core/v1alpha1/utils_test.go
  pkg/apis/core/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/core/v1beta1/BUILD.bazel
  pkg/apis/core/v1beta1/utils.go
  pkg/apis/core/v1beta1/utils_test.go
  pkg/apis/core/v1beta1/v1beta1_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1451 Add make targets cluster-sync-cdi & cluster-sync-test-infra
  Makefile
  cluster-sync/sync.sh
  hack/build/cluster-sync-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1452 Update builder image to add libnbd
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1439 Don't wait for NS to deleted in test before starting next test
  tests/cloner_test.go
  tests/framework/framework.go
  tests/framework/nfs-utils.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/tests_suite_test.go
  tests/utils/common.go
  tests/utils/pod.go
  tests/utils/pv.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1444 Update WORKSPACE packages to non-404 ones, and add a second mirror.
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
