Repository kubevirt/containerized-data-importer, pull requests merged in 2020-04, with the labels that each got.

#1164 cherry-pick #1156 to release-1.13
  go.sum
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  tests/BUILD.bazel
  tests/operator_test.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1165 Change how we wait for CDI to be ready for OS-3.11.0-crio provider.
  cluster-sync/sync.sh
  go.mod
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1163 Clean up client-go left overs after converting to runtime library.
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  go.mod
  go.sum
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/runtime-util.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/BUILD.bazel
  pkg/operator/api.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1166 Increase time we wait for operator upgrade to complete.
  automation/test.sh
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1162 ux: Clarify message when PVC is too small
  pkg/image/qemu.go
  pkg/image/qemu_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1167 Fix os-3.11.0-crio comparison so it follow the right path on other provider.
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1129 Remove error log from ExecWithLimits, let the caller handle this
  pkg/system/prlimit.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1169 Fix should clone across multiple nodes on NFS lane.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1122 Eliminate the need for HEAD requests in the Go HTTP download client.
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1176 Attempt to unstick the os-3.11-crio provider when an sdn pod is not r…
  cluster-sync/os-3.11.0-crio/provider.sh
  cluster-sync/sync.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1168 Convert remaining tests to ginkgo
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver_suite_test.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/authorizer_test.go
  pkg/image/filefmt_test.go
  pkg/keys/keystore_test.go
  pkg/operator/resources/operator/BUILD.bazel
  pkg/operator/resources/operator/operator_suite_test.go
  pkg/operator/resources/operator/operator_test.go
  pkg/token/BUILD.bazel
  pkg/token/token_test.go
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy_suite_test.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/BUILD.bazel
  pkg/uploadserver/uploadserver_suite_test.go
  pkg/uploadserver/uploadserver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1170 Create prometheus service in cdi namespace.
  pkg/common/common.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/utils/common.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1174 use dedicated SCC
  go.mod
  go.sum
  pkg/common/common.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cruft.go
  pkg/operator/controller/scc.go
  pkg/operator/controller/util.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/common.go
  tests/operator_test.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1171 Make sure all CDI crds have structural schemas
  cluster-sync/sync.sh
  pkg/operator/resources/cluster/cdiconfig.go
  pkg/operator/resources/cluster/datavolume.go
  pkg/operator/resources/operator/operator.go
  tests/BUILD.bazel
  tests/api_validation_test.go
  tests/basic_sanity_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1177 Cherrypick #1174
  pkg/common/common.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cruft.go
  pkg/operator/controller/scc.go
  pkg/operator/controller/util.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/common.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1180 Fix builder build image.
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1179 Fail to import a containerDisk containing more than one file
  pkg/importer/registry-datasource.go
  pkg/importer/registry-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1183 Allow for "pre initialized" DataVolumes.
  go.mod
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/util.go
  pkg/operator/controller/BUILD.bazel
  tests/datavolume_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/BUILD.bazel
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/BUILD.bazel
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1185 Wait for CDI config to be available if not found during functional tests
  go.mod
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1184 Minor fix to a manifest example, import-kubevirt-block-datavolume
  manifests/example/import-kubevirt-block-datavolume.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1188 Fix, crash when total size is 0 from endpoint. If total was 0 no prog…
  pkg/importer/format-readers.go
  pkg/importer/format-readers_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1186 Add DV restarts test for upload controller
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/exec_util.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1192 Fixed race for block blank disks
  pkg/controller/datavolume-controller.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
