Repository kubevirt/containerized-data-importer, pull requests merged in 2021-06, with the labels that each got.

#1813 Fix Secret URL
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1819 Fix leader election test that is failing.
  tests/leaderelection_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1779 Import registry disk into PVC barely big enough
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1826 Switch deprecated extensions/v1beta1 Ingress
  doc/exposing-upload-proxy.md
  pkg/controller/BUILD.bazel
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/operator/resources/cluster/controller.go
  tests/BUILD.bazel
  tests/cdiconfig_test.go
  tests/manifests/ingressNetworkApigroup.yaml
  tests/manifests/ingressNoHttp.yaml
  tests/utils/common.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1827 update builder image
  hack/build/config.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1828 Move nfs-server images to quay.io
  cluster-sync/nfs/nfs-server.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1822 Add Importer functional tests for Istio sidecar injection annotation
  tests/BUILD.bazel
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/import_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1831 Reduce the amount of noise from the filesystem overhead feature
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1823 Bump deprecated authorization/v1beta1
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/authorizer.go
  pkg/apiserver/authorizer_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1814 Use gibi for cloning tests.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1833 update fedora sha
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1808 OS image poll and update API
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/utils/utils_test.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/client/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/dataimportcron.go
  pkg/client/clientset/versioned/typed/core/v1beta1/datasource.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_dataimportcron.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_datasource.go
  pkg/client/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/informers/externalversions/core/v1beta1/BUILD.bazel
  pkg/client/informers/externalversions/core/v1beta1/dataimportcron.go
  pkg/client/informers/externalversions/core/v1beta1/datasource.go
  pkg/client/informers/externalversions/core/v1beta1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1beta1/BUILD.bazel
  pkg/client/listers/core/v1beta1/dataimportcron.go
  pkg/client/listers/core/v1beta1/datasource.go
  pkg/client/listers/core/v1beta1/expansion_generated.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/util_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/datasource.go
  pkg/operator/resources/cluster/datavolume.go
  pkg/operator/resources/cluster/factory.go
  tests/api_validation_test.go
  tests/utils/datavolume.go
  tools/schema-exporter/schema-exporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1820 Adding support to specify externally managed certs
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  cmd/cdi-uploadproxy/BUILD.bazel
  cmd/cdi-uploadproxy/uploadproxy.go
  pkg/util/cert/fetcher/certfetcher.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#1837 URL-encode special characters in VDDK credentials.
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1840 Remove the test - delete scratch space
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1816 Add "AwaitingVDDK" back to condition reason.
  pkg/common/common.go
  pkg/controller/datavolume-conditions.go
  pkg/controller/datavolume-conditions_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1844 Fix smartclone sometimes not triggering due to capicity not being reported.
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/alpha_test.go
  tests/framework/pvc.go
  tests/smartclone_test.go
  tests/transport_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1841 Add DataVolume annotation to retain the transfer pods after completion
  doc/datavolumes.md
  doc/debug.md
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pod.go
  tests/import_test.go
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1842 Set some reasonable requests/limits for workloads
  pkg/controller/clone-controller_test.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1818 Add a datavolume condition for the image being too large
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/nbdkit.go
  pkg/image/qemu.go
  pkg/util/util.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
