Repository kubevirt/containerized-data-importer, pull requests merged in 2021-02, with the labels that each got.

#1627 Update DV status to indicate when VDDK configmap is missing.
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/M

#1597 Support cloning from Filesystem to Block and vice-versa
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/feature-gates/BUILD.bazel
  pkg/uploadserver/uploadserver.go
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1621 text corrections and readability improvements
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1624 Remove OLM integration code not removed in #982
  tools/marketplace/BUILD.bazel
  tools/marketplace/helper/BUILD.bazel
  tools/marketplace/helper/bundle-helper.go
  tools/marketplace/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1631 Remove documentation note about VDDK 7 restriction.
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1630 Increase polling speed for upload annotation test
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1602 Simplify shouldReconcile function arguments.
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1632 rename importController to uploadController in the upload-controller.go file
  pkg/controller/upload-controller.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1639 VDDK: avoid crash when specified disk isn't in VM.
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1626 Add diagnostic to flaky test
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1625 Preallocation test did not run all scenarios
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1620 Fix flaky test: failure when checking permissions
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1645 Push builder to quay.io as well
  hack/build/bazel-build-builder.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1644 Fix inverted logic - wait for the pod to stop existing.
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1646 Update cross volume mode DV clone doc
  doc/clone-block-datavolume.md
  doc/clone-datavolume.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1637 Preallocate even if the size is too small
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/uploadserver.go
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1650 doc: update scratch-space
  doc/scratch-space.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1651 [release-v1.28] Preallocate even if the size is too small
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/uploadserver.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  pkg/util/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1653 Fix a few more remaining references to docker.
  hack/build/osci-image-builder.sh
  hack/build/release-description.sh
  hack/ci/Dockerfile.ci
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1655 Fix travis nightly to push from main.
  .travis.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1647 Flaky cert test fix
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1652 Revert skipping test 2555 on OpenShift.
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1658 Implement certConfigMap for s3 datasources, reported missing on #1506
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/controller/datavolume-controller.go
  pkg/importer/s3-datasource.go
  pkg/importer/s3-datasource_test.go
  pkg/operator/resources/cluster/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/L

#1657 Set default DOCKER_PREFIX to quay.io
  hack/build/bazel-build-builder.sh
  hack/build/config.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1665 Fixed typo in annotation name
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1659 Fix default content type validation for cloning
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1629 Pvc profiles api
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_storageprofile.go
  pkg/client/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/core/v1beta1/storageprofile.go
  pkg/client/informers/externalversions/core/v1beta1/BUILD.bazel
  pkg/client/informers/externalversions/core/v1beta1/interface.go
  pkg/client/informers/externalversions/core/v1beta1/storageprofile.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1beta1/BUILD.bazel
  pkg/client/listers/core/v1beta1/expansion_generated.go
  pkg/client/listers/core/v1beta1/storageprofile.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/storageprofile.go
  tools/schema-exporter/schema-exporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1661 Have the healthz server check for the uploadserver first.
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1670 VDDK/ImageIO cleanup after importer termination.
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1668 Check for DV success before we verify the contents is right.
  tests/smartclone_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1667 Add missing fields to v1alpha1 resources
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/resources/cluster/cdiconfig.go
  pkg/operator/resources/cluster/datavolume.go
  pkg/operator/resources/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1674 Allow passing default annotation value to transfer pods
  pkg/controller/clone-controller_test.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1673 Cluster scoped DataVolume/PVC namespace transfer API
  cluster-sync/clean.sh
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  hack/verify-codegen.sh
  pkg/apis/core/v1beta1/BUILD.bazel
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/register.go
  pkg/apis/core/v1beta1/types_transfer.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/transfer-validate.go
  pkg/apiserver/webhooks/transfer-validate_test.go
  pkg/client/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_objecttransfer.go
  pkg/client/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/core/v1beta1/objecttransfer.go
  pkg/client/informers/externalversions/core/v1beta1/BUILD.bazel
  pkg/client/informers/externalversions/core/v1beta1/interface.go
  pkg/client/informers/externalversions/core/v1beta1/objecttransfer.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1beta1/BUILD.bazel
  pkg/client/listers/core/v1beta1/expansion_generated.go
  pkg/client/listers/core/v1beta1/objecttransfer.go
  pkg/controller/clone-controller.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/transfer/BUILD.bazel
  pkg/controller/transfer/controller.go
  pkg/controller/transfer/controller_suite_test.go
  pkg/controller/transfer/controller_test.go
  pkg/controller/transfer/dv.go
  pkg/controller/transfer/dv_test.go
  pkg/controller/transfer/pvc.go
  pkg/controller/transfer/pvc_test.go
  pkg/controller/transfer/watch.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/object-transfer.go
  tests/BUILD.bazel
  tests/framework/pvc.go
  tests/manifests/out/dv1024MiPVC.yaml
  tests/manifests/out/templates/dv1024MiPVC.yaml.j2
  tests/transfer_test.go
  tools/schema-exporter/schema-exporter.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1675 Setup a default KUBEVIRT_PROVIDER for make functional-test
  hack/build/run-functional-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
