Repository kubevirt/containerized-data-importer, pull requests merged in 2021-03, with the labels that each got.

#1679 Adding Gosec builder docker image
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1681 Improved instructions about creating a new release.
  doc/releases.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1654 Test filesystem overhead on blank images
  tests/framework/pvc.go
  tests/import_test.go
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1691 Backport of PR #1686 Remove unit tests that are causing issues and arent' useful
  go.mod
  go.sum
  pkg/operator/resources/operator/BUILD.bazel
  pkg/operator/resources/operator/operator_suite_test.go
  pkg/operator/resources/operator/operator_test.go
  vendor/github.com/RHsyseng/operator-utils/LICENSE
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/BUILD.bazel
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_sync.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1693 Documentation update - describe cdi.kubevirt.io/storage.bind.immediat…
  doc/datavolumes.md
  doc/waitforfirstconsumer-storage-handling.md
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#1676 Adding support for gosec scan on CDI repo
  Makefile
  hack/build/config.sh
  hack/build/gosec.sh
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#1692 Update release description template (Docker Hub -> Quay.io)
  hack/build/release-description.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1680 Nbdkit refactor to unify usage for vddk and http importers
  pkg/image/BUILD.bazel
  pkg/image/nbdkit.go
  pkg/image/nbdkit_test.go
  pkg/image/qemu.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#1664 [release-v1.28] Preallocate blank block volumes (#1559)
  cmd/cdi-importer/importer.go
  pkg/controller/import-controller.go
  pkg/image/qemu.go
  pkg/importer/data-processor.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1595 [release-v1.28] Preallocation global setting for 1.28
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/config-controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1694 Deduplicate resource definition code
  pkg/operator/resources/cluster/cdiconfig.go
  pkg/operator/resources/cluster/datavolume.go
  pkg/operator/resources/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1697 Use quay.io for imageio test image
  manifests/templates/imageio.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1688 [release-v1.28] VDDK/ImageIO cleanup after importer termination.
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1703 update to kubevirtci with builtin rook/ceph
  cluster-sync/external/resources/machineconfig-worker.yaml
  cluster-sync/k8s-1.17/provider.sh
  cluster-sync/k8s-1.18/provider.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.17/dev-guide.md
  cluster-up/cluster/k8s-1.18/dev-guide.md
  cluster-up/cluster/k8s-1.19/dev-guide.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1705 Add scripts to do releases with PROW
  automation/git-askpass.sh
  automation/release.sh
  hack/gen-swagger-doc/deploy.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1704 Replace dockerhub references with quay.io
  manifests/templates/file-host.yaml.in
  manifests/templates/imageio.yaml.in
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1706 Increasing timeout for controller plane
  hack/build/run-unit-tests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1701 Separate nbdkit plugin arguments.
  pkg/image/nbdkit.go
  tools/vddk-test/vddk-test-plugin.c
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1663 Try different modes of preallocation
  pkg/image/nbdkit.go
  pkg/image/qemu.go
  pkg/importer/data-processor.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1699 Correct the behaviour of scratch space SC tests if env uses this tunable
  tests/cdiconfig_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1709 update kubevirci to fix rook/ceph with multiple nodes
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1717 update kubevirtci again to fix rook/ceph on single node
  cluster-up/cluster/kind-k8s-sriov-1.17.0/README.md
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1718 Move the cdi core containers out of push bundle to limit the push rate.
  BUILD.bazel
  hack/build/bazel-push-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1712 [release-v1.28] Try different modes of preallocation (#1663)
  pkg/image/qemu.go
  pkg/importer/data-processor.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1720 Set tag properly when doing releases in PROW
  hack/build/bazel-push-images.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1714 Refactored addPreallocation.
  pkg/image/qemu.go
  pkg/image/qemu_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1721 Add `bazel clean --expunge` to the clean make target
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
