Repository kubevirt/containerized-data-importer, pull requests merged in 2021-05, with the labels that each got.

#1768 Fix cluster proxy part of proxy test
  tests/import_proxy_test.go
  tests/tests_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1769 Update id for pvc size calculation tests
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1771 Touch-ups to WFFC documentation
  doc/waitforfirstconsumer-storage-handling.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1775 [Bugfix] wrong interpretation of custom cert rotation params
  pkg/operator/controller/certrotation_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cert/factory.go
  tests/certrotation_test.go
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1762 Add extra information when CDI pods are not ready
  hack/build/run-functional-tests.sh
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#1770 Namespace transfer fixing nitpicks
  pkg/controller/datavolume-controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1776 Make sure the DV is the main resource and single source of truth for …
  pkg/apis/core/v1alpha1/utils/utils.go
  pkg/apis/core/v1alpha1/utils/utils_test.go
  pkg/apis/core/v1beta1/utils/utils.go
  pkg/apis/core/v1beta1/utils/utils_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1782 Fix noaccess mode storage profile test
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1735 Restore compatibility in specifying custom CAs by using Go client
  doc/scratch-space.md
  pkg/importer/http-datasource.go
  tests/datavolume_test.go
  tests/utils/configmaps.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1778 Add functional test showing we proxy registry imports.
  tests/import_proxy_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1785 Use a method of deleting the pod that waits for it to no longer exist
  tests/framework/pvc.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1789 New release of fedora caused change in hash again.
  WORKSPACE
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1790 Update github.com/ulikunitz/xz for CVE-2021-29482
  go.mod
  go.sum
  vendor/github.com/ulikunitz/xz/LICENSE
  vendor/github.com/ulikunitz/xz/SECURITY.md
  vendor/github.com/ulikunitz/xz/TODO.md
  vendor/github.com/ulikunitz/xz/bits.go
  vendor/github.com/ulikunitz/xz/crc.go
  vendor/github.com/ulikunitz/xz/format.go
  vendor/github.com/ulikunitz/xz/internal/hash/cyclic_poly.go
  vendor/github.com/ulikunitz/xz/internal/hash/doc.go
  vendor/github.com/ulikunitz/xz/internal/hash/rabin_karp.go
  vendor/github.com/ulikunitz/xz/internal/hash/roller.go
  vendor/github.com/ulikunitz/xz/internal/xlog/xlog.go
  vendor/github.com/ulikunitz/xz/lzma/bintree.go
  vendor/github.com/ulikunitz/xz/lzma/bitops.go
  vendor/github.com/ulikunitz/xz/lzma/breader.go
  vendor/github.com/ulikunitz/xz/lzma/buffer.go
  vendor/github.com/ulikunitz/xz/lzma/bytewriter.go
  vendor/github.com/ulikunitz/xz/lzma/decoder.go
  vendor/github.com/ulikunitz/xz/lzma/decoderdict.go
  vendor/github.com/ulikunitz/xz/lzma/directcodec.go
  vendor/github.com/ulikunitz/xz/lzma/distcodec.go
  vendor/github.com/ulikunitz/xz/lzma/encoder.go
  vendor/github.com/ulikunitz/xz/lzma/encoderdict.go
  vendor/github.com/ulikunitz/xz/lzma/hashtable.go
  vendor/github.com/ulikunitz/xz/lzma/header.go
  vendor/github.com/ulikunitz/xz/lzma/header2.go
  vendor/github.com/ulikunitz/xz/lzma/lengthcodec.go
  vendor/github.com/ulikunitz/xz/lzma/literalcodec.go
  vendor/github.com/ulikunitz/xz/lzma/matchalgorithm.go
  vendor/github.com/ulikunitz/xz/lzma/operation.go
  vendor/github.com/ulikunitz/xz/lzma/prob.go
  vendor/github.com/ulikunitz/xz/lzma/properties.go
  vendor/github.com/ulikunitz/xz/lzma/rangecodec.go
  vendor/github.com/ulikunitz/xz/lzma/reader.go
  vendor/github.com/ulikunitz/xz/lzma/reader2.go
  vendor/github.com/ulikunitz/xz/lzma/state.go
  vendor/github.com/ulikunitz/xz/lzma/treecodecs.go
  vendor/github.com/ulikunitz/xz/lzma/writer.go
  vendor/github.com/ulikunitz/xz/lzma/writer2.go
  vendor/github.com/ulikunitz/xz/lzmafilter.go
  vendor/github.com/ulikunitz/xz/none-check.go
  vendor/github.com/ulikunitz/xz/reader.go
  vendor/github.com/ulikunitz/xz/writer.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1796 Only run clone across nodes on filesystem PVs only.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1791 Fix: Compute fs overhead only for fs volumeMode
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1799 [release-v1.34] Fix: Compute fs overhead only for fs volumeMode #1791
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1798 Enable test case 5072 - registry import, image contains valid archived raw file
  tests/transport_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1801 [BugFix] fix synchronization between smart clone and datavolume controller
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/transfer/pvc.go
  pkg/controller/transfer/pvc_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1804 Stop using deprecated admissionregistration, apiregistration v1beta1
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/cdi-validate_test.go
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/scheme.go
  pkg/apiserver/webhooks/transfer-validate.go
  pkg/apiserver/webhooks/transfer-validate_test.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/generate/install/BUILD.bazel
  pkg/operator/resources/generate/install/strategy.go
  vendor/k8s.io/api/admission/v1/BUILD.bazel
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XXL

#1809 [release-v1.34] Manual cherry pick of #1804
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/cdi-validate_test.go
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/scheme.go
  pkg/apiserver/webhooks/transfer-validate.go
  pkg/apiserver/webhooks/transfer-validate_test.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  vendor/k8s.io/api/admission/v1/BUILD.bazel
  vendor/k8s.io/api/admission/v1/doc.go
  vendor/k8s.io/api/admission/v1/generated.pb.go
  vendor/k8s.io/api/admission/v1/generated.proto
  vendor/k8s.io/api/admission/v1/register.go
  vendor/k8s.io/api/admission/v1/types.go
  vendor/k8s.io/api/admission/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1810 Fix - ignoring errors
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1803 Test: updated test id for fsOverhead resize tests
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
