Repository kubevirt/containerized-data-importer, pull requests merged in 2021-01, with the labels that each got.

#1535 Preallocation check all paths
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/BUILD.bazel
  cmd/cdi-uploadserver/uploadserver.go
  doc/preallocation.md
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/importer/data-processor.go
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1555 core: Preallocate blank image disks as well
  cmd/cdi-importer/importer.go
  pkg/controller/import-controller.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1542 Update CDI api for cert configuration
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/types_swagger_generated.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/certrotation.go
  pkg/operator/controller/certrotation_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/controller/reconciler-hooks.go
  pkg/operator/resources/cert/factory.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/operator/operator_test.go
  tests/operator_test.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/builder.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#1557 Compare logs while ignoring differences in spaces
  tests/cloner_test.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1562 Text-only changes missed in removing the Process phase (#1446)
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/s3-datasource.go
  pkg/importer/s3-datasource_test.go
  pkg/importer/upload-datasource_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1508 Use nbdkit for direct stream for the http importer
  WORKSPACE
  cmd/cdi-importer/BUILD.bazel
  pkg/image/BUILD.bazel
  pkg/image/nbdkit.go
  pkg/image/nbdkit_test.go
  pkg/image/qemu.go
  pkg/importer/format-readers.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  tests/datavolume_test.go
  tests/leaderelection_test.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/XL

#1560 Add a DV/PVC annotation "storage.bind.immediate.requested"
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  tests/datavolume_test.go
  tests/utils/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1564 VDDK: work with block devices better (BZ 1913756).
  cmd/cdi-importer/importer.go
  pkg/importer/BUILD.bazel
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
  tests/datavolume_test.go
  tests/utils/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#1558 Reduce the noise from the filesystem overhead functionality
  pkg/controller/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1556 update cdi config docs
  doc/cdi-config.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1571 Document smartclone disable feature in markdown
  doc/smart-clone.md
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1572 Skip test 2555 if running on openshift
  tests/datavolume_test.go
  tests/operator_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1581 [release-v1.28] Skip test 2555 if running on openshift (#1572)
  tests/datavolume_test.go
  tests/operator_test.go
  tests/utils.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1559 core: Preallocate blank block volumes
  cmd/cdi-importer/importer.go
  pkg/controller/import-controller.go
  pkg/image/qemu.go
  tests/import_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1582 Add Data Volume annotations documentation
  doc/datavolume-annotations.md
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1561 core: Preallocate blank image disks as well
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/BUILD.bazel
  cmd/cdi-uploadserver/uploadserver.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/importer/data-processor.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/datavolume.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#1568 Typedef for preallocation status
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/importer/data-processor.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1576 When cleaning up NFS disks, recursively delete their contents.
  tests/framework/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1584 Make DeletePodByName always wait for the pod to stop existing.
  tests/utils/pod.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#1583 Retry finding the pods for looking up the annotations.
  tests/BUILD.bazel
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1565 Global preallocation setting is not taken into account correctly.
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/config-controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1579 Update kubevirtci
  cluster-up/.gitignore
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.14/README.md
  cluster-up/cluster/k8s-1.14/provider.sh
  cluster-up/cluster/k8s-1.15/README.md
  cluster-up/cluster/k8s-1.15/provider.sh
  cluster-up/cluster/k8s-1.20/README.md
  cluster-up/cluster/k8s-1.20/dev-guide.md
  cluster-up/cluster/k8s-1.20/provider.sh
  cluster-up/cluster/k8s-fedora-1.17.0/README.md
  cluster-up/cluster/k8s-fedora-1.17.0/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/README.md
  cluster-up/cluster/kind-k8s-1.17.0-ipv6/provider.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/OWNERS
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certlib/selfsign.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/certsecret.go
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.mod
  cluster-up/cluster/kind-k8s-sriov-1.17.0/certcreator/go.sum
  cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh
  cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/manifests/kind-ipv6.yaml
  cluster-up/cluster/kind/manifests/kube-calico.diff.in
  cluster-up/cluster/kind/manifests/kube-calico.yaml.in
  cluster-up/cluster/kind/manifests/kube-flannel.yaml
  cluster-up/cluster/openshift-provider-common.sh
  cluster-up/cluster/os-3.11.0-crio/README.md
  cluster-up/cluster/os-3.11.0-crio/provider.sh
  cluster-up/cluster/os-3.11.0-multus/README.md
  cluster-up/cluster/os-3.11.0-multus/provider.sh
  cluster-up/cluster/os-3.11.0/README.md
  cluster-up/cluster/os-3.11.0/provider.sh
  cluster-up/hack/common.sh
  cluster-up/oc.sh
  hack/update-codegen.sh
  hack/update-kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#1598 Try to use the CDIConfig proxy URL if it is set, if not use port-forward
  tests/upload_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#1606 fix lsblk handling
  cmd/cdi-cloner/cloner_startup.sh
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#1580 Make string comparison less strict.
  tests/datavolume_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#1600 Enable tests for featuregates
  pkg/feature-gates/feature-gates_suite_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#1609 doc: update url in doc/datavolumes.md.
  doc/datavolumes.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#1601 Wait for clone to succeed before checking MD5.
  tests/cloner_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#1614 Add focus for destructive tests.
  automation/test.sh
  tests/operator_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
