Repository kubevirt/containerized-data-importer, pull requests merged in 2021-09, with the labels that each got.

#1916 Fix ingress test with no service to test right ingress
  pkg/apiserver/BUILD.bazel
  tests/cdiconfig_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1911 Avoid trying to get metrics from non-running pod.
  pkg/controller/datavolume-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1912 Replace all NAMESPACE refs with CDI_NAMESPACE
  Makefile
  automation/test.sh
  cluster-sync/clean.sh
  hack/build/build-manifests.sh
  hack/build/config.sh
  hack/build/resource-generator.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1926 Overhead on profile and usable space toghether
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1927 [release-v1.34] Overhead on profile and usable space toghether (#1926)
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1928 [release-v1.38] Overhead on profile and usable space toghether (#1926)
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1929 Wait for pod's Ready=True condition rather than phase=Ready
  tests/utils/pod.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1930 [release-v1.28] VDDK: Reduce read size when connecting to vCenter.
  pkg/importer/vddk-datasource.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1919 Stop qemu-img writing with cache=none
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1937 Commit write to disk in source-pvc filler pod
  tests/framework/pvc.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1939 BugId: 1999571 - fix clone into larger capacity nfs volume
  cluster-sync/nfs/nfs-server.yaml
  pkg/controller/datavolume-controller.go
  tests/cloner_test.go
  tests/framework/nfs-utils.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1933 VDDK: accept snapshot change IDs in previous checkpoint fields
  doc/datavolumes.md
  pkg/importer/BUILD.bazel
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1922 Add long term token to pvcs when host assisted cloning cross namespaces
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/util.go
  pkg/operator/resources/namespaced/controller.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1941 Set requests for CDI control plane
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/operator/BUILD.bazel
  pkg/operator/resources/operator/operator.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1935 rm tests/manifests/out and add to .gitignore
  .gitignore
  tests/manifests/out/dv1024MiPVC.yaml
  tests/manifests/out/templates/dv1024MiPVC.yaml.j2
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1936 Explicitly set the storage class name
  pkg/controller/datavolume-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1944 update go to 1.16.6
  WORKSPACE
  hack/build/config.sh
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1931 Run imageio test deployment as root
  manifests/templates/imageio.yaml.in
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1913 Support registry import using node docker cache
  BUILD.bazel
  api/openapi-spec/swagger.json
  cmd/cdi-importer/BUILD.bazel
  cmd/cdi-importer/importer.go
  doc/image-from-registry.md
  hack/build/run-functional-tests.sh
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/importer/transport.go
  pkg/operator/resources/crds_generated.go
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/import_proxy_test.go
  tests/import_test.go
  tests/tests_suite_test.go
  tests/transport_test.go
  tests/utils/datavolume.go
  tools/cdi-containerimage-server/BUILD.bazel
  tools/cdi-containerimage-server/main.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#1946 Update external links.
  CONTRIBUTING.md
  README.md
  doc/basic_pv_pvc_dv.md
  doc/image-from-registry.md
  hack/README.md
  pkg/importer/registry-datasource.go
  pkg/operator/resources/operator/operator.go
  pkg/util/openapi/openapi.go
  pkg/version/base.go
  pkg/version/types.go
  pkg/version/verflag/verflag.go
  tests/operator_test.go
  tools/openapi-spec-generator/definitions.go
  tools/util/marshaller.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1951 Correct the cloneStrategy on StorageProfile
  doc/storageprofile.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/core/v1beta1/types.go
  pkg/apis/core/v1beta1/types_swagger_generated.go
  pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  pkg/controller/datavolume-controller.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/util_test.go
  pkg/operator/resources/crds_generated.go
  tests/cloner_test.go
  tests/utils/storageprofile.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1952 make tools support aarch64
  WORKSPACE
  third_party/toolchains/toolchains.bzl
  tools/cdi-func-test-bad-webserver/BUILD.bazel
  tools/cdi-func-test-file-host-init/BUILD.bazel
  tools/cdi-func-test-proxy/BUILD.bazel
  tools/cdi-func-test-registry-init/BUILD.bazel
  tools/imageio-init/BUILD.bazel
  tools/loop-back-lvm/BUILD.bazel
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#1947 Remove unused scripts.
  hack/version/ci-skip-check.sh
  hack/version/lib.sh
  hack/version/set-version.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1950 Retry clone kill which is flaky
  tests/cloner_test.go
  tests/utils/pod.go
  tests/utils/pvc.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1957 fix cdi-importer wrong rpm package for aarch64
  WORKSPACE
  cmd/cdi-importer/BUILD.bazel
  tools/cdi-func-test-file-host-init/BUILD.bazel
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#1960 Use inclusive language, add check for inclusive language
  Makefile
  README.md
  cmd/cdi-apiserver/apiserver.go
  cmd/cdi-controller/controller.go
  cmd/cdi-uploadproxy/uploadproxy.go
  hack/README.md
  hack/build/release-description.sh
  hack/build/run-functional-tests.sh
  hack/ci/language.sh
  pkg/version/base.go
  pkg/version/version.go
  tests/cdiconfig_test.go
  tests/framework/framework.go
  tests/tests_suite_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1965 update builder image to 0.13
  hack/build/config.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
