Repository kubevirt/containerized-data-importer, pull requests merged in 2021-12, with the labels that each got.

#2034 Enable DataImportCron garbageCollect by default
  doc/os-image-poll-and-update.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/dataimportcron-controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2027 Add alert for incomplete storage profiles / delete profile when corresponding SC gone
  cluster-sync/sync.sh
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/controller/BUILD.bazel
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/operator/controller/prometheus.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/controller.go
  pkg/storagecapabilities/storagecapabilities.go
  tests/BUILD.bazel
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/import_test.go
  tests/operator_test.go
  tests/utils.go
  tests/utils/BUILD.bazel
  tests/utils/cli.go
  tests/utils/common.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2046 Fix hpp setup for tests.
  cluster-sync/ephemeral_provider.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1982 Switch builder to using centos:stream9
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/fedora.repo
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2047 [release-v1.38] Backport fix hpp tests
  cluster-sync/ephemeral_provider.sh
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/common.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2020 Skip VDI test on OpenShift
  tests/datavolume_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2051 Extend test for explicit storage class
  tests/datavolume_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2050 Improve directory detection on containerdisk imports
  pkg/importer/transport.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2055 used uncached client to get cluster proxy configmap
  pkg/controller/config-controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2056 Add tests numbers to dv quota tests
  tests/csiclone_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2054 make dependaabot happier (but not completely happy)
  .vscode/settings.json
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2004 Trigger Host Assisted Cloning for encrypted ocs sc.
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  tests/cloner_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2039 Add common labels into alert definitions
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/prometheus.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, ok-to-test, approved

#2037 Attempt to mitigate flake #1989, 'io: read/write on closed pipe'
  tests/upload_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2059 Whitespace change to builder to trigger postsubmit job
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2061 [release-v1.38] Revert "Backport fix hpp tests (#2047)"
  cluster-sync/ephemeral_provider.sh
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/import_test.go
  tests/upload_test.go
  tests/utils/common.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2045 Add DataImportCron status conditions
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/BUILD.bazel
  tests/dataimportcron_test.go
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#2035 [release-v1.38] Change some relationship labels on update as well (#2018)
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/storageprofile-controller.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/cruft.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2057 [release-v1.38] used uncached client to get cluster proxy configmap (#2055)
  pkg/controller/config-controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2062 Bump timeout in DataImportCron test suite
  tests/dataimportcron_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2065 HPP storage class file name changed.
  cluster-sync/ephemeral_provider.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2066 On CDI delete validation ignore DVs labeled with DataImportCron
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/common/common.go
  pkg/controller/dataimportcron-controller.go
  tests/operator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2064 clone source pod certs in secrets
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2052 Use ImageIO extents API to copy raw images more efficiently.
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/util/BUILD.bazel
  pkg/util/prometheus/BUILD.bazel
  pkg/util/prometheus/prometheus.go
  pkg/util/prometheus/prometheus_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/datavolume_test.go
  tests/imageio-inventory.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2068 Allow http in s3 datasource
  pkg/importer/s3-datasource.go
  pkg/importer/s3-datasource_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2063 Add alert for DataImportCron not being up to date
  cmd/cdi-controller/controller.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/operator/controller/prometheus.go
  tests/dataimportcron_test.go
  tests/operator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
