Repository kubevirt/containerized-data-importer, pull requests merged in 2021-11, with the labels that each got.

#2005 Fix blank block preallocation import
  pkg/image/BUILD.bazel
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  tests/import_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2008 Datacontroller cosmetics
  pkg/controller/datavolume-controller.go
  pkg/controller/util.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#1995 Attempt to handle flakes in upload/annotations tests
  tests/datavolume_test.go
  tests/upload_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2011 Replace the priorityClass to kubevirt-cluster-critical
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/common.go
  tests/operator_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1949 Add DataImportCron controller
  WORKSPACE
  cluster-sync/clean.sh
  cmd/cdi-controller/controller.go
  cmd/cdi-importer/BUILD.bazel
  doc/os-image-poll-and-update.md
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/dataimportcron-validate_test.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/handler.go
  pkg/controller/BUILD.bazel
  pkg/controller/config-controller.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/import-controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/cluster/cronjob.go
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/crds_generated.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/cronjob.go
  pkg/operator/resources/namespaced/factory.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/openapi_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/BUILD.bazel
  tests/dataimportcron_test.go
  tests/import_test.go
  tests/utils/datavolume.go
  tools/cdi-source-update-poller/BUILD.bazel
  tools/cdi-source-update-poller/main.go
  vendor/github.com/gorhill/cronexpr/APLv2
  vendor/github.com/gorhill/cronexpr/BUILD.bazel
  vendor/github.com/gorhill/cronexpr/GPLv3
  vendor/github.com/gorhill/cronexpr/README.md
  vendor/github.com/gorhill/cronexpr/cronexpr.go
  vendor/github.com/gorhill/cronexpr/cronexpr_next.go
  vendor/github.com/gorhill/cronexpr/cronexpr_parse.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2017 Disable [test_id:3937]succeed creating warm import dv
  tests/datavolume_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1994 Allow user-specified headers in HTTP data source.
  api/openapi-spec/swagger.json
  doc/datavolumes.md
  pkg/common/common.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/image/nbdkit.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/openapi_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/openapi_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/utils/datavolume.go
Labels: kind/proposal, release-note, size/XL, dco-signoff: yes, lgtm, approved

#2016 Emit event and update dv conditions when pvc fails to create due to quota
  pkg/controller/datavolume-conditions.go
  pkg/controller/datavolume-conditions_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/import-controller.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/import_test.go
  tests/smartclone_test.go
  tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2019 Remove skopeo binary dependency - use containers/image instead
  WORKSPACE
  cmd/cdi-importer/BUILD.bazel
  pkg/importer/BUILD.bazel
  pkg/importer/transport.go
  tools/cdi-source-update-poller/BUILD.bazel
  tools/cdi-source-update-poller/main.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2009 Degraded/unusual restartcount alerts
  go.mod
  go.sum
  pkg/common/common.go
  pkg/controller/upload-controller.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/prometheus.go
  tests/BUILD.bazel
  tests/datavolume_test.go
  tests/import_test.go
  tests/operator_test.go
  tests/utils.go
  tests/utils/BUILD.bazel
  tests/utils/upload.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2026 Fix DataImportCron test checks
  tests/dataimportcron_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2021 Move fsync to be after chmod on disk.img/1.22 flakes
  cmd/cdi-importer/importer.go
  pkg/image/qemu.go
  tests/framework/pvc.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2032 Less dependencies for containerized-data-importer-api
  hack/update-codegen.sh
  pkg/apis/core/v1alpha1/BUILD.bazel
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1beta1/BUILD.bazel
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/upload/v1alpha1/BUILD.bazel
  pkg/apis/upload/v1alpha1/openapi_generated.go
  pkg/apis/upload/v1beta1/BUILD.bazel
  pkg/apis/upload/v1beta1/openapi_generated.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/BUILD.bazel
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/upload/v1alpha1/BUILD.bazel
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/upload/v1beta1/BUILD.bazel
  tools/openapi-spec-generator/BUILD.bazel
  tools/openapi-spec-generator/openapi-spec-generator.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2018 Change some relationship labels on update as well
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/apiserver/apiserver_test.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cruft.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2028 uploadserver key/cert in secret
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/operator/resources/cluster/controller.go
  tests/basic_sanity_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2025 Add storageprofiles to RBAC
  pkg/operator/resources/cluster/rbac.go
  tests/rbac_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2038 Update fedora sha
  WORKSPACE
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2044 Fix cdi-containerimage-server readiness sync in cdi-importer
  cmd/cdi-importer/importer.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
