Repository kubevirt/containerized-data-importer, pull requests merged in 2022-04, with the labels that each got.

#2209 tighten sync between smart clone and transfer controllers
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
  pkg/controller/transfer/pvc.go
  pkg/controller/transfer/pvc_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2216 Update github.com/prometheus/client_golang to v1.11.1 (#2213)
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2220 [release-v1.43] Delete erroneous DVs on DataImportCron digest update
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/importer/data-processor.go
  tests/dataimportcron_test.go
  tests/operator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2221 Add timeout to importer cmd wait for server ready
  cmd/cdi-importer/importer.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2205 Improve handling of prePopulated DV
  pkg/controller/datavolume-conditions.go
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2223 Retry adding ticket on imageio container startup
  manifests/templates/imageio.yaml.in
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2218 Add lane scripts in repo
  automation/ceph.sh
  automation/destructive.sh
  automation/istio.sh
  automation/latest-hpp.sh
  automation/nfs.sh
  automation/previous-hpp.sh
  automation/upgrade.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2230 [release-v1.38] Delete profile as a follow up to storage class getting deleted
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2235 Switch VolumeSnapshot to v1
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  go.mod
  go.sum
  pkg/controller/BUILD.bazel
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v4/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2231 Gather all metrics info in a single location
  cmd/cdi-cloner/clone-source.go
  doc/metrics.md
  pkg/controller/dataimportcron-controller.go
  pkg/controller/storageprofile-controller.go
  pkg/image/qemu.go
  pkg/importer/format-readers.go
  pkg/monitoring/metrics.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/prometheus.go
  tools/metricsdocs/metricsdocs.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2202 Add unit test to make sure we don't clean up dataimportcrons accidentally
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2204 Test flakiness - DataImportCron - retry update at least once
  tests/dataimportcron_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2238 Fix DataImportCron watch race
  pkg/controller/dataimportcron-controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2237 cloner_startup.sh: "pipefail" requires bash
  cmd/cdi-cloner/cloner_startup.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved

#2215 Add metrics types to CDI metrics description
  doc/metrics.md
  tools/metricsdocs/metricsdocs.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, ok-to-test, approved

#2241 Extract the clone logic from main reconcile loop
  pkg/controller/datavolume-conditions.go
  pkg/controller/datavolume-controller.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2228 Quarantine flaky tests
  tests/datavolume_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2243 Describe clone-strategy annotation
  doc/efficient-cloning.md
  doc/storageprofile.md
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2245 Expose all CDI CRDs to cluster-readers
  cmd/cdi-cloner/BUILD.bazel
  pkg/controller/BUILD.bazel
  pkg/image/BUILD.bazel
  pkg/importer/BUILD.bazel
  pkg/operator/controller/BUILD.bazel
  pkg/operator/resources/cluster/rbac.go
  tests/rbac_test.go
  tools/metricsdocs/BUILD.bazel
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2246 [release-v1.43] Expose all CDI CRDs to cluster-readers
  pkg/operator/resources/cluster/rbac.go
  tests/rbac_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2249 [release-v1.43] Tighten DataImportCron & DataSource max name length
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2227 Bugfix - Correctly handle populated PVC
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
