Repository kubevirt/containerized-data-importer, pull requests merged in 2022-01, with the labels that each got.

#2075 Use existing DataVolume on DataImportCron source digest match
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2076 update builder golang to 1.17 remove kubebuilder
  hack/build/bazel-build-builder.sh
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/fedora.repo
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2085 Add DataSource controller to update the Ready condition
  cmd/cdi-controller/controller.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datasource-controller.go
  pkg/controller/datasource-controller_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2060 add PVC claimName to datavolume status
  api/openapi-spec/swagger.json
  cluster-sync/sync.sh
  manifests/templates/upgrade-testing-artifacts.yaml.in
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/datavolume-controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/BUILD.bazel
  tests/upgrade_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2083 Add test ids for Alert tests
  tests/operator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2082 Update relationship labels on missed ConfigMap
  cmd/cdi-controller/leaderelection.go
  pkg/common/common.go
  pkg/operator/controller/cruft.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2086 Remove tag from DataImportCron registry source URL
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2088 Cleanup DataImportCron jobs on deletion
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/namespaced/controller.go
  tests/dataimportcron_test.go
  tests/utils/pod.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2104 [release-v1.34] Backport cluster proxy test fix
  WORKSPACE
  cluster-sync/ephemeral_provider.sh
  tests/datavolume_test.go
  tests/import_proxy_test.go
  tests/import_test.go
  tests/utils.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2107 [release-v1.34] Backport some test fixes
  manifests/templates/imageio.yaml.in
  tests/alpha_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/smartclone_test.go
  tests/transport_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2099 Remove DataImportCron CDI labeling
  pkg/controller/dataimportcron-controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2095 Update DataSource Ready condition on DV update
  pkg/controller/datasource-controller.go
  tests/BUILD.bazel
  tests/datasource_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2102 Allow optional per-DataVolume VDDK image.
  api/openapi-spec/swagger.json
  doc/datavolumes.md
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/util.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1alpha1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/datavolume_test.go
  tests/utils/configmaps.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2103 Refactor the data-processor.go to allow customization
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2081 Use directly official libnbd go bindings
  WORKSPACE
  go.sum
  hack/build/bazel-generate.sh
  pkg/importer/BUILD.bazel
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  vendor/libguestfs.org/libnbd/BUILD.bazel
  vendor/libguestfs.org/libnbd/LICENSE
  vendor/libguestfs.org/libnbd/README.md
  vendor/libguestfs.org/libnbd/aio_buffer.go
  vendor/libguestfs.org/libnbd/bindings.go
  vendor/libguestfs.org/libnbd/callbacks.go
  vendor/libguestfs.org/libnbd/closures.go
  vendor/libguestfs.org/libnbd/go.mod
  vendor/libguestfs.org/libnbd/handle.go
  vendor/libguestfs.org/libnbd/wrappers.go
  vendor/libguestfs.org/libnbd/wrappers.h
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2113 Fix prometheus tests failing after bootstrap img bump on CI
  tests/utils.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2118 Improve failure reporting in tests
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/datavolume_test.go
  tests/smartclone_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2111 Fix error message to be without trace
  cmd/cdi-importer/importer.go
  tests/datavolume_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2091 [release-v1.38] Manual cherrypick 2082
  cmd/cdi-controller/leaderelection.go
  pkg/common/common.go
  pkg/operator/controller/cruft.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2126 Allow non amd64 native Go builds
  hack/build/build-go.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2117 Add DataImportCron ImageStream tag support
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datasource-controller.go
  pkg/controller/util.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2122 [release-v1.34] used uncached client to get cluster proxy configmap (#2055)
  pkg/controller/config-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2119 Catch changed rejection message
  tests/api_validation_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2043 Add tool to generate metrics documentation
  Makefile
  doc/metrics.md
  pkg/operator/controller/prometheus.go
  tools/metricsdocs/metricsdocs.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2129 Fix CRDs deletion in operator deletion
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/controller/callbacks.go
  tests/operator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved
