Repository kubevirt/containerized-data-importer, pull requests merged in 2022-02, with the labels that each got.

#2131 Replace batch/v1beta with v1
  go.mod
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tools/metricsdocs/BUILD.bazel
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2096 BugId: 2038679 - Clone with volume mode file system using Storage API fails
  cmd/cdi-importer/importer.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/controller/datavolume-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/utils/datavolume.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2132 Set http(s)_proxy to lower case env variable
  manifests/templates/cdi-testing-sa.yaml.in
  manifests/templates/file-host.yaml.in
  manifests/templates/test-proxy.yaml.in
  pkg/common/common.go
  pkg/controller/config-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/registry-datasource.go
  pkg/util/util.go
  tests/datavolume_test.go
  tests/import_proxy_test.go
  tests/transport_test.go
  tests/utils/configmaps.go
  tools/cdi-func-test-file-host-init/BUILD.bazel
  tools/cdi-func-test-file-host-init/nginx.conf
  tools/cdi-func-test-proxy/BUILD.bazel
  tools/cdi-func-test-proxy/main.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2138 [release-v1.38] Set http(s)_proxy to lower case env variable
  manifests/templates/cdi-testing-sa.yaml.in
  manifests/templates/file-host.yaml.in
  manifests/templates/test-proxy.yaml.in
  pkg/common/common.go
  pkg/controller/config-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/registry-datasource.go
  pkg/util/util.go
  tests/import_proxy_test.go
  tests/transport_test.go
  tests/utils/configmaps.go
  tools/cdi-func-test-file-host-init/BUILD.bazel
  tools/cdi-func-test-file-host-init/nginx.conf
  tools/cdi-func-test-proxy/BUILD.bazel
  tools/cdi-func-test-proxy/main.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2139 [release-v1.34] Set http(s)_proxy to lower case env variable
  cluster-sync/sync.sh
  manifests/templates/cdi-testing-sa.yaml.in
  manifests/templates/file-host.yaml.in
  manifests/templates/test-proxy.yaml.in
  pkg/common/common.go
  pkg/controller/config-controller.go
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/registry-datasource.go
  pkg/util/util.go
  tests/import_proxy_test.go
  tests/transport_test.go
  tests/utils/configmaps.go
  tools/cdi-func-test-file-host-init/BUILD.bazel
  tools/cdi-func-test-file-host-init/nginx.conf
  tools/cdi-func-test-proxy/BUILD.bazel
  tools/cdi-func-test-proxy/main.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2140 use leases AND configmaps for leader election
  cmd/cdi-controller/controller.go
  cmd/cdi-operator/operator.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/operator/operator.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2134 [release-v1.43] BugId: 2038679 - Clone with volume mode file system using Storage API fails
  cmd/cdi-importer/importer.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/controller/datavolume-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/utils/datavolume.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2135 [release-v1.38] BugId: 2038679 - Clone with volume mode file system using Storage API fails
  cmd/cdi-importer/importer.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/controller/datavolume-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
  tests/framework/pvc.go
  tests/utils/datavolume.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2142 Reconcile DataSource PVC on update if managed by DataImportCron
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2148 Fix failing imageio test
  pkg/controller/import-controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2150 Ignore error in upload copy test
  tests/upload_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2143 Extend tests to check explicit storage class name
  tests/datavolume_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2144 Get rid of DataImportCron finalizer
  pkg/common/common.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/controller/callbacks.go
  pkg/operator/resources/cluster/controller.go
  tests/dataimportcron_test.go
  tests/operator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2157 [release-v1.43] Get rid of DataImportCron finalizer
  pkg/common/common.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/controller/callbacks.go
  pkg/operator/resources/cluster/controller.go
  tests/dataimportcron_test.go
  tests/operator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2153 [release-v1.38] Fix failing imageio test (#2148)
  pkg/controller/import-controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2154 [release-v1.34] Fix failing imageio test (#2148)
  pkg/controller/import-controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2155 Increase time we wait for cdiconfig update
  tests/utils/common.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2141 Simplify importer code, cleanup and extract function
  cmd/cdi-importer/importer.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2158 Fix SnapshotForSmartCloneInProgress sometimes not occuring
  pkg/controller/datavolume-controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2079 Add test cases for runbook URLs
  tests/operator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, ok-to-test, approved

#2168 Fix VerifySparse to look at content size and not size on disk
  tests/framework/BUILD.bazel
  tests/framework/pvc.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
