Repository kubevirt/containerized-data-importer, pull requests merged in 2022-08, with the labels that each got.

#2371 Only list Ingresses/Routes in CDI namespace instead of cluster level
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/controller/clone-controller.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datasource-controller.go
  pkg/controller/datavolume-controller.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/transfer/watch.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/namespaced/controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2370 Add test IDs/minor steps to crypto policy tests
  tests/apiserver_test.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2363 Fix race condition in upload-controller to keep PVC annotations after a clone error
  pkg/controller/datavolume-controller.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  tests/cloner_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2379 update portworx storage capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, needs-ok-to-test, approved

#2373 Queue DataVolumes referred to in "populatedFor" annotations
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2380 Use container image name in server as-is
  cmd/cdi-importer/importer.go
  tests/BUILD.bazel
  tools/cdi-containerimage-server/main.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2368 Fix failure to resize when the request image size is specified in milli- scale.
  pkg/importer/data-processor.go
  tests/cloner_test.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2381 Update DataSource LastTransitionTime when populated PVC is updated
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/datasource-controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/datasource_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2364 Status reporting for CSI & Smart clones with WFFC storage
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  go.mod
  pkg/controller/datavolume-controller.go
  tests/cloner_test.go
  tests/framework/framework.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2382 Add omitempty to DataSourceStatus.source
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2375 Check for pvc populated before doing any clone validations and actions
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2386 test fix: Move check of clone type before create target pvc
  tests/cloner_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2383 Ability to run tests in D/S
  hack/build/build-functest.sh
  hack/build/build-manifests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved

#2401 [release-v1.53] Manual backport of 2364, 2375
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  go.mod
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
  tests/framework/framework.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2388 Fix flake where cross ns finalizer can't be removed
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2404 Fix ingress annotations
  doc/exposing-upload-proxy.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2408 Add DV garbage collection doc
  api/openapi-spec/swagger.json
  doc/cdi-config.md
  doc/datavolumes.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2405 [release-v1.43] Manual fix for clone without source pvc but target pvc already populated
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2411 Revert "[release-v1.43] Manual fix for clone without source pvc but t…
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note-none, size/L, dco-signoff: yes, approved

#2397 fix issue #2391 When clone dv from an existing pvc use smart clone, s…
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, needs-ok-to-test, approved

#2409 Always set a valid ContentType for created PVC
  pkg/controller/datavolume-controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2399 Simplify test PVC creation & force-binding code
  tests/api_validation_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/leaderelection_test.go
  tests/transport_test.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2406 [release-v1.49] Manual fix for clone without source pvc but target pvc already populated
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2412 [release-v1.43] Redo 2405
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
