Repository kubevirt/containerized-data-importer, pull requests merged in 2022-11, with the labels that each got.

#2454 Update kubevirtci
  cluster-up/cluster/K8S.md
  cluster-up/cluster/K8S_DEV_GUIDE.md
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k8s-1.24-psa/provider.sh
  cluster-up/cluster/k8s-1.25/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.22-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-1.22-sriov/conformance.json
  cluster-up/cluster/kind-1.22-sriov/provider.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-1.22-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-1.22-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-1.23-vgpu/conformance.json
  cluster-up/cluster/kind-1.23/README.md
  cluster-up/cluster/kind-1.23/provider.sh
  cluster-up/cluster/kind/check-cluster-up.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/kind/configure-registry-proxy.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#2448 Wait for podman stop to successfully stop rsync container
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2455 Add DataImportCron CronJobs Proxy support
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/import-controller.go
  pkg/importer/registry-datasource.go
  tests/dataimportcron_test.go
  tests/import_proxy_test.go
  tests/operator_test.go
  tests/utils/BUILD.bazel
  tests/utils/dataimportcron.go
  tools/cdi-source-update-poller/main.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2458 Document CRI config that allows non-root containers usage of block devices
  doc/block_cri_ownership_config.md
  doc/datavolumes.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2466 Fix SCC priority so it doesn't get picked for random pods
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/scc.go
  tests/operator_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2470 Add topolvm to known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2476 Suppress alerting for unsupported provisioners
  pkg/controller/BUILD.bazel
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/storagecapabilities/storagecapabilities.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/testutil/lint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/BUILD.bazel
  vendor/github.com/prometheus/client_golang/prometheus/testutil/promlint/promlint.go
  vendor/github.com/prometheus/client_golang/prometheus/testutil/testutil.go
  vendor/modules.txt
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#2479 Update to include mount for containers dir in bazel-docker.sh
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2481 Bump kubevirtci, bump k8s versions used in CI
  automation/ceph.sh
  automation/destructive.sh
  automation/istio.sh
  automation/latest-hpp.sh
  automation/nfs.sh
  automation/previous-hpp.sh
  automation/upgrade.sh
  cluster-sync/k8s-1.17/provider.sh
  cluster-sync/k8s-1.18/provider.sh
  cluster-sync/k8s-1.19/provider.sh
  cluster-sync/k8s-1.20/provider.sh
  cluster-sync/k8s-1.25/provider.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/kind-1.22-sriov/provider.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
  tests/manifests/dvInvalidSourcePVC.yaml
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2478 Update golang to 1.18.8
  WORKSPACE
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2488 Preserve permissions on extract
  pkg/util/util.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2493 [release-1.49] Queue DataVolumes referred to in "populatedFor" PVC annotations
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2492 Use new builder with GO 1.18.8
  hack/build/config.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
