Repository kubevirt/containerized-data-importer, pull requests merged in 2022-12, with the labels that each got.

#2484 refactor: move from io/ioutil to io and os packages
  cluster-up/cluster/kind-1.22-sriov/certcreator/certsecret.go
  cmd/cdi-cloner/clone-source.go
  cmd/cdi-cloner/clone-source_test.go
  cmd/cdi-controller/controller.go
  cmd/cdi-importer/importer.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/handler.go
  pkg/controller/datavolume-controller.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor_test.go
  pkg/importer/format-readers.go
  pkg/importer/format-readers_test.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/registry-datasource.go
  pkg/importer/registry-datasource_test.go
  pkg/importer/s3-datasource_test.go
  pkg/importer/transport_test.go
  pkg/importer/upload-datasource_test.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/uploadserver/uploadserver.go
  pkg/util/cert/cert.go
  pkg/util/cert/fetcher/certfetcher.go
  pkg/util/prometheus/prometheus.go
  pkg/util/prometheus/prometheus_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/api_validation_test.go
  tests/import_test.go
  tests/operator_test.go
  tests/utils/certs.go
  tools/cdi-containerimage-server/main.go
  tools/cdi-func-test-proxy/main.go
  tools/crd-generator/crd-generator.go
  tools/manifest-generator/manifest-generator.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, needs-ok-to-test, approved

#2496 Fix bazel build command
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2497 remove vscode settings
  .gitignore
  .vscode/settings.json
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2494 [release-1.43] Queue DataVolumes referred to in "populatedFor" PVC annotations
  pkg/controller/datavolume-controller.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2504 Update cdi-testing-sa SCC to work in newer Open Shift
  manifests/templates/cdi-testing-scc.yaml.in
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2480 Make cluster-sync more friendly for external provider
  README.md
  cluster-sync/clean.sh
  cluster-sync/external/README.md
  cluster-sync/sync.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2485 Log specific test failure artifact path for easier debugging
  tests/framework/framework.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2505 Correct skip message on CSI Clone tests
  tests/cloner_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2507 Add cinder to known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2513 Bump volumesnapshot client to v6
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  go.mod
  go.sum
  pkg/controller/BUILD.bazel
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  tests/BUILD.bazel
  tests/cloner_test.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/LICENSE
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/types.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/apis/volumesnapshot/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2518 Create unit test suite for new folders following refactor
  pkg/controller/common/BUILD.bazel
  pkg/controller/common/controller_suite_test.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/controller_suite_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
