Repository kubevirt/containerized-data-importer, pull requests merged in 2022-10, with the labels that each got.

#2430 Add restart policy for rsync container
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2440 Remove namespaced rbac for dataimportcron
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/namespaced/cronjob.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2444 Update cdi-config.md
  doc/cdi-config.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test, approved

#2445 Enable HonorWaitForFirstConsumer by default
  doc/waitforfirstconsumer-storage-handling.md
  manifests/templates/release/cdi-cr.yaml.in
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2253 Address possible nils in dv controller, log CSIDrivers in tests
  pkg/controller/datavolume-controller.go
  pkg/controller/datavolume-controller_test.go
  tests/framework/framework.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2427 Add make target to verify deps
  Makefile
  hack/diff-csv.sh
  hack/verify-codegen.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2389 Add fossa check for licenses.
  .fossa.yml
  Makefile
  go.mod
  go.sum
  hack/ci/language.sh
  hack/fossa.sh
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
