Repository kubevirt/containerized-data-importer, pull requests merged in 2023-10, with the labels that each got.

#2911 [release-v1.57] Delete old version DVs with DIC GC
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/dataimportcron_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2917 Respect wffc override for blank block disks
  cmd/cdi-importer/importer.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/import_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2934 Update builder to use golang 1.20.10 and bazel 5.4.0
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2910 [release-v1.57] Manual backport of AnnPodRetainAfterCompletion with populators
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/populators/clone-populator.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/util.go
  tests/cloner_test.go
  tests/import_proxy_test.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2913 Default storage class for virtualization purposes
  cmd/cdi-controller/controller.go
  doc/metrics.md
  pkg/controller/clone-controller.go
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/upload-populator.go
  pkg/controller/populators/util.go
  pkg/controller/storageprofile-controller.go
  pkg/monitoring/metrics.go
  pkg/operator/controller/prometheus.go
  tests/clone-populator_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/monitoring_test.go
  tests/utils/datavolume.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2942 Use golang 1.20.10 when building CDI
  WORKSPACE
  hack/build/config.sh
  vendor/golang.org/x/sys/windows/BUILD.bazel
  vendor/sigs.k8s.io/json/internal/golang/encoding/json/BUILD.bazel
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2928 Improve DataVolume status reporting with populators
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/import-populator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2945 Address error condition to avoid DataVolumeError status during VM provisioning
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/data-processor.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2944 Mount block PVC rw in clone source pods
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/common/util.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2951 [release-v1.57] Check PVC Prime before updating DV status to improve status reporting
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/import-populator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
