Repository kubevirt/containerized-data-importer, pull requests merged in 2023-08, with the labels that each got.

#2821 Fix race condition in populators so we clean up PVC' after population succeeds
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  tests/import_test.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2833 [release-v1.57] Manual cherrypick of #2821
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  tests/import_test.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2834 Skip code-block formatting from api-reference
  hack/gen-swagger-doc/gen-swagger-docs.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2787 dataVolume: Add default instance type labels from source
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2832 Always use scratchspace when importing and converting
  WORKSPACE
  pkg/controller/import-controller.go
  pkg/importer/data-processor.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  rpm/BUILD.bazel
  tests/datavolume_test.go
  tests/import_proxy_test.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2841 [release-v1.57] Always use scratchspace when importing and converting (#2832)
  WORKSPACE
  pkg/controller/import-controller.go
  pkg/importer/data-processor.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  rpm/BUILD.bazel
  tests/datavolume_test.go
  tests/import_proxy_test.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2840 Fix broken local -> rook-ceph-block clone
  pkg/controller/clone/common.go
  pkg/controller/clone/planner.go
  pkg/controller/clone/planner_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2845 Don't use scratch space for registry node pull imports
  BUILD.bazel
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/image/qemu.go
  pkg/importer/http-datasource.go
  tests/BUILD.bazel
  tests/import_test.go
  tests/utils/datavolume.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2844 Improve alert rules sanity test
  tests/monitoring_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2858 [release-v1.56] Tolerate GetActiveCDI returning nil, nil
  pkg/operator/controller/cruft.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2855 bump k8s.io/client-go dep for discovery client fixes
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/modules.txt
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2863 [release-v1.57] Backport 'bump k8s.io/client-go dep for discovery client fixes'
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/openapi_generated.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apis/upload/v1beta1/openapi_generated.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/modules.txt
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2862 increase controller concurrency and cpu requests
  pkg/controller/clone-controller.go
  pkg/controller/config-controller.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datasource-controller.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/external-population-controller.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/import-controller.go
  pkg/controller/populators/clone-populator.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/upload-populator.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/transfer/controller.go
  pkg/controller/upload-controller.go
  pkg/operator/controller/controller.go
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/operator/operator.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2861 [release-v1.56] Do not fail DV reconcile if storage class is not found
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2860 Do not fail DV reconcile if storage class is not found
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2864 Ensure priority class is assigned to pod populating pvc prime
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/populators/clone-populator_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator_test.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2865 DataImportCron external trigger polarion id
  tests/dataimportcron_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved

#2872 [release-v1.57] Ensure priority class is assigned to pod populating pvc prime
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/populators/clone-populator_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2876 [release-v1.56] Update golang builder for 1.56 to golang 1.19.12
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2875 Update builder to use golang 1.20.7
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2879 Fix gingko install in builder
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2880 Fix gingko v2 path in builder
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2837 Avoid creating snapshot of old storage class DataImportCron PVCs
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2866 Audit RBAC, avoid global (*) permissions
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/operator/controller/prometheus.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/factory.go
  pkg/operator/resources/namespaced/prometheus.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/operator/operator.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
