Repository kubevirt/containerized-data-importer, pull requests merged in 2023-02, with the labels that each got.

#2566 Fix DataImportCron PVC timestamping
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2565 Allow root podman for cluster-sync
  hack/build/bazel-docker.sh
  hack/build/common.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2553 Add functional test for unsupported provisioners
  tests/BUILD.bazel
  tests/operator_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2568 Fix DataImportCron PVC GC test timeout
  tests/dataimportcron_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2567 [release-v1.55] Fix DataImportCron PVC timestamping
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2527 Remove v1alpha1 version from CDI CRD
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/cruft.go
  pkg/operator/controller/reconciler-hooks.go
  tests/operator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2572 Check docker first
  hack/build/common.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2522 Clone from VolumeSnapshot source
  api/openapi-spec/swagger.json
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/clone/auth.go
  pkg/common/common.go
  pkg/controller/common/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/smart-clone-controller.go
  pkg/controller/datavolume/smart-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller_test.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/cloner_test.go
  tests/framework/framework.go
  tests/tests_suite_test.go
  tests/utils/datavolume.go
  tests/webhook_test.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/scheme/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/BUILD.bazel
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/doc.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/fake/fake_volumesnapshotcontent.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/generated_expansion.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/volumesnapshot_client.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotclass.go
  vendor/github.com/kubernetes-csi/external-snapshotter/client/v6/clientset/versioned/typed/volumesnapshot/v1/volumesnapshotcontent.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2570 Print chosen CDI_CRI
  hack/build/common.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2573 Remove stack trace from PVC and DataVolume events in case of import error
  cmd/cdi-importer/importer.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2571 Watch DataSources in DV clone controller
  pkg/controller/datavolume/pvc-clone-controller.go
  tests/datasource_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2577 Fix operator_test CDI CR Gets
  tests/operator_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2580 [release-v1.55] Watch DataSources in DV controller
  pkg/controller/datavolume-controller.go
  tests/datasource_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2578 docs: fix exposing upload proxy ingress
  doc/exposing-upload-proxy.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved

#2581 [release-v1.55] Fix cdi_cr_ready test CDI CR name
  tests/operator_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2574 Add clone from VolumeSnapshot docs
  doc/clone-from-volumesnapshot-source.md
  doc/datavolumes.md
  doc/efficient-cloning.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2586 Fix flaky destructive metric tests
  tests/operator_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2585 Update builder image to use golang 1.19.5
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2584 Apply retry filter to ndkit conversions
  pkg/image/nbdkit.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2596 Use real tmpdir path in qemu blank image unit tests
  pkg/image/qemu_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2588 Stop forcing preallocation on block imports
  cmd/cdi-importer/importer.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2595 Another attempt to stabilize storage profile metric tests
  tests/operator_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2601 Fix DV verifyConditions test
  tests/datasource_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2602 [release-v1.55] Fix DV verifyConditions test
  tests/datasource_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2583 Annotation to check for statically provisioned PVs when creating DataVolumes
  cmd/cdi-controller/controller.go
  go.mod
  go.sum
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/handler.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/external-population-controller.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/static-volume_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/util.go
  tests/BUILD.bazel
  tests/cloner_test.go
  tests/external_population_test.go
  tests/static-volume_test.go
  tests/utils/datavolume.go
  tests/webhook_test.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/storage/volume/BUILD.bazel
  vendor/k8s.io/component-helpers/storage/volume/helpers.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2587 Verify that ginkgo suite is bootstrapped
  Makefile
  hack/build/bootstrap-ginkgo.sh
  pkg/token/BUILD.bazel
  pkg/token/token_suite_test.go
  pkg/token/token_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2592 Adjust alpha deprecation tests
  tests/framework/pvc.go
  tests/operator_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved
