Repository kubevirt/containerized-data-importer, pull requests merged in 2023-09, with the labels that each got.

#2883 [release-v1.57] dataVolume: Add default instance type labels from source (#2787)
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
  tests/datavolume_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2789 Fix Portworx CSI storage capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2740 Upgrade golangci-lint to v1.54.2 and fix findings
  .golangci.yml
  hack/build/run-linters.sh
  pkg/operator/controller/certrotation.go
  pkg/operator/controller/certrotation_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2889 Add unit test for bad RBAC practices
  pkg/operator/controller/controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2882 Allow modifying log verbosity in CDI
  api/openapi-spec/swagger.json
  doc/debug.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2868 Update ontap-san to be RWX
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2749 Delete old version DVs with DIC GC
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/dataimportcron_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2873 Allow the usage of AnnPodRetainAfterCompletion with populators
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/populators/clone-populator.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/util.go
  tests/cloner_test.go
  tests/import_proxy_test.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2897 [release-v1.56] Fix Portworx CSI storage capabilities
  pkg/controller/storageprofile-controller.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2901 [release-v1.56] Fix flakes when using gigabytes intead of gibibytes
  tests/webhook_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2902 [release-v1.55] Fix Portworx CSI storage capabilities
  pkg/controller/storageprofile-controller.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2900 Fix possible nil ptr in snapshot/pvc clone controllers
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2904 Update doc of shouldUseCDIPopulator to reflect changes
  doc/cdi-populators.md
  pkg/controller/datavolume/controller-base.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2907 chore: import packages only once
  pkg/util/cert/cert.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved
