Repository kubevirt/containerized-data-importer, pull requests merged in 2023-03, with the labels that each got.

#2604 Respect bind.immediate annotation by not attempting fancy clones
  pkg/controller/common/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  tests/cloner_test.go
  tests/datasource_test.go
  tests/datavolume_test.go
  tests/import_test.go
  tests/utils/BUILD.bazel
  tests/utils/common.go
  tests/utils/dataimportcron.go
  tests/utils/datavolume.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2613 Add manila csi to list of known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2610 Testing suite adjustments for testing on WFFC snapshot capable storage
  tests/cloner_test.go
  tests/utils/datavolume.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2582 Add sourceRef support for VolumeSnapshot sources
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datasource-controller.go
  pkg/controller/datasource-controller_test.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/cloner_test.go
  tests/datasource_test.go
  tests/utils/datavolume.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2618 Simplify upgrade testing, and only test v1beta1 DVs
  cluster-sync/sync.sh
  manifests/templates/upgrade-testing-artifacts-no-gc.yaml.in
  manifests/templates/upgrade-testing-artifacts.yaml.in
  tests/upgrade_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2624 Avoid CI downgrading from latest release to cherrypick PR
  automation/test.sh
  hack/common-funcs.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2625 Add SYS_CHROOT cap to rsync in build
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2611 Enable DV status subresource
  pkg/controller/datavolume/controller-base.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2619 Add ref ids and test ids for clone and datasource tests
  tests/cloner_test.go
  tests/datasource_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2593 add http zstd reader for cdi
  pkg/image/filefmt.go
  pkg/image/validate.go
  pkg/importer/BUILD.bazel
  pkg/importer/format-readers.go
  tests/datavolume_test.go
  tests/utils/BUILD.bazel
  tests/utils/datavolume.go
  tests/utils/fileConversion.go
  tools/cdi-func-test-file-host-init/main.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, ok-to-test, approved

#2634 Bump bazel version in builder
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2637 Adapt operator_test to cover OpenShift
  tests/framework/nodeplacement.go
  tests/operator_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2547 Pass DV labels to PVC
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/smart-clone-controller.go
  pkg/controller/datavolume/smart-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/cloner_test.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2589 Add support for imagePullSecrets
  api/openapi-spec/swagger.json
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/clone-controller.go
  pkg/controller/common/util.go
  pkg/controller/config-controller.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/upload-controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/crds_generated.go
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/factory.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/operator/factory.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/utils/common.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2640 Update git config to mark rsync directory as safe
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2648 Add nfs-subdir-external-provisioner to CapabilitiesByProvisionerKey
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, ok-to-test, approved

#2633 Follow up for WFFC test suite adjustments
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/datavolume_test.go
  tests/external_population_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/smartclone_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2641 Add document explaining requirements for mainters/approvers
  doc/maintainer.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2651 [release-v1.55] Manual backport of follow up for WFFC test suite adjustments
  tests/cloner_test.go
  tests/csiclone_test.go
  tests/datavolume_test.go
  tests/framework/pvc.go
  tests/import_test.go
  tests/smartclone_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2650 Annotate DIC-created DV for immediate binding
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/import_proxy_test.go
  tests/utils/dataimportcron.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2656 [release-v1.55] Annotate DIC-created DV for immediate binding
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/import_proxy_test.go
  tests/utils/dataimportcron.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2661 Add ovirt csi to known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2658 Report last DV phase in tests when garbage collection fails
  tests/utils/datavolume.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2673 [release-v1.54] Combine several fixes so we can run test builds again
  automation/test.sh
  hack/build/bazel-docker.sh
  hack/common-funcs.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
