Repository kubevirt/containerized-data-importer, pull requests merged in 2023-05, with the labels that each got.

#2647 Set pod affinity for host assisted clone
  pkg/controller/clone-controller.go
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2683 Create PVC if possible even if the StorageClass is missing
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/conditions.go
  pkg/controller/datavolume/conditions_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/smart-clone-controller.go
  pkg/controller/datavolume/util.go
  tests/csiclone_test.go
  tests/datasource_test.go
  tests/datavolume_test.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#2705 Fix import populator static binding test
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/util.go
  tests/import_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2678 Upload populator
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/client/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_volumeuploadsource.go
  pkg/client/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/core/v1beta1/volumeuploadsource.go
  pkg/client/informers/externalversions/core/v1beta1/BUILD.bazel
  pkg/client/informers/externalversions/core/v1beta1/interface.go
  pkg/client/informers/externalversions/core/v1beta1/volumeuploadsource.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1beta1/BUILD.bazel
  pkg/client/listers/core/v1beta1/expansion_generated.go
  pkg/client/listers/core/v1beta1/volumeuploadsource.go
  pkg/controller/populators/BUILD.bazel
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/populators_suite_test.go
  pkg/controller/populators/upload-populator.go
  pkg/controller/populators/upload-populator_test.go
  pkg/controller/populators/util.go
  pkg/controller/upload-controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/populationsources.go
  pkg/operator/resources/crds_generated.go
  pkg/uploadproxy/BUILD.bazel
  pkg/uploadproxy/uploadproxy.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/register.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/upload_test.go
  tests/utils/BUILD.bazel
  tests/utils/upload.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2703 enable ginkgolinter and fix findings
  .golangci.yml
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/webhooks/dataimportcron-validate_test.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/clone-controller_test.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/conditions_test.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util_test.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/controller/transfer/dv_test.go
  pkg/controller/upload-controller_test.go
  pkg/importer/format-readers_test.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/vddk-datasource_test.go
  pkg/operator/controller/controller_test.go
  pkg/util/util_test.go
  tests/basic_sanity_test.go
  tests/certrotation_test.go
  tests/cloner_test.go
  tests/dataimportcron_test.go
  tests/datavolume_test.go
  tests/framework/vddk.go
  tests/imageio-inventory.go
  tests/import_proxy_test.go
  tests/import_test.go
  tests/monitoring_test.go
  tests/operator_test.go
  tests/rbac_test.go
  tests/smartclone_test.go
  tests/transport_test.go
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#2636 Move pkg/clone/auth to API lib and introduce single dv.Authorize()
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/handler.go
  pkg/clone/BUILD.bazel
  pkg/clone/auth.go
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/BUILD.bazel
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize_utils.go
  tests/BUILD.bazel
  tests/webhook_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2707 Add a webhook for import and upload populator CRs
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/populators-validate.go
  pkg/apiserver/webhooks/populators-validate_test.go
  pkg/apiserver/webhooks/util.go
  pkg/controller/populators/import-populator.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/apiserver.go
  tests/api_validation_test.go
  tests/manifests/volumeimportsource.yaml
  tests/manifests/volumeuploadsource.yaml
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2712 Propagate CDI workload NodePlacement to DIC CronJob and initial Job
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/import-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2717 Add Hitachi to known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2720 [release-v1.56] Add Dell EMC, HPE & Hitachi to known provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2721 Fixes issue with smart clone hanging while waiting for initial import
  pkg/controller/datavolume/pvc-clone-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#2723 DataImportCron dusty stuff cleanups
  hack/README.md
  pkg/common/common.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/import-controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/controller.go
  tests/BUILD.bazel
  tests/dataimportcron_test.go
  tests/framework/pvc.go
  tools/cdi-source-update-poller/main.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2706 [release-v1.56] Skip TLS crypto test/ensure anyvolumedatasource test pvc is gone
  tests/external_population_test.go
  tests/upload_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2727 [release-v1.55] Handle 0 restore size better v155
  pkg/controller/smart-clone-controller.go
  pkg/controller/smart-clone-controller_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2728 Add test ids for dataimportcron tests
  tests/dataimportcron_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2729 add PendingPopulation DataVolume phase
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/utils.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2711 Enable external trigger in DataImportCron
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/dataimportcron-validate_test.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/dataimportcron_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, ok-to-test, approved

#2733 [release-v1.56] Propagate CDI workload NodePlacement to DIC CronJob and initial Job
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/import-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2734 [release-v1.55] Propagate CDI workload NodePlacement to DIC CronJob and initial Job
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/import-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2731 expand upon #2721
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
