Repository kubevirt/containerized-data-importer, pull requests merged in 2023-04, with the labels that each got.

#2644 Ceph WFFC lane set up
  automation/ceph-wffc.sh
  cluster-sync/k8s-1.22/provider.sh
  cluster-sync/k8s-1.23/provider.sh
  cluster-sync/k8s-1.24/provider.sh
  cluster-sync/k8s-1.25/provider.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/k3d-1.25-sriov/OWNERS
  cluster-up/cluster/k3d-1.25-sriov/README.md
  cluster-up/cluster/k3d-1.25-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/k3d-1.25-sriov/config_sriov_cluster.sh
  cluster-up/cluster/k3d-1.25-sriov/conformance.json
  cluster-up/cluster/k3d-1.25-sriov/provider.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/k3d-1.25-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/k3d-1.25-sriov/sriov-node/node.sh
  cluster-up/cluster/k3d-1.25-sriov/sriovdp_setup.sh
  cluster-up/cluster/k3d/check-cluster-up.sh
  cluster-up/cluster/k3d/common.sh
  cluster-up/cluster/k3d/manifests/calico.yaml
  cluster-up/cluster/k8s-1.23/provider.sh
  cluster-up/cluster/k8s-1.24-psa/provider.sh
  cluster-up/cluster/k8s-1.25-ipv6/provider.sh
  cluster-up/cluster/k8s-1.26/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.23-sriov/provider.sh
  cluster-up/cluster/kind-1.23/provider.sh
  cluster-up/cluster/kind-1.25-vgpu/README.md
  cluster-up/cluster/kind-1.25-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.25-vgpu/conformance.json
  cluster-up/cluster/kind-1.25-vgpu/provider.sh
  cluster-up/cluster/kind-1.25-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  cluster-up/ssh.sh
  cluster-up/up.sh
  hack/update-kubevirtci.sh
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2684 fix typo in token payload
  pkg/token/token.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2681 [release-v1.55] manual cherrypick of #2536
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2676 more targeted cleanup of target/scratch pvcs
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/gcs-datasource.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/registry-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  tests/framework/pvc.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2680 Allow restoreSize to be 0, and use request size if 0
  pkg/controller/datavolume/smart-clone-controller.go
  pkg/controller/datavolume/smart-clone-controller_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2686 [release-v1.54] more targeted cleanup of target/scratch pvcs
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/registry-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  tests/framework/pvc.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#2675 Start integrate golangci lint into CI
  .golangci.yml
  hack/build/run-lint-checks.sh
  hack/build/run-linters.sh
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/clone/auth.go
  pkg/controller/BUILD.bazel
  pkg/controller/clone-controller_test.go
  pkg/controller/config-controller_test.go
  pkg/controller/datavolume/garbagecollect.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util_test.go
  pkg/importer/data-processor_test.go
  pkg/importer/gcs-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/s3-datasource.go
  pkg/importer/s3-datasource_test.go
  pkg/operator/controller/callbacks.go
  pkg/operator/resources/generate/install/strategy.go
  pkg/storagecapabilities/storagecapabilities.go
  pkg/system/prlimit.go
  pkg/util/cert/fetcher/certfetcher.go
  pkg/util/openapi/BUILD.bazel
  pkg/util/openapi/openapi.go
  tests/api_validation_test.go
  tests/badserver_test.go
  tests/datavolume_test.go
  tests/framework/framework.go
  tests/framework/prometheus.go
  tests/imageio-inventory.go
  tests/leaderelection_test.go
  tests/monitoring_test.go
  tests/operator_test.go
  tools/cdi-func-test-file-host-init/main.go
  tools/cdi-func-test-registry-init/main.go
  tools/metricsdocs/metricsdocs.go
Labels: release-note-none, size/XL, dco-signoff: yes, lgtm, approved

#2575 Ensure host assisted concurrent clone test runs on all storages
  tests/cloner_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2691 Enable additional linters to golangci-lint configuration
  .golangci.yml
  cmd/cdi-cloner/clone-source.go
  cmd/cdi-importer/importer.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config_test.go
  pkg/controller/clone-controller_test.go
  pkg/controller/common/util.go
  pkg/controller/config-controller_test.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datasource-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/external-population-controller_test.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/smart-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller_test.go
  pkg/controller/datavolume/upload-controller_test.go
  pkg/controller/datavolume/util_test.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/controller/transfer/controller_test.go
  pkg/controller/upload-controller_test.go
  pkg/feature-gates/feature-gates_test.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/keys/keystore_test.go
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/generate/install/strategy.go
  pkg/system/prlimit_test.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadserver/uploadserver_test.go
  tests/cloner_test.go
  tests/operator_test.go
  tests/rbac_test.go
  tests/transfer_test.go
  tools/util/marshaller.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#2693 [release-v1.49] backport tar handling from #2410
  cmd/cdi-cloner/clone-source.go
  pkg/util/util.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2674 Correctly wait for resourcequota "ready" state in tests
  tests/framework/framework.go
  tests/transfer_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2642 Use `RUNBOOK_URL_TEMPLATE` env for the runbooks URL template
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/prometheus.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#2697 let's start testing 1.26
  automation/ceph-wffc.sh
  automation/ceph.sh
  automation/destructive.sh
  automation/istio.sh
  automation/latest-hpp.sh
  automation/nfs.sh
  automation/previous-hpp.sh
  automation/upgrade.sh
  cluster-sync/ephemeral_provider.sh
  cluster-sync/external-snapshotter/rbac-snapshot-controller.yaml
  cluster-sync/external-snapshotter/setup-snapshot-controller.yaml
  cluster-sync/external-snapshotter/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  cluster-sync/external-snapshotter/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  cluster-sync/external-snapshotter/snapshot.storage.k8s.io_volumesnapshots.yaml
  cluster-sync/external/provider.sh
  cluster-sync/k8s-1.25/provider.sh
  cluster-sync/kubevirtci/provider.sh
  cluster-sync/os-3.11.0-crio/provider.sh
  cluster-sync/rook-ceph/cluster.yaml
  cluster-sync/rook-ceph/common.yaml
  cluster-sync/rook-ceph/operator.yaml
  cluster-sync/rook-ceph/pool.yaml
  cluster-sync/rook-ceph/scc.yaml
  cluster-sync/sync-os-ci.sh
  cluster-sync/sync.sh
  cluster-up/cluster/k8s-1.27/provider.sh
  cluster-up/cluster/kind-1.23/provider.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#2698 Remove embedded reconcile.Reconciler
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/external-population-controller.go
  pkg/controller/datavolume/external-population-controller_test.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2699 remove old generated crds before creating new ones
  hack/update-codegen.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2702 [release-v1.54] backport tar handling from #2410
  cmd/cdi-cloner/clone-source.go
  pkg/util/util.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#2690 Import populator
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/client/clientset/versioned/typed/core/v1beta1/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/BUILD.bazel
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_core_client.go
  pkg/client/clientset/versioned/typed/core/v1beta1/fake/fake_volumeimportsource.go
  pkg/client/clientset/versioned/typed/core/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/core/v1beta1/volumeimportsource.go
  pkg/client/informers/externalversions/core/v1beta1/BUILD.bazel
  pkg/client/informers/externalversions/core/v1beta1/interface.go
  pkg/client/informers/externalversions/core/v1beta1/volumeimportsource.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/core/v1beta1/BUILD.bazel
  pkg/client/listers/core/v1beta1/expansion_generated.go
  pkg/client/listers/core/v1beta1/volumeimportsource.go
  pkg/controller/clone-controller.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/BUILD.bazel
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/populators_suite_test.go
  pkg/controller/populators/util.go
  pkg/controller/transfer/pvc.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/factory.go
  pkg/operator/resources/cluster/populationsources.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/register.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/BUILD.bazel
  tests/framework/pvc.go
  tests/import_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#2701 Add the readahead filter to curl requests
  pkg/image/nbdkit.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, needs-ok-to-test, approved
