Repository kubevirt/containerized-data-importer, pull requests merged in 2024-04, with the labels that each got.

#3156 Double number of e2e parallel nodes from 3 to 6
  hack/build/run-functional-tests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3157 Fix that the Resources configuration
  pkg/controller/import-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3155 Fix volume/access mode inferring for temp host assisted source PVC in snapshot clones
  doc/clone-from-volumesnapshot-source.md
  pkg/controller/clone/planner.go
  pkg/controller/clone/planner_test.go
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3129 Suppress alerts to reduce noise of dependent ones
  pkg/controller/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/monitoring/metrics/cdi-controller/dataimportcron.go
  pkg/monitoring/rules/alerts/operator.go
  tests/monitoring_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3164 Enable misspell linter and fix spelling errors
  .golangci.yml
  cmd/cdi-cloner/clone-source.go
  cmd/cdi-importer/importer.go
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/controller/config-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/snapshot-clone-controller_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/upload-populator_test.go
  pkg/importer/data-processor_test.go
  pkg/importer/imageio-datasource.go
  pkg/importer/util.go
  pkg/importer/vddk-datasource_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/route.go
  tests/cloner_test.go
  tests/imageio-inventory.go
  tests/operator_test.go
  tests/utils/datavolume.go
  tools/cdi-func-test-sample-populator/main.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3163 Stop handling error phase as "unknown" in clone-populator
  pkg/controller/datavolume/clone-controller-base.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3173 [release-v1.58] Fix inferring for temp host assisted source PVC in snapshot clones
  doc/clone-from-volumesnapshot-source.md
  pkg/controller/clone/planner.go
  pkg/controller/clone/planner_test.go
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/util.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3182 [release-v1.57] Fix inferring for temp host assisted source PVC in snapshot clones
  doc/clone-from-volumesnapshot-source.md
  pkg/controller/clone/BUILD.bazel
  pkg/controller/clone/planner.go
  pkg/controller/clone/planner_test.go
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/util.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3183 CVE-2023-45288: Bump golang.org/x/net to v0.23.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/BUILD.bazel
  vendor/golang.org/x/net/http2/databuffer.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go111.go
  vendor/golang.org/x/net/http2/go115.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go111.go
  vendor/golang.org/x/net/http2/not_go115.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables12.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3181 [release-v1.58] Suppress alerts to reduce noise of dependent ones
  pkg/controller/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/storagecapabilities/BUILD.bazel
  pkg/storagecapabilities/storagecapabilities.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/monitoring_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3185 [release-v1.57] Suppress alerts to reduce noise of dependent ones
  pkg/controller/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/storagecapabilities/BUILD.bazel
  pkg/storagecapabilities/storagecapabilities.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
  tests/monitoring_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3191 #3183 follow-up: Move golang.org/x/net dependency from replace to require
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3192 [release-v1.56] Downgrade/upgrade to mirrored rpms to avoid dead mirror 404s
  WORKSPACE
  rpm/BUILD.bazel
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3172 Remove openshift dep on api
  api/openapi-spec/swagger.json
  hack/update-codegen.sh
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/auth-config_test.go
  pkg/controller/upload-controller_test.go
  pkg/operator/resources/crds_generated.go
  pkg/util/tls-crypto-watch/BUILD.bazel
  pkg/util/tls-crypto-watch/tls-crypto-watch.go
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/BUILD.bazel
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_tlssecurityprofile.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/apiserver_test.go
  tests/upload_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3161 Reject DataVolumes and PVCs with storage size smaller than 1MiB
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3171 Enable unconvert linter
  .golangci.yml
  pkg/apiserver/webhooks/populators-validate_test.go
  pkg/controller/clone/prep-claim.go
  pkg/controller/common/util.go
  pkg/controller/config-controller_test.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/upload-populator_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/operator/controller/route.go
  pkg/util/util.go
  pkg/util/util_test.go
  pkg/version/verflag/verflag.go
  tests/cloner_test.go
  tests/external_population_test.go
  tests/framework/framework.go
  tests/framework/nfs-utils.go
  tests/framework/pvc.go
  tests/operator_test.go
  tests/upload_test.go
  tests/utils/datavolume.go
  tests/utils/pod.go
  tests/utils/pv.go
  tests/utils/pvc.go
  tests/webhook_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3174 fix: add rook-ceph upstream provisioner string to unsupported providers
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3177 Enable linters checking error handling
  .golangci.yml
  cmd/cdi-cloner/clone-source.go
  cmd/cdi-cloner/clone-source_test.go
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/controller/common/util.go
  pkg/image/qemu.go
  pkg/importer/data-processor.go
  pkg/importer/format-readers.go
  pkg/importer/imageio-datasource.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/transport.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  tests/certrotation_test.go
  tests/upload_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3186 fix: propagating mesh annotations to transient pods
  pkg/controller/clone-controller.go
  pkg/controller/clone/prep-claim.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/populators/populator-base.go
  pkg/controller/upload-controller.go
  tests/import_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3196 Change clone strategy and cron sources format for LVMS
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3200 [release-v1.56] Backport more targeted cleanup of target/scratch pvcs (#2676)
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/registry-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  tests/framework/pvc.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3176 Enable durationcheck linter
  .golangci.yml
  pkg/controller/dataimportcron-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3194 Add new DV reason: ImagePullFailed
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/BUILD.bazel
  pkg/importer/data-processor.go
  pkg/importer/errors.go
  pkg/importer/gcs-datasource.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/transport.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/util/util.go
  tests/import_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3178 Enable nakedret linter
  .golangci.yml
  cmd/cdi-cloner/clone-source.go
  cmd/openstack-populator/openstack-populator.go
  pkg/controller/clone-controller.go
  pkg/controller/clone/planner.go
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datasource-controller.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/storageprofile-controller.go
  pkg/image/qemu_test.go
  pkg/util/util.go
  tests/upload_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3204 [release-v1.55] Backport more targeted cleanup of target/scratch pvcs (#2676)
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/registry-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver.go
  pkg/util/util.go
  tests/framework/pvc.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3123 Clean up leftover snapshot sources from DataImportCron tests
  pkg/controller/dataimportcron-controller.go
  tests/BUILD.bazel
  tests/dataimportcron_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3198 Update README.md
  README.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3214 [release-1.59] CVE-2023-45288: Bump golang.org/x/net to v0.23.0
  go.mod
  go.sum
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64le.s
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/BUILD.bazel
  vendor/golang.org/x/net/http2/databuffer.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/go111.go
  vendor/golang.org/x/net/http2/go115.go
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go111.go
  vendor/golang.org/x/net/http2/not_go115.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/idna/go118.go
  vendor/golang.org/x/net/idna/idna10.0.0.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/pre_go118.go
  vendor/golang.org/x/net/idna/tables10.0.0.go
  vendor/golang.org/x/net/idna/tables11.0.0.go
  vendor/golang.org/x/net/idna/tables12.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/tables9.0.0.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/golang.org/x/sys/unix/aliases.go
  vendor/golang.org/x/sys/unix/syscall_darwin_libSystem.go
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3215 [release-1.58] Bump golang.org/x/net to 0.23.0 in /staging/src/kubevirt.io/containerized-data-importer-api
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3216 [release-1.57] Bump golang.org/x/net to 0.23.0 in /staging/src/kubevirt.io/containerized-data-importer-api
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3217 [release-1.56] Bump golang.org/x/net to 0.23.0 in /staging/src/kubevirt.io/containerized-data-importer-api
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3218 [release-1.55] Bump golang.org/x/net to 0.23.0 in /staging/src/kubevirt.io/containerized-data-importer-api
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3175 Enable dupword linter
  .golangci.yml
  pkg/controller/clone/snap-clone_test.go
  pkg/controller/populators/util.go
  pkg/controller/upload-controller.go
  pkg/image/qemu_test.go
  pkg/operator/controller/controller_test.go
  tests/framework/pvc.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3205 Add make target to scan for vulnerabilities
  Makefile
  hack/build/run-vulncheck.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3219 Improve http import flow to decide whether to use scratch space or not
  pkg/importer/format-readers.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3209 Set default clone strategy for trident to snapshot
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
