Repository kubevirt/containerized-data-importer, pull requests merged in 2024-06, with the labels that each got.

#3280 forklift: fix race between prime pvc and pod removal
  pkg/controller/populators/forklift-populator.go
  pkg/controller/populators/forklift-populator_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3301 [release-v1.58] Add watch for DataImportCron-labeled PVCs deletion
  pkg/controller/dataimportcron-controller.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3299 Enable usestdlibvars linter
  .golangci.yml
  cmd/cdi-cloner/clone-source.go
  pkg/apiserver/apiserver_test.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/populators/forklift-populator_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource.go
  pkg/uploadproxy/uploadproxy_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  tests/apiserver_test.go
  tests/framework/prometheus.go
  tests/upload_test.go
  tools/cdi-func-test-bad-webserver/main.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3302 [release-v1.57] Add watch for DataImportCron-labeled PVCs deletion
  pkg/controller/dataimportcron-controller.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3252 Make upload client/server certs configurable
  api/openapi-spec/swagger.json
  cmd/cdi-importer/importer.go
  cmd/cdi-uploadserver/BUILD.bazel
  cmd/cdi-uploadserver/uploadserver.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/clone-controller_test.go
  pkg/controller/datavolume/util.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/BUILD.bazel
  pkg/operator/api.go
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/certrotation_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/patches.go
  pkg/operator/resources/cert/BUILD.bazel
  pkg/operator/resources/cert/factory.go
  pkg/operator/resources/crds_generated.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/operator_test.go
  tests/upload_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3303 Revert LVMO storage CSI snapshot clone.
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3295 forklift: rename API group
  doc/cdi-populators.md
  pkg/client/clientset/versioned/typed/forklift/v1beta1/forklift_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/controller/populators/forklift-populator.go
  pkg/controller/populators/forklift-populator_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/register.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/v1beta1/doc.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3294 Add tests AfterEach nil checks
  tests/clone-populator_test.go
  tests/cloner_test.go
  tests/import_test.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3305 [release-v1.59] manual backport of 'forklift: rename API group'
  doc/cdi-populators.md
  pkg/client/clientset/versioned/typed/forklift/v1beta1/forklift_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/controller/populators/forklift-populator.go
  pkg/controller/populators/forklift-populator_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/register.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/forklift/v1beta1/doc.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3272 Add virt default storage class mention in onboarding doc
  doc/onboarding-storage-provisioners.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3297 Document environment variables in Makefile
  Makefile
  hack/README.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3244 Update DataVolume doc references from the 'pvc' API to the 'storage' API
  doc/annotations.md
  doc/blank-raw-image.md
  doc/clone-block-datavolume.md
  doc/clone-datavolume.md
  doc/clone-from-volumesnapshot-source.md
  doc/datavolume-annotations.md
  doc/datavolumes.md
  doc/debug.md
  doc/image-from-registry.md
  doc/import-block-pv.md
  doc/local-storage-selector.md
  doc/preallocation.md
  doc/upload.md
  manifests/example/blank-image-datavolume.yaml
  manifests/example/clone-block-datavolume.yaml
  manifests/example/clone-datavolume.yaml
  manifests/example/import-archive-block-datavolume.yaml
  manifests/example/import-archive-datavolume.yaml
  manifests/example/import-kubevirt-block-datavolume.yaml
  manifests/example/import-kubevirt-datavolume-gcs.yaml
  manifests/example/import-kubevirt-datavolume-secret.yaml
  manifests/example/import-kubevirt-datavolume.yaml
  manifests/example/registry-image-block-datavolume.yaml
  manifests/example/registry-image-datavolume.yaml
  manifests/example/upload-block-datavolume.yaml
  manifests/example/upload-datavolume.yaml
  manifests/templates/upgrade-testing-artifacts.yaml.in
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3308 [release-v1.58] Manual backport of "Use direct io with qemu-img convert if pod is OOMKilled"
  cmd/cdi-importer/importer.go
  hack/build/bazel-docker.sh
  pkg/common/common.go
  pkg/controller/common/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/image/BUILD.bazel
  pkg/image/directio.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3309 [release-v1.57] Manual backport of "Use direct io with qemu-img convert if pod is OOMKilled"
  cmd/cdi-importer/importer.go
  hack/build/bazel-docker.sh
  pkg/common/common.go
  pkg/controller/common/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/image/BUILD.bazel
  pkg/image/directio.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3311 State explicit go version in go.mod files
  go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3307 Make reverse proxy send error messages to klog and to virtctl
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadproxy/uploadproxy_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3317 fix: Make valid labels regex less restrictive
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3322 Prevent a panic in test clean-up
  tests/tests_suite_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3310 Suppress CDIDefaultStorageClassDegraded on SNO
  doc/metrics.md
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/monitoring/metrics/cdi-controller/storageprofile.go
  pkg/monitoring/rules/alerts/operator.go
  pkg/operator/resources/cluster/controller.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3323 [release-v1.58] Backport 'Fix progress reporting for http imports (#3293)'
  pkg/controller/populators/import-populator.go
  pkg/importer/http-datasource.go
  tests/datavolume_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3324 [release-v1.57] Backport 'Fix progress reporting for http imports (#3293)'
  pkg/controller/populators/import-populator.go
  pkg/importer/http-datasource.go
  tests/datavolume_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3284 Add vSphere storagecapabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3325 Update csi-cloning prerequisites
  doc/csi-cloning.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3306 Fix uploadproxy override in cluster-sync
  cluster-sync/sync.sh
  tests/upload_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3249 Fix DELL storagecapabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3321 Update quota.md
  doc/quota.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3314 Expose Upload Proxy certificate in CDI Config status
  api/openapi-spec/swagger.json
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
