Repository kubevirt/containerized-data-importer, pull requests merged in 2024-10, with the labels that each got.

#3451 bug fix nginx arch in BUILD.bazel
  tools/cdi-func-test-file-host-init/BUILD.bazel
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3449 Suppress alerting for kubernetes.io/no-provisioner
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3445 Docs for dataimportcron storage class switching
  doc/datavolumes.md
  doc/os-image-poll-and-update.md
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3454 [release-v1.59] Suppress alerting for kubernetes.io/no-provisioner
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3452 Document device_ownership_from_security_context=true for Containerd v2
  doc/block_cri_ownership_config.md
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3461 Fix uploading for block devices that exceed requested size
  pkg/importer/data-processor.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3468 unit-test, arm64: Add memory limit for prlimit test
  pkg/system/prlimit_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3469 Go to completed phase after apply delta on warm import
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3465 Add default containerPort for cdi-apiserver deployment
  pkg/operator/resources/namespaced/apiserver.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3477 Reduce frequency of SCC management Events
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/scc.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3479 Handle potential nil pointer in handleSnapshot
  pkg/controller/dataimportcron-controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3481 webhooks/datavolume: comment about remove check of claim adoption
  pkg/apiserver/webhooks/datavolume-validate.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3463 Exclude Unsupported Func-Test Images for s390x
  cluster-sync/sync.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3483 [release-v1.58] Fix NBD status coalescing for large blocks
  doc/datavolumes.md
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3488 [release-v1.59] Add Longhorn storagecapabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3494 [release-v1.55] Sync multiple storage capability additions
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3489 cdi-operator updating cdi-apiserver all the time
  pkg/operator/resources/utils/common.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3493 [release-v1.56] Sync multiple storage capability additions
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3491 [release-v1.58] Sync multiple storage capability additions
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3492 [release-v1.57] Sync multiple storage capability additions
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
