Repository kubevirt/containerized-data-importer, pull requests merged in 2024-08, with the labels that each got.

#3360 pkg/importer: Increase number of nbdkit lines logged
  pkg/importer/vddk-datasource_amd64.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3366 Allow dataimportcron snap->pvc automatic source switch
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3349 s390x Unit Test Enablement
  pkg/system/prlimit_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3019 Create build-the-builder.md
  doc/build-the-builder.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, needs-ok-to-test, approved

#3379 Remove ginkgo CLI dep from builder
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3380 Inject cdi-uploadproxy CA cert into user created routes
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/route.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3361 nbdkit datapath debug
  pkg/image/nbdkit.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3383 Fix build-builder script
  hack/build/bazel-build-builder.sh
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3290 Add Longhorn storagecapabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3371 Add s390x support for cdi builder for unit tests
  cluster-up/cluster/kind/common.sh
  hack/build/bazel-build-builder.sh
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3381 feat(DataVolume): Add default instance type labels from VolumeSnapshots and from Registry imports
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
  tests/BUILD.bazel
  tests/datavolume_test.go
  tools/cdi-func-test-registry-init/populate-registry.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3352 Properly handle DataVolume preallocation setting for all host assisted (copy) clones
  pkg/uploadserver/uploadserver.go
  pkg/util/BUILD.bazel
  pkg/util/file.go
  pkg/util/file_test.go
  pkg/util/util.go
  pkg/util/util_test.go
  tests/cloner_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3363 nbdkit: Use password=+temporary to send passwords securely
  pkg/image/nbdkit.go
  pkg/importer/http-datasource.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3377 feat: Copy labels from source to DataSource
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datasource-controller.go
  pkg/controller/datasource-controller_test.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/populator-base.go
  tests/dataimportcron_test.go
  tests/datasource_test.go
  tests/utils/populators.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3378 Setup ginkgo cli build properly to avoid double dep
  BUILD.bazel
  Makefile
  hack/build/build-functest.sh
  hack/build/build-ginkgo.sh
  hack/build/config.sh
  hack/ci/build-functest.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3387 Retry pulling builder image
  hack/build/bazel-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3389 apidocs: remove gradle dep (builder)
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3390 apidocs: remove gradle dep (gen-swagger-docs.sh)
  hack/build/config.sh
  hack/gen-swagger-doc/build.gradle
  hack/gen-swagger-doc/gen-swagger-docs.sh
  hack/gen-swagger-doc/gradle.properties
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3392 Fix ginkgo build script that breaks postsubmits
  hack/build/build-ginkgo.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3399 [release-v1.58] Manual backport for VDDK related PRs 3361, 3363, 3385
  pkg/image/nbdkit.go
  pkg/importer/http-datasource.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  tools/vddk-test/vddk-test-plugin.c
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3385 VDDK: pass snapshot ID through to nbdkit.
  pkg/image/nbdkit.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  tools/vddk-test/vddk-test-plugin.c
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3404 [release-v1.59] remove gradle dep when running gen-swagger-docs.sh
  hack/build/config.sh
  hack/gen-swagger-doc/build.gradle
  hack/gen-swagger-doc/gen-swagger-docs.sh
  hack/gen-swagger-doc/gradle.properties
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3391 fix: mismatched type (stat.Bsize to int64)
  pkg/util/file.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3405 Run make rpm-deps to udpate dependencies for all arches
  WORKSPACE
  hack/build/rpm-deps.sh
  rpm/BUILD.bazel
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3362 Fix PVC deletion logic in populators
  pkg/controller/clone/csi-clone_test.go
  pkg/controller/clone/planner_test.go
  pkg/controller/clone/prep-claim.go
  pkg/controller/clone/prep-claim_test.go
  pkg/controller/clone/rebind_test.go
  pkg/controller/clone/snap-clone_test.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/static-volume_test.go
  pkg/controller/populators/forklift-populator_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator_test.go
  pkg/controller/transfer/pvc.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3408 [release-v1.59] Inject cdi-uploadproxy CA cert into user created routes
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/route.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3409 Update README.md
  rpm/README.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3382 cross-compile docker builder for s390x
  hack/build/docker/builder/Dockerfile
  hack/build/docker/builder/output-bazel-arch.sh
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3410 Remove git diff, refine plattform check for multiarch builder
  hack/build/bazel-build-builder.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3388 fix(import-populator): Make copying of annotations more robust
  pkg/controller/populators/import-populator.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3414 builder: Update to latest builder version which includes s390x image
  hack/build/config.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3357 s390x enablement WIP
  .bazelrc
  WORKSPACE
  bazel/toolchain/s390x-none-linux-gnu/BUILD
  bazel/toolchain/s390x-none-linux-gnu/cc_toolchain_config.bzl
  bazel/toolchain/toolchain.bzl
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-cloner/BUILD.bazel
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-importer/BUILD.bazel
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-uploadproxy/BUILD.bazel
  cmd/cdi-uploadserver/BUILD.bazel
  hack/build/rpm-deps.sh
  hack/build/run-linters.sh
  pkg/importer/BUILD.bazel
  pkg/importer/vddk-datasource_s390x.go
  tools/cdi-func-test-bad-webserver/BUILD.bazel
  tools/cdi-func-test-file-host-init/BUILD.bazel
  tools/cdi-func-test-proxy/BUILD.bazel
  tools/cdi-func-test-registry-init/BUILD.bazel
  tools/cdi-func-test-sample-populator/BUILD.bazel
  tools/vddk-init/BUILD.bazel
  tools/vddk-test/BUILD.bazel
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
