Repository kubevirt/containerized-data-importer, pull requests merged in 2024-01, with the labels that each got.

#3041 [release-v1.57] Add new Prometheus alerts and label existing alerts
  automation/test.sh
  cmd/cdi-controller/controller.go
  doc/metrics.md
  pkg/controller/common/util.go
  pkg/controller/dataimportcron-conditions.go
  pkg/controller/dataimportcron-controller.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/controller-base.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/monitoring/metrics.go
  pkg/operator/controller/prometheus.go
  tests/framework/framework.go
  tests/import_test.go
  tests/manifests/snapshot/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  tests/manifests/snapshot/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  tests/manifests/snapshot/snapshot.storage.k8s.io_volumesnapshots.yaml
  tests/monitoring_test.go
  tests/utils/common.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3050 Add Trident RWO Filesystem capability
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3057 Fix DataImportCron PVC GC race and test flakiness
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3059 add annotation to PVCs when DVs are garbage collected
  pkg/controller/common/util.go
  pkg/controller/datavolume/garbagecollect.go
  pkg/controller/datavolume/import-controller_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3065 forklift: remove ovirt-populator
  cmd/cdi-importer/BUILD.bazel
  cmd/ovirt-populator/BUILD.bazel
  cmd/ovirt-populator/ovirt-populator.go
  hack/build/rpm-deps.sh
  repo.yaml
Labels: release-note, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#3063 [release-v1.58] Fix DataImportCron PVC GC race and test flakiness
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3064 [release-v1.57] Fix DataImportCron PVC GC race and test flakiness
  pkg/controller/dataimportcron-controller.go
  tests/dataimportcron_test.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3067 Make rpm-deps following #3065
  WORKSPACE
  rpm/BUILD.bazel
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3056 Fix populators not repopulating pvc after it was deleted
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  tests/cloner_test.go
  tests/import_test.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3029 Feature Gate and annotation for PVCs to be "adopted" by DataVolumes
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/feature-gates/feature-gates.go
  pkg/feature-gates/feature-gates_test.go
  pkg/operator/resources/cluster/apiserver.go
  tests/BUILD.bazel
  tests/adopt-volume_test.go
  tests/framework/pvc.go
  tests/upload_test.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#3039 Stop skipping advanced clone method tests with immediate bind annotation
  tests/cloner_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3027 Docs for default virt storage class
  doc/datavolumes.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3073 [release-v1.57] Fix populators not repopulating pvc
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  tests/cloner_test.go
  tests/import_test.go
  tests/utils/datavolume.go
  tests/utils/pvc.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3072 Fix DataImportCron import DataVolume creation when last import is not found
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3081 Change CDI webhook failure policy to Ignore
  pkg/operator/resources/cluster/apiserver.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3083 Update builder to use golang 1.21.5
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3080 Allow Deployed CDI to get out of Error Phase
  pkg/controller/common/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/operator/controller/cr-manager.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3084 Bump builder, switch to go 1.21
  WORKSPACE
  go.mod
  go.sum
  hack/build/config.sh
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.sum
  vendor/modules.txt
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3088 Remove deprecated insecure registries config map from user's install
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cruft.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3070 Introduce customizeComponents option
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/common/common.go
  pkg/controller/common/util.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/cr-manager.go
  pkg/operator/controller/patches.go
  pkg/operator/controller/patches_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/cluster/cronjob.go
  pkg/operator/resources/cluster/uploadproxy.go
  pkg/operator/resources/crds_generated.go
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/cronjob.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/utils/common.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/zz_generated.deepcopy.go
  tests/operator_test.go
  vendor/github.com/evanphx/json-patch/v5/BUILD.bazel
  vendor/github.com/evanphx/json-patch/v5/internal/json/BUILD.bazel
  vendor/github.com/evanphx/json-patch/v5/internal/json/decode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/encode.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fold.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/fuzz.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/indent.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/scanner.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/stream.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tables.go
  vendor/github.com/evanphx/json-patch/v5/internal/json/tags.go
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, ok-to-test, approved

#3085 Update portworx csi to have CSI-clone clone strategy
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3094 Add missing RBAC for identifying if were running on OpenShift
  pkg/operator/resources/cluster/controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
