Repository kubevirt/containerized-data-importer, pull requests merged in 2024-11, with the labels that each got.

#3495 Bump Minio Version
  manifests/templates/file-host.yaml.in
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3500 Populators: Add to PVC' exclude velero backup annotation
  pkg/controller/clone/csi-clone.go
  pkg/controller/clone/csi-clone_test.go
  pkg/controller/clone/host-clone.go
  pkg/controller/clone/host-clone_test.go
  pkg/controller/clone/snap-clone.go
  pkg/controller/clone/snap-clone_test.go
  pkg/controller/common/util.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3496 Standardize setting go.mod to minor
  go.mod
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  vendor/modules.txt
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3509 Add the "latest" endpoint for the nightly manifest
  automation/prow_periodic_push.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3510 [release-v1.57] Backport 3242 VDDK: Fix NBD status coalescing for large blocks.
  doc/datavolumes.md
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3508 [release-v1.57] Prepare branch for releasing; apidocs/go binary freezes
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3516 Limit secret caching to CDI namespace
  cmd/cdi-controller/controller.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3514 [release-v1.57] Prepare branch for releasing, follow up builder changes
  hack/build/config.sh
  hack/gen-swagger-doc/build.gradle
  hack/gen-swagger-doc/gen-swagger-docs.sh
  hack/gen-swagger-doc/gradle.properties
  pkg/operator/resources/crds_generated.go
  pkg/system/prlimit_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3521 Fix the location of the nightly commit file
  automation/prow_periodic_push.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3522 Populators: Add to PVC' exclude velero backup label
  pkg/controller/clone/csi-clone.go
  pkg/controller/clone/csi-clone_test.go
  pkg/controller/clone/host-clone.go
  pkg/controller/clone/host-clone_test.go
  pkg/controller/clone/snap-clone.go
  pkg/controller/clone/snap-clone_test.go
  pkg/controller/common/util.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3538 [release-v1.59] Manual cherry pick of CNV-51521 fix
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved, priority/critical-urgent

#3535 [release-v1.58] Manual cherry pick of CNV-51521 fix
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved, priority/critical-urgent

#3536 cdi-uploadserver: healthcheck and application use same port
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3541 [release-v1.60] Manual cherry pick of CNV-51521 fix
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3534 CNV-51521 | Fix Incomplete transfer of change blocks leads to data corruption
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved, priority/critical-urgent
