Repository kubevirt/containerized-data-importer, pull requests merged in 2024-03, with the labels that each got.

#3106 Watch DIC-orphan cronjobs and cleanup them
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/namespaced/controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3076 [release-v1.58] Feature Gate and annotation for PVCs to be "adopted" by DataVolumes
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  pkg/apiserver/BUILD.bazel
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth-config_test.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/apiserver/webhooks/handler.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/feature-gates/feature-gates.go
  pkg/feature-gates/feature-gates_test.go
  pkg/operator/resources/cluster/apiserver.go
  tests/BUILD.bazel
  tests/adopt-volume_test.go
  tests/framework/pvc.go
  tests/upload_test.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#3077 [release-v1.58] add annotation cdi.kubevirt.io/garbageCollected to PVCs when DVs are garbage collected
  pkg/controller/common/util.go
  pkg/controller/datavolume/garbagecollect.go
  pkg/controller/datavolume/import-controller_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3120 [release-v1.58] Watch DIC-orphan cronjobs and cleanup them
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/namespaced/controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3121 [release-v1.57] Watch DIC-orphan cronjobs and cleanup them
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/resources/namespaced/controller.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3079 [release-v1.58] Fix DIC DV creation when last import is not found
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3099 [release-v1.58] Fix StorageProfile ClaimPropertySets validation
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3124 Rename PVC webhook rendering label to "applyStorageProfile"
  doc/pvc-mutating-webhook-rendering.md
  pkg/apiserver/webhooks/pvc-mutate.go
  pkg/common/common.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/util.go
  pkg/operator/controller/callbacks.go
  tests/clone-populator_test.go
  tests/datavolume_test.go
  tests/import_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3127 Replace cron expression library with one used in kubernetes
  go.mod
  go.sum
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/dataimportcron-validate.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  vendor/github.com/gorhill/cronexpr/APLv2
  vendor/github.com/gorhill/cronexpr/BUILD.bazel
  vendor/github.com/gorhill/cronexpr/GPLv3
  vendor/github.com/gorhill/cronexpr/README.md
  vendor/github.com/gorhill/cronexpr/cronexpr.go
  vendor/github.com/gorhill/cronexpr/cronexpr_next.go
  vendor/github.com/gorhill/cronexpr/cronexpr_parse.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/BUILD.bazel
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3116 Avoid race condition during importer termination
  cmd/cdi-importer/importer.go
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  tests/datavolume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3101 feat: Make importer datasource communication explicit
  cmd/cdi-importer/BUILD.bazel
  cmd/cdi-importer/importer.go
  pkg/common/BUILD.bazel
  pkg/common/common.go
  pkg/common/common_suite_test.go
  pkg/common/common_test.go
  pkg/controller/clone-controller.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/upload-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/importer/gcs-datasource.go
  pkg/importer/http-datasource.go
  pkg/importer/imageio-datasource.go
  pkg/importer/registry-datasource.go
  pkg/importer/s3-datasource.go
  pkg/importer/upload-datasource.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_arm64.go
  pkg/importer/vddk-datasource_test.go
  pkg/uploadserver/uploadserver_test.go
  pkg/util/util.go
  tests/datavolume_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3128 Get all no-provisioner storage capabilities from PVs
  pkg/controller/BUILD.bazel
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/storagecapabilities/BUILD.bazel
  pkg/storagecapabilities/storagecapabilities.go
  tests/framework/BUILD.bazel
  tests/framework/framework.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3133 Add missing import in pkg/importer/vddk-datasource_arm64.go
  pkg/importer/vddk-datasource_arm64.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3135 Add polarion rfes and ids to webhook rendering
  tests/clone-populator_test.go
  tests/datavolume_test.go
  tests/import_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3126 Improve handling of unpopulated capacity field in clone populator
  pkg/controller/clone/prep-claim.go
  pkg/controller/clone/prep-claim_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3136 cdi.kubevirt.io/allowClaimAdoption annotation breaking "regular" operations
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3140 Add HPE RWX/Block capability
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3142 [release-v1.55] Escape user-controlled strings in uploadproxy to avoid XSS attacks
  pkg/uploadproxy/uploadproxy.go
  tests/upload_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3143 [release-v1.58] cdi.kubevirt.io/allowClaimAdoption annotation breaking "regular" operations
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/upload-controller.go
  pkg/controller/datavolume/upload-controller_test.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3103 feat(import): Set PVC labels derived from env vars on containerdisks
  pkg/common/common.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator.go
  pkg/controller/populators/upload-populator_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/importer/BUILD.bazel
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/registry-datasource.go
  pkg/importer/registry-datasource_test.go
  pkg/importer/transport.go
  pkg/importer/transport_test.go
  pkg/importer/util.go
  pkg/importer/util_test.go
  tests/BUILD.bazel
  tests/import_test.go
  tools/cdi-containerimage-server/BUILD.bazel
  tools/cdi-containerimage-server/main.go
  tools/cdi-func-test-registry-init/populate-registry.sh
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#3118 Improve readability of importer pod's creation code
  pkg/controller/import-controller.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3141 [release-v1.56] Escape user-controlled strings in uploadproxy to avoid XSS attacks
  pkg/uploadproxy/uploadproxy.go
  tests/upload_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3152 [release-v1.49] Add HPE RWX/Block capability
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3023 Update kubevirtci, 1.29 lanes
  automation/ceph-wffc.sh
  automation/ceph.sh
  automation/destructive.sh
  automation/istio.sh
  automation/latest-hpp.sh
  automation/nfs.sh
  automation/non-csi-hpp.sh
  automation/previous-hpp.sh
  automation/upgrade.sh
  cluster-sync/ephemeral_provider.sh
  cluster-sync/sync.sh
  cluster-up/README.md
  cluster-up/cluster/README_VGPU.md
  cluster-up/cluster/k8s-1.29/provider.sh
  cluster-up/cluster/k8s-1.30/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.27-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.27-vgpu/image
  cluster-up/cluster/kind-1.27-vgpu/provider.sh
  cluster-up/cluster/kind-1.27-vgpu/version
  cluster-up/cluster/kind-1.27/README.md
  cluster-up/cluster/kind-1.27/provider.sh
  cluster-up/cluster/kind-1.28/README.md
  cluster-up/cluster/kind-1.28/image
  cluster-up/cluster/kind-1.28/provider.sh
  cluster-up/cluster/kind-1.28/version
  cluster-up/cluster/kind-sriov/OWNERS
  cluster-up/cluster/kind-sriov/README.md
  cluster-up/cluster/kind-sriov/TROUBLESHOOTING.md
  cluster-up/cluster/kind-sriov/config_sriov_cluster.sh
  cluster-up/cluster/kind-sriov/conformance.json
  cluster-up/cluster/kind-sriov/image
  cluster-up/cluster/kind-sriov/provider.sh
  cluster-up/cluster/kind-sriov/sriov-components/manifests/kustomization.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/multus/kustomization.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/multus/multus.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/multus/patch-args.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/patch-node-selector.yaml.in
  cluster-up/cluster/kind-sriov/sriov-components/manifests/patch-sriovdp-resource-prefix.yaml.in
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriov-cni-daemonset.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriov-ns.yaml
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriovdp-config.yaml.in
  cluster-up/cluster/kind-sriov/sriov-components/manifests/sriovdp-daemonset.yaml
  cluster-up/cluster/kind-sriov/sriov-components/sriov_components.sh
  cluster-up/cluster/kind-sriov/sriov-node/configure_vfs.sh
  cluster-up/cluster/kind-sriov/sriov-node/node.sh
  cluster-up/cluster/kind-sriov/sriovdp_setup.sh
  cluster-up/cluster/kind-sriov/version
  cluster-up/cluster/kind/bump-kind.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/cluster/local/README.md
  cluster-up/cluster/local/provider.sh
  cluster-up/hack/common.sh
  hack/update-kubevirtci.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3151 Fix linter warnings and clean-up upload controller
  pkg/controller/upload-controller.go
  pkg/controller/upload-controller_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3097 Add goimports to golangci linters
  .golangci.yml
  pkg/importer/imageio-datasource_test.go
  pkg/operator/controller/patches_test.go
  tests/operator_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3147 cleanup: Return modified labels added from termination message
  pkg/controller/import-controller.go
  pkg/controller/util.go
  pkg/controller/util_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3153 docs: Add docs for containerdisk labels
  doc/image-from-registry.md
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
