Repository kubevirt/containerized-data-importer, pull requests merged in 2024-02, with the labels that each got.

#3093 Allow ReadWriteOncePod DVs
  pkg/apiserver/webhooks/datavolume-validate.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/external_population_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3090 Create rpm/README.md
  rpm/README.md
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, ok-to-test, approved

#3082 [release-v1.57] Fix DIC DV creation when last import is not found
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/controller/datavolume/controller-base.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3096 Fix StorageProfile ClaimPropertySets validation
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/storageprofile-controller.go
  pkg/controller/storageprofile-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2813 Add PVC spec mutating webhook rendering based on StorageProfiles
  api/openapi-spec/swagger.json
  cmd/cdi-apiserver/BUILD.bazel
  cmd/cdi-apiserver/apiserver.go
  doc/cdi-populators.md
  doc/pvc-mutating-webhook-rendering.md
  doc/storageprofile.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/handler.go
  pkg/apiserver/webhooks/pvc-mutate.go
  pkg/common/common.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/util.go
  pkg/controller/datavolume/util_test.go
  pkg/controller/import-controller_test.go
  pkg/feature-gates/feature-gates.go
  pkg/operator/controller/BUILD.bazel
  pkg/operator/controller/callbacks.go
  pkg/operator/resources/cluster/apiserver.go
  pkg/operator/resources/operator/operator.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  tests/BUILD.bazel
  tests/clone-populator_test.go
  tests/datavolume_test.go
  tests/import_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3112 [release-v1.55] Allow Deployed CDI to get out of Error Phase
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/operator/controller/cr-manager.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3113 [release-v1.56] Add mirror for systemd related RPMs
  WORKSPACE
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3115 Add storage capabilities for minikube's hostpath provider
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3111 [release-v1.56] Allow Deployed CDI to get out of Error Phase
  WORKSPACE
  pkg/controller/common/BUILD.bazel
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/operator/controller/cr-manager.go
  rpm/BUILD.bazel
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3105 Check cdi.kubevirt.io/allowClaimAdoption on DataVolume rather than PVC
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/upload-controller_test.go
  tests/adopt-volume_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
