Repository kubevirt/containerized-data-importer, pull requests merged in 2024-12, with the labels that each got.

#3350 add IBM Block Storage CSI driver support for RWX
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3547 Watch for StorageProfile updates to reconcile DataVolumes
  pkg/controller/datavolume/controller-base.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3552 Deprecate DataVolume garbage collection
  api/openapi-spec/swagger.json
  doc/cdi-config.md
  doc/datavolumes.md
  manifests/templates/upgrade-testing-artifacts.yaml.in
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-mutate.go
  pkg/apiserver/webhooks/datavolume-mutate_test.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/BUILD.bazel
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/garbagecollect.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/BUILD.bazel
  tests/adopt-volume_test.go
  tests/cloner_test.go
  tests/dataimportcron_test.go
  tests/datavolume_test.go
  tests/external_population_test.go
  tests/import_test.go
  tests/operator_test.go
  tests/static-volume_test.go
  tests/transfer_test.go
  tests/upload_test.go
  tests/utils/datavolume.go
Labels: release-note, size/XL, dco-signoff: yes, lgtm, approved

#3554 Correct typo in deprecation note for ObjectTransfer
  pkg/operator/resources/cluster/object-transfer.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3544 Fix PVC webhook rendering segfault
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/pvc-mutate_test.go
  pkg/controller/datavolume/util.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3560 Make deps update over apiserver change
  pkg/apiserver/webhooks/BUILD.bazel
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3564 CWE-79 small tightening up
  pkg/uploadproxy/uploadproxy.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3553 Move size detection pod deletion to cleanup
  automation/test.sh
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3565 Add vddk label to a func test
  tests/import_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3571 [release-v1.61] Manual backport "Move size detection pod deletion to cleanup"
  automation/test.sh
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3555 Update kubevirtci, 1.31 lanes
  automation/ceph-wffc.sh
  automation/ceph.sh
  automation/destructive.sh
  automation/istio.sh
  automation/latest-hpp.sh
  automation/nfs.sh
  automation/non-csi-hpp.sh
  automation/previous-hpp.sh
  automation/upgrade.sh
  cluster-sync/ephemeral_provider.sh
  cluster-up/check.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/external/provider.sh
  cluster-up/cluster/k8s-1.32/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/kind-1.27-vgpu/config_vgpu_cluster.sh
  cluster-up/cluster/kind-1.27-vgpu/image
  cluster-up/cluster/kind-1.27-vgpu/provider.sh
  cluster-up/cluster/kind-1.27-vgpu/version
  cluster-up/cluster/kind-1.27-vgpu/vgpu-node/node.sh
  cluster-up/cluster/kind-1.28/conformance.json
  cluster-up/cluster/kind-1.28/provider.sh
  cluster-up/cluster/kind-1.30-vgpu/provider.sh
  cluster-up/cluster/kind-ovn/provider.sh
  cluster-up/cluster/kind-sriov/OWNERS
  cluster-up/cluster/kind-sriov/image
  cluster-up/cluster/kind-sriov/provider.sh
  cluster-up/cluster/kind-sriov/version
  cluster-up/cluster/kind/check-cluster-up.sh
  cluster-up/cluster/kind/common.sh
  cluster-up/hack/common.sh
  cluster-up/virtctl.sh
  hack/update-kubevirtci.sh
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved
