Repository kubevirt/containerized-data-importer, pull requests merged in 2024-09, with the labels that each got.

#3413 Replace corev1 with k8sv1 in utils/datavolume.go
  tests/utils/datavolume.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3403 Make bazel binary world executable
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3347 Bump rpms to fix concurrent host-assisted clone tar failure on file change during read
  WORKSPACE
  rpm/BUILD.bazel
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3384 Ensure scratch space is large enough to hold disk image
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/util/util.go
  tests/cloner_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3422 [release-v1.59] Ensure scratch space is large enough to hold disk image
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/util/util.go
  tests/cloner_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3353 Handle storage class changes automatically in cron controller
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3419 Bump builder to latest
  hack/build/config.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3418 Deprecate ObjectTransfer feature
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/apiserver/webhooks/transfer-validate.go
  pkg/apiserver/webhooks/transfer-validate_test.go
  pkg/operator/resources/cluster/BUILD.bazel
  pkg/operator/resources/cluster/object-transfer.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_transfer.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3424 define container bundles for s390x test images that omit tests for features unsupported in s390x
  BUILD.bazel
  Makefile
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3427 [release-v1.60] Bump builder
  hack/build/config.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3406 feat: Set default host architecture in makefile
  Makefile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3431 Run unit-tests without bazel
  Makefile
  hack/build/in-docker.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3428 Add s390x and native BUILD_ARCH in periodic automation
  automation/prow_periodic_push.sh
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3438 [release-v1.58] Freeze some go tool versions in corresponding builder
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3432 [release-v1.58] Ensure scratch space is large enough to hold disk image
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/controller/storageprofile-controller_test.go
  pkg/controller/util.go
  pkg/controller/util_test.go
  pkg/image/nbdkit.go
  pkg/util/util.go
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3439 [release-v1.58] remove gradle dep when running gen-swagger-docs.sh
  hack/build/config.sh
  hack/gen-swagger-doc/build.gradle
  hack/gen-swagger-doc/gen-swagger-docs.sh
  hack/gen-swagger-doc/gradle.properties
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3447 [release-v1.59] Bump tar rpm to fix concurrent host-assisted clone failure
  WORKSPACE
  rpm/BUILD.bazel
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3448 [release-v1.60] Bump tar rpm to fix concurrent host-assisted clone failure
  WORKSPACE
  rpm/BUILD.bazel
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
