Repository kubevirt/containerized-data-importer, pull requests merged in 2024-07, with the labels that each got.

#3253 Add Huawei storagecapabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3337 Move and extend functional test focus flag
  automation/test.sh
  hack/README.md
  hack/build/run-functional-tests.sh
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3333 Fix qemu O_DIRECT refusing unit tests
  hack/build/bazel-docker.sh
  pkg/image/directio.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3339 Make restart count test serial
  tests/import_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3278 [release-v1.59] Update docker/docker to v25.0.5
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3342 Flaky certrotation tests
  pkg/operator/controller/certrotation.go
  pkg/operator/controller/certrotation_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3345 [release-v1.59] Sync multiple storage capability additions
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3346 Add KubeSAN capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3351 Fix runbook_url test
  tests/monitoring_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3348 Fix race condition in multi-stage import logic
  pkg/controller/common/checkpoint-util.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3331 Remove datavolume clone source validation
  pkg/apiserver/webhooks/BUILD.bazel
  pkg/apiserver/webhooks/datavolume-validate.go
  pkg/apiserver/webhooks/datavolume-validate_test.go
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  pkg/controller/datavolume/snapshot-clone-controller_test.go
  pkg/controller/util_test.go
  tests/cloner_test.go
  tests/datasource_test.go
Labels: release-note, size/XXL, dco-signoff: yes, lgtm, approved

#3354 updating documentation to reflect the ability to use the upload source and the archive contentType as a valid combination
  README.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
