Repository kubevirt/containerized-data-importer, pull requests merged in 2024-05, with the labels that each got.

#3228 [release-v1.58] Backport profile tunings for several provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3232 CDIStorageProfilesIncomplete should not impact operator health
  pkg/monitoring/rules/alerts/operator.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3229 [release-v1.57] Backport profile tunings for several provisioners
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3234 [release-v1.58] Fix backport PR #3181 alerts expression
  pkg/operator/controller/prometheus.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3230 [release-v1.58] Manual backport of improve http import flow to decide whether to use scratch space or not
  pkg/importer/format-readers.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  tests/import_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3221 Claim Adoption Doc
  doc/datavolume-claim-adoption.md
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3231 [release-v1.57] Manual backport of improve http import flow to decide whether to use scratch space or not
  pkg/importer/format-readers.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  tests/import_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3233 [release-v1.57] Fix backport PR #3185 alerts expression
  pkg/operator/controller/prometheus.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3238 [release-v1.56] CDIStorageProfilesIncomplete should not impact operator health
  pkg/operator/controller/prometheus.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3239 [release-v1.55] Add unsupported provisioners for OCS bucket and Stork snapshot
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3236 [release-v1.58] CDIStorageProfilesIncomplete should not impact operator health
  pkg/operator/controller/prometheus.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3237 [release-v1.57] CDIStorageProfilesIncomplete should not impact operator health
  pkg/operator/controller/prometheus.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3235 [release-v1.59] CDIStorageProfilesIncomplete should not impact operator health
  pkg/monitoring/rules/alerts/operator.go
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3197 Fix goveralls coverage reporting
  .github/workflows/coverall.yml
  Makefile
  hack/build/coverage.sh
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3245 Fix cluster-sync wait_cdi_crd_installed timeout check
  cluster-sync/install.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3246 Update builder to use golang 1.22.3
  hack/build/docker/builder/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3193 Improve usability of Golangci-lint
  .golangci.yml
  hack/README.md
  hack/build/bazel-build-builder.sh
  hack/build/bazel-docker.sh
  hack/build/bazel-generate.sh
  hack/build/build-go.sh
  hack/build/common.sh
  hack/build/docker/builder/Dockerfile
  hack/build/format.sh
  hack/build/rpm-deps.sh
  hack/build/run-lint-checks.sh
  hack/build/run-linters.sh
  hack/ci/prom_metric_linter.sh
  hack/common-funcs.sh
  hack/fossa.sh
  pkg/importer/vddk-datasource_arm64.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3242 VDDK: Fix NBD status coalescing for large blocks.
  doc/datavolumes.md
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3251 Update bazel-build-builder.sh
  hack/build/bazel-build-builder.sh
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3256 Fix flaky DataImportCron controller reconcile loop unit test
  pkg/controller/dataimportcron-controller.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3017 Use direct io with qemu-img convert if pod is OOMKilled
  cmd/cdi-importer/importer.go
  hack/build/bazel-docker.sh
  pkg/common/common.go
  pkg/controller/common/util.go
  pkg/controller/import-controller.go
  pkg/controller/import-controller_test.go
  pkg/image/BUILD.bazel
  pkg/image/directio.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/data-processor.go
  pkg/importer/data-processor_test.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3266 Make generate following new builder bump
  pkg/operator/resources/crds_generated.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3268 Filter out generated files from coverage report
  hack/build/run-unit-tests.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3225 Apply monitoring linters
  go.mod
  go.sum
  hack/build/run-linters.sh
  pkg/monitoring/rules/BUILD.bazel
  pkg/monitoring/rules/rules_suite_test.go
  pkg/monitoring/rules/rules_test.go
  vendor/github.com/grafana/regexp/.gitignore
  vendor/github.com/grafana/regexp/BUILD.bazel
  vendor/github.com/grafana/regexp/LICENSE
  vendor/github.com/grafana/regexp/README.md
  vendor/github.com/grafana/regexp/backtrack.go
  vendor/github.com/grafana/regexp/exec.go
  vendor/github.com/grafana/regexp/onepass.go
  vendor/github.com/grafana/regexp/regexp.go
  vendor/github.com/machadovilaca/operator-observability/pkg/docs/metrics.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/BUILD.bazel
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
  vendor/modules.txt
Labels: release-note-none, size/XXL, dco-signoff: yes, lgtm, approved

#3271 Onboard Infinibox CSI driver
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3277 [release-v1.55] Onboard Infinibox CSI driver
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3276 [release-v1.56] Onboard Infinibox CSI driver
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3263 tests: correct check for containerdisk env vars eventually appearing
  tests/import_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3241 Enable revive linter
  .golangci.yml
  hack/build/bazel-build-builder.sh
  hack/update-codegen.sh
  pkg/apiserver/apiserver.go
  pkg/controller/common/util.go
  pkg/controller/config-controller.go
  pkg/controller/config-controller_test.go
  pkg/controller/import-controller.go
  pkg/image/qemu.go
  pkg/image/qemu_test.go
  pkg/importer/imageio-datasource.go
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
  pkg/system/prlimit_test.go
  tests/apiserver_test.go
  tests/cdiconfig_test.go
  tests/framework/framework.go
  tests/monitoring_test.go
  tests/operator_test.go
  tools/cdi-func-test-bad-webserver/main.go
  tools/cdi-func-test-proxy/main.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3285 Add watch for DataImportCron-labeled PVCs deletion
  pkg/controller/dataimportcron-controller.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3286 s390x rpm support
  .bazelrc
  hack/build/rpm-deps.sh
  repo.yaml
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3282 Update makefile documentation
  Makefile
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3283 Enable Gosec linter
  .golangci.yml
  Makefile
  cmd/cdi-cloner/clone-source.go
  cmd/openstack-populator/openstack-populator.go
  cmd/openstack-populator/openstack-populator_test.go
  hack/build/docker/builder/Dockerfile
  hack/build/gosec.sh
  hack/build/rpm-deps.sh
  hack/build/run-unit-tests.sh
  pkg/apiserver/apiserver.go
  pkg/common/common.go
  pkg/controller/clone-controller.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/controller/populators/forklift-populator_test.go
  pkg/controller/populators/import-populator_test.go
  pkg/controller/util.go
  pkg/importer/http-datasource.go
  pkg/importer/http-datasource_test.go
  pkg/importer/imageio-datasource_test.go
  pkg/importer/transport.go
  pkg/importer/vddk-datasource_test.go
  pkg/operator/controller/patches.go
  pkg/system/prlimit_test.go
  pkg/uploadproxy/uploadproxy.go
  pkg/uploadserver/uploadserver.go
  pkg/uploadserver/uploadserver_test.go
  pkg/util/cert/cert.go
  pkg/util/prometheus/prometheus.go
  pkg/util/util.go
  tests/api_validation_test.go
  tests/apiserver_test.go
  tests/certrotation_test.go
  tests/external_population_test.go
  tests/framework/prometheus.go
  tests/import_test.go
  tests/transport_test.go
  tests/upload_test.go
  tests/utils/certs.go
  tools/cdi-containerimage-server/main.go
  tools/cdi-func-test-bad-webserver/main.go
  tools/cdi-func-test-proxy/main.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved

#3184 Reduce amount of logs fetched by tests that assert on control plane pod logs
  tests/api_validation_test.go
  tests/badserver_test.go
  tests/cloner_test.go
  tests/datavolume_test.go
  tests/framework/pod.go
  tests/import_proxy_test.go
  tests/import_test.go
  tests/operator_test.go
  tests/smartclone_test.go
  tests/upload_test.go
Labels: release-note-none, size/L, dco-signoff: yes, lgtm, approved
