Repository kubevirt/containerized-data-importer, pull requests merged in 2025-03, with the labels that each got.

#3650 Update golang to 1.23.6 in cdi builder
  hack/build/docker/builder/Dockerfile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3652 Use new 1.23.6 builder
  .golangci.yml
  go.mod
  hack/build/config.sh
  hack/build/run-linters.sh
  pkg/apiserver/webhooks/cdi-validate.go
  pkg/apiserver/webhooks/cdi-validate_test.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/populators/forklift-populator.go
  pkg/image/qemu.go
  pkg/importer/gcs-datasource.go
  pkg/importer/http-datasource.go
  pkg/importer/s3-datasource.go
  staging/src/kubevirt.io/containerized-data-importer-api/go.mod
  tests/basic_sanity_test.go
  tests/operator_test.go
  vendor/modules.txt
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3658 Create prow_multi-arch_release.sh
  automation/prow_multi-arch_release.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3648 Update x/oauth2 to v0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3663 Add GCP hyperdisk capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3667 Revert "Clean up leftover snapshot sources from DataImportCron tests"
  tests/BUILD.bazel
  tests/dataimportcron_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3669 [release-v1.60] Revert "Clean up leftover snapshot sources from DataImportCron tests"
  tests/BUILD.bazel
  tests/dataimportcron_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#3628 Enable Tinycore Functest image multiarch
  BUILD.bazel
  tests/BUILD.bazel
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3673 don't start informer in cert rotation unit tests
  pkg/operator/controller/certrotation_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3651 Adding an if statement for the case that the certDir is not configured
  pkg/importer/registry-datasource.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
