Repository kubevirt/containerized-data-importer, pull requests merged in 2025-02, with the labels that each got.

#3591 Label VDDK and ImageIO tests
  tests/api_validation_test.go
  tests/datavolume_test.go
  tests/import_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3629 [release-v1.59] Manual backport "Move size detection pod deletion to cleanup"
  automation/test.sh
  pkg/controller/datavolume/clone-controller-base.go
  pkg/controller/datavolume/pvc-clone-controller.go
  pkg/controller/datavolume/pvc-clone-controller_test.go
  pkg/controller/datavolume/snapshot-clone-controller.go
  tests/cloner_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3630 Update CDIDataVolumeUnusualRestartCount alert
  pkg/monitoring/rules/alerts/operator.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3520 Change clone strategy to avoid PowerStore snapshot limits
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3633 Add volume capabilities for Oracle Cloud
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3634 Fix error formatting in populators
  pkg/controller/populators/forklift-populator.go
  pkg/controller/populators/import-populator.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3641 add support for infinibox nvme protocol
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3644 Add RWX block to Portworx capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#3646 Add openshift.io/required-scc to required workloads
  pkg/common/common.go
  pkg/controller/BUILD.bazel
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/namespaced/BUILD.bazel
  pkg/operator/resources/namespaced/apiserver.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/namespaced/uploadproxy.go
  pkg/operator/resources/utils/BUILD.bazel
  pkg/operator/resources/utils/common.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
