Repository kubevirt/containerized-data-importer, pull requests merged in 2025-04, with the labels that each got.

#3559 MTV-1699 Avoid potentially exceeding memory limit in multi-stage VDDK imports.
  pkg/importer/vddk-datasource_amd64.go
  pkg/importer/vddk-datasource_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3622 VDDK: Add CRD field for extra configuration arguments
  api/openapi-spec/swagger.json
  doc/datavolumes.md
  manifests/example/vddk-args-field.yaml
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/import-controller_test.go
  pkg/operator/resources/crds_generated.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3639 Clone populator: Add clone source watches
  pkg/controller/populators/BUILD.bazel
  pkg/controller/populators/clone-populator.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3681 Avoid waiting out entire tcp timeout in progress call
  pkg/controller/clone/host-clone.go
  pkg/controller/common/util.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/populators/forklift-populator.go
  pkg/controller/populators/import-populator.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3705 Drop selected-node annotation from temp restore PVC
  pkg/controller/clone/planner.go
  pkg/controller/clone/planner_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3687 Fix Longhorn Filesystem capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3704 uploadserver, tests: include error message for upload failure due to lack of space
  pkg/uploadserver/uploadserver.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3718 [release-v1.59] Fix Longhorn Filesystem capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3710 chore(doc): wrong source used for pvc in docs
  doc/datavolumes.md
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
