Repository kubevirt/containerized-data-importer, pull requests merged in 2025-07, with the labels that each got.

#3821 Add GCNV storage capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3835 [release-v1.62] Add GCNV storage capabilities
  pkg/storagecapabilities/storagecapabilities.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#3807 Add missing RBAC to forklift volume populator CRDs.
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/cluster/controller.go
  pkg/operator/resources/cluster/rbac.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3798 Support DIC DV node pullMethod for update polling
  pkg/controller/dataimportcron-controller.go
  pkg/controller/dataimportcron-controller_test.go
  tests/dataimportcron_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved, needs-approver-review

#3834 [release-v1.60] Tests: Fix flaky variable assignments during Update
  tests/BUILD.bazel
  tests/import_test.go
  tests/upload_test.go
Labels: release-note-none, size/M, dco-signoff: yes, lgtm, approved

#3837 metrics-server: use SecureServing option
  cmd/cdi-controller/BUILD.bazel
  cmd/cdi-controller/controller.go
  cmd/cdi-operator/BUILD.bazel
  cmd/cdi-operator/operator.go
  pkg/operator/controller/prometheus.go
  pkg/operator/resources/namespaced/controller.go
  pkg/operator/resources/operator/operator.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#3764 Populate DV with events from PVC Prime
  pkg/controller/clone-controller.go
  pkg/controller/common/util.go
  pkg/controller/common/util_test.go
  pkg/controller/datavolume/conditions.go
  pkg/controller/datavolume/controller-base.go
  pkg/controller/import-controller.go
  pkg/controller/populators/clone-populator.go
  pkg/controller/populators/import-populator.go
  pkg/controller/populators/populator-base.go
  pkg/controller/populators/upload-populator.go
  pkg/controller/populators/upload-populator_test.go
  pkg/controller/populators/util.go
  pkg/controller/upload-controller.go
  pkg/operator/resources/cluster/controller.go
  pkg/uploadproxy/uploadproxy.go
  tests/basic_sanity_test.go
  tests/datavolume_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#3809 Targeted fsync in resource generating
  hack/build/resource-generator.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#3812 Increase default filesystem overhead to 6%
  api/openapi-spec/swagger.json
  doc/cdi-config.md
  pkg/apis/core/v1beta1/openapi_generated.go
  pkg/common/common.go
  pkg/controller/import-controller_test.go
  pkg/importer/data-processor_test.go
  pkg/operator/resources/crds_generated.go
  pkg/uploadserver/uploadserver_test.go
  pkg/util/util_test.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types.go
  staging/src/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/types_swagger_generated.go
  tests/import_test.go
  tests/upload_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
